### ISSUE TITLE
Failed to run avocado with python2.6 : AttributeError: 'module' object has no attribute 'NullHandler'

### ISSUE THREAD

**Issue by suqinhuang** [avocado-framework/avocado#1053]
Avocado crashed:
Traceback (most recent call last):
  File "/usr/bin/avocado", line 81, in <module>
    from avocado.core.app import AvocadoApp
  File "/home/avocado/avocado/core/app.py", line 25, in <module>
    from .dispatcher import CLIDispatcher
  File "/home/avocado/avocado/core/dispatcher.py", line 17, in <module>
    from stevedore import ExtensionManager
  File "/usr/lib/python2.6/site-packages/stevedore-1.12.0-py2.6.egg/stevedore/__init__.py", line 23, in <module>
    LOG.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'

**Comment by Hao-Liu** [comment]
@suqinhuang, this is caused by newer version (>=1.11.0) of stevedore won't support python2.6.

You can solve this by confining packages version, Just run `make requirement`.

**Comment by suqinhuang** [comment]
ok, will downgrade stevedore if no plan to fix it

**Comment by Hao-Liu** [comment]
Hi @suqinhuang, stevedore developers have dropped support for python-2.6. So from our side we can only fix the version we are using.
