### ISSUE TITLE
Avocado crashed during test OSError: [Errno 36] File name too long: 

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#1091]
# avocado -v
Avocado 0.33.0
Command line used:
avocado run --vt-type libvirt --vt-config /usr/share/avocado/data/avocado-vt/backends/libvirt/cfg/temp.cfg --sysinfo on

Exception loading test
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/runner.py", line 237, in _run_test
    instance = loader.load_test(test_factory)
  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/loader.py", line 260, in load_test
    test_instance = test_class(**test_parameters)
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-0.33.0-py2.7.egg/avocado_vt/test.py", line 113, in __init__
    runner_queue=runner_queue)
  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/test.py", line 113, in __init__
    self.logdir = utils_path.init_dir(base_logdir, safe_tagged_name)
  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/utils/path.py", line 74, in init_dir
    os.makedirs(directory)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/root/avocado/job-results/job-2016-03-23T07.24-0bd7ab4/test-results/guest_backuprestore.qemu.qcow2.scsi.smp2.spapr-vlan.RHEL.7.2.ppc64le.io-github-autotest-libvirt.virsh.snapshot_disk.no_delete.positive_test.no_pool.network_disk.gluster.transport_default.snapshot_from_xml.disk_external.sys_checkpoint.default.memory_external'

Avocado crashed: TestError: Avocado crashed during test load. Some reports might have not been generated. Aborting...
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/job.py", line 497, in _run
    replay_map=replay_map)

  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/runner.py", line 448, in run_suite
    failures, deadline)

  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/runner.py", line 326, in run_test
    test_status.wait_for_early_status(proc, 10)

  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/runner.py", line 115, in wait_for_early_status
    while not self.early_status:

  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/runner.py", line 105, in __getattribute__
    return super(TestStatus, self).__getattribute__(name)

  File "/usr/lib/python2.7/site-packages/avocado-0.33.0-py2.7.egg/avocado/core/runner.py", line 94, in early_status
    raise exceptions.TestError("Avocado crashed during test "

TestError: Avocado crashed during test load. Some reports might have not been generated. Aborting...

**Comment by ldoktor** [comment]
Hello Satheesh, thank you for the report, there is a fix https://github.com/avocado-framework/avocado/pull/1090 under review already, hopefully it works for you too.

**Comment by sathnaga** [comment]
Tried with above fix, not ve hit the crash, Thanks :-)

**Comment by ldoktor** [comment]
It should be fixed by this PR https://github.com/avocado-framework/avocado/pull/1115
