### ISSUE TITLE
The avocado can not give a useful traceback information(file, line number), when import error raised?

### ISSUE THREAD

**Issue by linfenghuaster** [avocado-framework/avocado#1452]

**Comment by apahim** [comment]
Can you demonstrate your problem?

**Comment by linfenghuaster** [comment]
Hello @apahim,  when using the python2.6, the avocado will be crashed, and it only gives the module does not esxit but not gives the line and file.
```python
#!/usr/bin/env python

from avocado import main
from avocado import Test
import does_not_exit

class PassTest(Test):

    """
    Example test that passes.
    """

    def test(self):
        """
        A test simply doesn't have to fail in order to pass
        """
        pass


if __name__ == "__main__":
    main()
```

**Comment by clebergnu** [comment]
@linfenghuaster I can not replicate what you describe.  Here's what I get when listing the code sample you posted:

```
$ avocado list -V /tmp/foo.py 
Type         Test
INSTRUMENTED /tmp/foo.py:PassTest.test

ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
FILTERED: 0
INSTRUMENTED: 1
MISSING: 0
NOT_A_TEST: 0
SIMPLE: 0
```

When running it:

```
[cleber@localhost ~]$ avocado run /tmp/foo.py 
JOB ID     : 108e7ca371cc80fdb25958142c5f3f576feb4d02
JOB LOG    : /home/cleber/avocado/job-results/job-2016-09-12T13.20-108e7ca/job.log
TESTS      : 1
 (1/1) /tmp/foo.py:PassTest.test: ERROR (0.00 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /home/cleber/avocado/job-results/job-2016-09-12T13.20-108e7ca/html/results.html
TESTS TIME : 0.00 s
```

This is on a EL6 box with Python 2.6.6:

```
[cleber@localhost ~]$ python --version
Python 2.6.6
```

And The traceback is recoded (including line number):

```
2016-09-12 13:20:39,793 multiplexer      L0180 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2016-09-12 13:20:39,793 test             L0214 INFO | START 1-/tmp/foo.py:PassTest.test
2016-09-12 13:20:39,794 stacktrace       L0038 ERROR| 
2016-09-12 13:20:39,794 stacktrace       L0041 ERROR| Reproduced traceback from: /home/cleber/src/avocado/avocado/core/test.py:448
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR| Traceback (most recent call last):
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 862, in test
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR|     self.error(self.exception)
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 610, in error
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR|     raise exceptions.TestError(message)
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR| TestError: Traceback (most recent call last):
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR|   File "/tmp/foo.py", line 5, in <module>
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR|     import does_not_exit
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR| ImportError: No module named does_not_exit
2016-09-12 13:20:39,795 stacktrace       L0044 ERROR| 
2016-09-12 13:20:39,795 stacktrace       L0045 ERROR| 
2016-09-12 13:20:39,796 test             L0580 ERROR| ERROR 1-/tmp/foo.py:PassTest.test -> TestError: Traceback (most recent call last):
  File "/tmp/foo.py", line 5, in <module>
    import does_not_exit
ImportError: No module named does_not_exit
```

**Comment by linfenghuaster** [comment]
#1118 seems to resolve this problem, thank you very much.
