### ISSUE TITLE
Missing requirement in spec file

### ISSUE THREAD

**Issue by gbraad** [avocado-framework/avocado#1798]
We are installing Avocado as follows:

```
$ sudo curl https://repos-avocadoproject.rhcloud.com/static/avocado-el.repo -o /etc/yum.repos.d/avocado.repo
$ sudo yum install -y avocado
```

but when running on ci.centos.org ([ref][ref]), with:

```
 $ avocado run --show-job-log tests/test.py
```

we get the following error:
```
Avocado crashed unexpectedly: No module named pkg_resources
```

This might be due to a missing dependency...

[ref]: https://github.com/minishift/minishift-b2d-iso/pull/30

**Comment by clebergnu** [comment]
Yes, I can confirm and reproduce this.  Basically, we've relied (and shouldn't) on python-setuptools being provided as a depedency of other packages such as python-stevedore.  On EL, python-stevedore uses setuptools:

```
# grep -ir pkg_resources /usr/lib/python2.7/site-packages/stevedore/*py
/usr/lib/python2.7/site-packages/stevedore/extension.py:import pkg_resources
/usr/lib/python2.7/site-packages/stevedore/extension.py:        :mod:`pkg_resources`.
/usr/lib/python2.7/site-packages/stevedore/extension.py:            eps = list(pkg_resources.iter_entry_points(namespace))
``` 

But doesn't list it as a dependecy:

```
# rpm -qR python-stevedore 
python(abi) = 2.7
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

Since Avocado uses setuptools explicitly (for instance, on `avocado.core.version`), it should indeed list it as a depedency.

**Comment by gbraad** [comment]
@clebergnu When do new packages get created? Since at the moment we have a workaround in place by adding the dependency to the a setup_ci script.

**Comment by ldoktor** [comment]
Last release was on the 13th, therefor the next one should be on 6th (or the week after if we wait for some blockers).

**Comment by uberhacker** [comment]
This issue has apparently reoccurred in the 58.0 release.  Can we reopen?

**Comment by ldoktor** [comment]
Hello @uberhacker, the `python-setuptools` is still listed as a dependency, can you please provide the actual version you're installing as well as the error message?

**Comment by uberhacker** [comment]
@ldoktor:
```
$ python -V
Python 2.7.14
$ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ pip install avocado-framework --prefix /usr/local
Collecting avocado-framework
  Using cached avocado_framework-58.0-py2-none-any.whl
Collecting six>=1.10.0 (from avocado-framework)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting stevedore>=0.14 (from avocado-framework)
  Using cached stevedore-1.28.0-py2.py3-none-any.whl
Collecting pbr!=2.1.0,>=2.0.0 (from stevedore>=0.14->avocado-framework)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Installing collected packages: six, pbr, stevedore, avocado-framework
Successfully installed avocado-framework-58.0 pbr-3.1.1 six-1.11.0 stevedore-1.28.0
$ avocado
Avocado crashed unexpectedly: No module named pkg_resources
You can find details in /usr/local/tmp/avocado-traceback-2018-02-23_08:21:03-e3eO86.log
```

**Comment by ldoktor** [comment]
I see, the issue was that `spec` file lacks this dependency and that was addressed, unfortunately without the `setup.py`. Fixing it now.

**Comment by uberhacker** [comment]
@ldoktor: Has this issue been addressed yet?  I'm getting the same error with the 60.0 release.

**Comment by ldoktor** [comment]
There were some issues related to python3 packaging, but new package should be released soon (right @clebergnu?).

**Comment by uberhacker** [comment]
Thank you for the feedback @clebergnu.  I'm attempting to install from source since a package manager is not available on my Chromebook.

System specs:
```
$ cat /etc/lsb-release 
CHROMEOS_RELEASE_BOARD=x86-pentiumm
CHROMEOS_DEVSERVER=http://devserver.crosbuilder.click:44225
GOOGLE_RELEASE=9592.96.2017_09_20_2221
CHROMEOS_RELEASE_BUILD_NUMBER=9592
CHROMEOS_RELEASE_BRANCH_NUMBER=96
CHROMEOS_RELEASE_CHROME_MILESTONE=60
CHROMEOS_RELEASE_PATCH_NUMBER=2017_09_20_2221
CHROMEOS_RELEASE_TRACK=developer-build
CHROMEOS_RELEASE_DESCRIPTION=9592.96.2017_09_20_2221 (Developer Build - chromium) developer-build x86-pentiumm
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - chromium
CHROMEOS_RELEASE_VERSION=9592.96.2017_09_20_2221
CHROMEOS_AUSERVER=http://update.crosbuilder.click:44225/update
$ uname -a
Linux localhost 4.4.64 #13 SMP PREEMPT Wed Sep 20 09:49:58 JST 2017 i686 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz GenuineIntel GNU/Linux
$ python3 --version
Python 3.6.4
$ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
```
Installation:
```
$ wget https://github.com/avocado-framework/avocado/archive/60.0.tar.gz
$ tar xvf 60.0.tar.gz 
$ cd avocado-60.0/
$ pip3 install setuptools
$ pip3 install -r https://raw.githubusercontent.com/avocado-framework/avocado/60.0/requirements.txt --prefix /usr/local
$ python3 setup.py install --prefix /usr/local
$ avocado
Avocado crashed unexpectedly: No module named 'pkg_resources'
You can find details in /usr/local/tmp/avocado-traceback-2018-04-13_08:47:01-30y_4i2_.log
$ cat /usr/local/tmp/avocado-traceback-2018-04-13_08:47:01-30y_4i2_.log
Avocado crashed:
Traceback (most recent call last):
  File "/usr/local/bin/avocado", line 62, in <module>
    from avocado.core.app import AvocadoApp    # pylint: disable=E0611
  File "/usr/local/lib/python3.6/site-packages/avocado/__init__.py", line 28, in <module>
    from avocado.core.job import main
  File "/usr/local/lib/python3.6/site-packages/avocado/core/job.py", line 33, in <module>
    from . import version
  File "/usr/local/lib/python3.6/site-packages/avocado/core/version.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by lmr** [comment]
Is virtualenv an option? Much better and cleaner than performing a system wide install.

**Comment by ldoktor** [comment]
A bit of googling suggests the `setuptools` were probably not installed properly: https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources I'd not suggest the first answer, but later people suggest `pip install --upgrade setuptools`. If that doesn't help make sure your `pip` is the latest (run `pip install --upgrade pip` first) and then try again. Worst case try the first answer, but I'd not run such command on my personal laptop.

PS: Yes, using virtualenv should be slightly better.

**Comment by uberhacker** [comment]
Just wanted to update you guys that I found a solution.  Not sure why it makes any difference but this works:
```bash
$ wget https://github.com/avocado-framework/avocado/archive/60.0.tar.gz
$ tar xvf 60.0.tar.gz 
$ cd avocado-60.0/
$ pip3 install setuptools
$ pip3 install avocado-framework -r requirements.txt
$ avocado -v
Avocado 60.0
```

**Comment by ldoktor** [comment]
OK, good to know. Let us know if anything changes but it looks more like `pip` issue than ours.
