### ISSUE TITLE
xunit output is not JUNIT comliant (jenkins)

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1905]
Hi,

I have generated xunit file which contains failed tests and Jenkins is not able to interpret is as results (attached)
[out.xunit.txt](https://github.com/avocado-framework/avocado/files/892702/out.xunit.txt)

@apahim found that there is issue like: 
 out.xunit:9:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'system-out': This element is not expected.
    
    Regards
    Honza

**Comment by apahim** [comment]
We are generating the xml in an incompatible format when a failure happens:

```python
>>> from lxml import etree
>>> from StringIO import StringIO
>>> from avocado.utils import process
>>> 
>>> 
>>> with open('selftests/unit/junit-4.xsd', 'r') as f:
...     xmlschema = etree.XMLSchema(etree.parse(f))
... 
>>> xml = StringIO(process.system_output('avocado run failtest.py --xunit -', ignore_status=True))
>>> 
>>> xmlschema.validate(etree.parse(xml))
False
>>> print(xmlschema.error_log.filter_from_errors()[0])
<string>:9:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'system-out': This element is not expected.
```

Here the snip from the `avocado/plugins/xunit.py`:

```python
...
    def _create_failure_or_error(self, document, test, element_type):
        element = Element(element_type)
        element.setAttribute('type', self._get_attr(test, 'fail_class'))
        element.setAttribute('message', self._get_attr(test, 'fail_reason'))
        traceback_content = self._escape_cdata(test.get('traceback', self.UNKNOWN))
        traceback = document.createCDATASection(traceback_content)
        element.appendChild(traceback)
        system_out = Element('system-out') <=========== This element is making the validation to fail
        try:
            with open(test.get("logfile"), "r") as logfile_obj:
                text_output = logfile_obj.read()
        except (TypeError, IOError):
            text_output = self.UNKNOWN
        system_out_cdata_content = self._escape_cdata(text_output)
        system_out_cdata = document.createCDATASection(system_out_cdata_content)
        system_out.appendChild(system_out_cdata)
        element.appendChild(system_out)
        return element
...
    def _render(self, result):
        ...

            elif status == 'FAIL':
                element = self._create_failure_or_error(document, test, 'failure')
        ...
```

We need to double check where the `system-out` actually goes. According to the `avocado/selftests/unit/junit-4.xsd`, we have:

```xml
    <xs:element name="testcase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="skipped" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="error" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="failure" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="system-out" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="system-err" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="assertions" type="xs:string" use="optional"/>
            <xs:attribute name="time" type="xs:string" use="optional"/>
            <xs:attribute name="classname" type="xs:string" use="optional"/>
            <xs:attribute name="status" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
```

Seems like the `system_out` and the `failure` element should be in the same level. But we are currently creating the `system_out` as a `failure` child:

```
~$ avocado run failtest.py failtest.py --xunit -
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="2" name="avocado" skipped="0" tests="2" time="0.0716989040375" timestamp="2017-04-04 12:18:28.287761">
        <testcase classname="FailTest" name="1-failtest.py:FailTest.test" time="0.0389058589935">
                <failure message="This test is supposed to fail" type="TestFail">
<![CDATA[Traceback (most recent call last):
  File "/home/apahim/git/avocado/avocado/core/test.py", line 671, in _run_avocado
    raise test_exception
TestFail: This test is supposed to fail
]]>                     <system-out>
<![CDATA[12:18:27 ERROR|
12:18:27 ERROR| Reproduced traceback from: /home/apahim/git/avocado/avocado/core/test.py:600
12:18:27 ERROR| Traceback (most recent call last):
12:18:27 ERROR|   File "/usr/share/avocado/tests/failtest.py", line 19, in test
12:18:27 ERROR|     self.fail('This test is supposed to fail')
12:18:27 ERROR|   File "/home/apahim/git/avocado/avocado/core/test.py", line 766, in fail
12:18:27 ERROR|     raise exceptions.TestFail(message)
12:18:27 ERROR| TestFail: This test is supposed to fail
12:18:27 ERROR|
12:18:27 DEBUG| Local variables:
12:18:27 DEBUG|  -> self <class 'failtest.FailTest'>: 1-failtest.py:FailTest.test
12:18:27 ERROR| FAIL 1-failtest.py:FailTest.test -> TestFail: This test is supposed to fail
12:18:27 INFO |
]]>                     </system-out>
                </failure>
        </testcase>
        <testcase classname="FailTest" name="2-failtest.py:FailTest.test" time="0.0327930450439">
                <failure message="This test is supposed to fail" type="TestFail">
<![CDATA[Traceback (most recent call last):
  File "/home/apahim/git/avocado/avocado/core/test.py", line 671, in _run_avocado
    raise test_exception
TestFail: This test is supposed to fail
]]>                     <system-out>
<![CDATA[12:18:27 ERROR|
12:18:27 ERROR| Reproduced traceback from: /home/apahim/git/avocado/avocado/core/test.py:600
12:18:27 ERROR| Traceback (most recent call last):
12:18:27 ERROR|   File "/usr/share/avocado/tests/failtest.py", line 19, in test
12:18:27 ERROR|     self.fail('This test is supposed to fail')
12:18:27 ERROR|   File "/home/apahim/git/avocado/avocado/core/test.py", line 766, in fail
12:18:27 ERROR|     raise exceptions.TestFail(message)
12:18:27 ERROR| TestFail: This test is supposed to fail
12:18:27 ERROR|
12:18:27 DEBUG| Local variables:
12:18:28 DEBUG|  -> self <class 'failtest.FailTest'>: 2-failtest.py:FailTest.test
12:18:28 ERROR| FAIL 2-failtest.py:FailTest.test -> TestFail: This test is supposed to fail
12:18:28 INFO |
]]>                     </system-out>
                </failure>
        </testcase>
</testsuite>

```
Moving the `system_out` one level up, the validation passes. @clebergnu, @ldoktor  what do you think?

**Comment by lmr** [comment]
Yep, according to http://llg.cubic.org/docs/junit/, `system_out` and `failure` should both be children of testcase, so avocado is wrong. Which is weird, given that I've used recent avocado master, not older than maybe 2 or 3 weeks successfully with the jenkins junit plugin.

**Comment by apahim** [comment]
@lmr thank you for the confirmation. I'm sending a fix.

**Comment by clebergnu** [comment]
IIRC, LTS has a different xunit implementation.  @apahim can you check that we pass validation there while I review this PR?

**Comment by apahim** [comment]
Fixed by https://github.com/avocado-framework/avocado/pull/1907.

**Comment by apahim** [comment]
@clebergnu 36lts branch is not affected by this issue.

**Comment by clebergnu** [comment]
@apahim thanks!
