### ISSUE TITLE
Avocado crashed unexpectedly: argument --html: conflicting option string(s): --html

### ISSUE THREAD

**Issue by xutian** [avocado-framework/avocado#1911]
```
Avocado crashed:
Traceback (most recent call last):
  File "/usr/bin/avocado", line 4, in <module>
    __import__('pkg_resources').run_script('avocado-framework==48.0', 'avocado')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/EGG-INFO/scripts/avocado", line 85, in <module>
    app = AvocadoApp()
  File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/core/app.py", line 61, in __init__
    self.cli_dispatcher.map_method('configure', self.parser)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 282, in map_method
    method_name, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 255, in map
    self._invoke_one_plugin(response.append, func, e, args, kwds)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 286, in _invoke_one_plugin
    response_callback(func(e, *args, **kwds))
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 260, in _call_extension_method
    return getattr(extension.obj, method_name)(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/avocado_result_html/__init__.py", line 317, in configure
    help=('Enable HTML output to the FILE where the result should be '
  File "/usr/lib64/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib64/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib64/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib64/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib64/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib64/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib64/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --html: conflicting option string(s): --html

```

**Comment by xutian** [comment]
it looks avocado-result-html (46.0)  conflict with avocado-framework-plugin-result-html(48.0)

**Comment by sathnaga** [comment]
Try cleaning all the previous installed instances of avocado and html plugin, and freshly install both, this goes away.

**Comment by clebergnu** [comment]
Right.  This happens because the Python module name changed in 48.0.  If you leave the old (46.0 in that case) version around, both (with different names) will be initialized, and both will attempt to add the `--html` options.

As @sathnaga already pointed out, it's just a matter of cleaning the previous installation (the `.egg-info` directiories more specifically).
