### ISSUE TITLE
archive.extract of zip fails when running for multiple variants with teststmpdir ( which is common for all variants)

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#1931]
When running with multiple variants, if `self.teststmpdir` is used as destination directory in `archive.extract`,  on second variant the following issue is found when extracting zip file.

```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/core/test.py:578
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR| Traceback (most recent call last):
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR|   File "/var/lib/libvirt/images/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/tests/avocado-misc-tests/generic/ltp.py", line 50, in setUp
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR|     archive.extract(tarball, self.teststmpdir)
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/utils/archive.py", line 242, in uncompress
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|     x.extract(path)
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/utils/archive.py", line 168, in extract
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|     self._update_zip_extra_attrs(path)
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/utils/archive.py", line 192, in _update_zip_extra_attrs
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|     os.symlink(src, dst)
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR| OSError: [Errno 36] File name too long
```
No issue is observed when extracting a tar file.

**Comment by ldoktor** [comment]
@harish-24 can you please provide more details? Ideally the zip file (as it fails during updating of the extra attrs which is our custom handling). If that is not possible, could you please provide other details about the execution, does it also fail when running just one variant, or with default values only and so on.

**Comment by harish-24** [comment]
@ldoktor The failure is only when running with multiple variants. 
Eg: https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/ltp.py,
`avocado run ltp.py -m ltp.py.data/ltp.yaml`.
In the above scenario, `ltp-master.zip` is extracted in `self.teststmpdir` and working as expected for first variant. As the directory is extracted already for first variant,  issue occurs during `os.symlink` for the second variant.
Same scenario when tried with a tar instead of a zip, did not have any issues.

**Comment by ldoktor** [comment]
Hello @harish-24, thank you for the details, there are basically two issues. First one is that `zipfile` library doesn't treats symlinks and when it already exists it skips it. I sent a fix for that here: https://github.com/avocado-framework/avocado/pull/1939

The second issue is that in the test you are extracting already extracted file. That itself is not really an issue, it's just not necessary. So I'd recommend something like this:

```diff
diff --git a/generic/ltp.py b/generic/ltp.py
index d7d68ce..fa4ca4d 100644
--- a/generic/ltp.py
+++ b/generic/ltp.py
@@ -45,17 +45,21 @@ class ltp(Test):
         for package in deps:
             if not sm.check_installed(package) and not sm.install(package):
                 self.error(package + ' is needed for the test to be run')
-        url = "https://github.com/linux-test-project/ltp/archive/master.zip"
-        tarball = self.fetch_asset("ltp-master.zip", locations=[url])
-        archive.extract(tarball, self.srcdir)
-        ltp_dir = os.path.join(self.srcdir, "ltp-master")
-        os.chdir(ltp_dir)
-        build.make(ltp_dir, extra_args='autotools')
-        ltpbin_dir = os.path.join(ltp_dir, 'bin')
-        os.mkdir(ltpbin_dir)
-        process.system('./configure --prefix=%s' % ltpbin_dir)
-        build.make(ltp_dir)
-        build.make(ltp_dir, extra_args='install')
+        setup_finished_file = os.path.join(self.teststmpdir,
+                                           "ltp-setup-completed")
+        if not os.path.exists(setup_finished_file):
+            url = "https://github.com/linux-test-project/ltp/archive/master.zip"
+            tarball = self.fetch_asset("ltp-master.zip", locations=[url])
+            archive.extract(tarball, self.teststmpdir)
+            ltp_dir = os.path.join(self.teststmpdir, "ltp-master")
+            os.chdir(ltp_dir)
+            build.make(ltp_dir, extra_args='autotools')
+            ltpbin_dir = os.path.join(ltp_dir, 'bin')
+            os.mkdir(ltpbin_dir)
+            process.system('./configure --prefix=%s' % ltpbin_dir)
+            build.make(ltp_dir)
+            build.make(ltp_dir, extra_args='install')
+            open(setup_finished_file, 'a').close()
```

(haven't really tested that one, but the idea is there...)

**Comment by ldoktor** [comment]
PS: Both of the proposed fixes work and they should both be applied

**Comment by ldoktor** [comment]
OK the fix was applied, feel free to re-open this issue if that didn't work well for you...
