### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'base_logdir'

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1984]
I've met issue that something weong with init method:
 see sources for this trouble
### base-runtime module setup docker image
https://github.com/fedora-modularity/baseruntime-docker-tests/blob/master/setup.py

### modularity testing framework (built on top of Avocado (derived class))
https://pagure.io/modularity-testing-framework/blob/master/f/moduleframework/module_framework.py

### output
```
    $ sudo python ./setup.py
    found extension EntryPoint.parse('journal = avocado.plugins.journal:JournalResult')
    found extension EntryPoint.parse('tap = avocado.plugins.tap:TAPResult')
    found extension EntryPoint.parse('human = avocado.plugins.human:Human')
    found extension EntryPoint.parse('teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir')
    found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
    Command line: ./setup.py
     
    Avocado version: 46.0
     
    Config files read (in order):
    /etc/avocado/avocado.conf
    /etc/avocado/conf.d/gdb.conf
    /root/.config/avocado/avocado.conf
     
    Avocado config:
    Section.Key                             Value
    datadir.paths.base_dir                  /usr/share/avocado
    datadir.paths.test_dir                  /usr/share/avocado/tests
    datadir.paths.data_dir                  /usr/share/avocado/data
    datadir.paths.logs_dir                  ~/avocado/job-results
    sysinfo.collect.enabled                 True
    sysinfo.collect.commands_timeout        -1
    sysinfo.collect.installed_packages      False
    sysinfo.collect.profiler                False
    sysinfo.collect.locale                  C
    sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
    sysinfo.collectibles.files              /etc/avocado/sysinfo/files
    sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
    runner.output.colored                   True
    runner.output.utf8                      
    remoter.behavior.reject_unknown_hosts   False
    remoter.behavior.disable_known_hosts    False
    job.output.loglevel                     debug
    restclient.connection.hostname          localhost
    restclient.connection.port              9405
    restclient.connection.username          
    restclient.connection.password          
    plugins.disable                         []
    plugins.skip_broken_plugin_notification []
    plugins.loaders                         ['file', '@DEFAULT']
    gdb.paths.gdb                           /usr/bin/gdb
    gdb.paths.gdbserver                     /usr/bin/gdbserver
     
    Avocado Data Directories:
     
    Avocado replaces config dirs that can't be accessed
    with sensible defaults. Please edit your local config
    file to customize values
     
    base     /usr/share/avocado
    tests    /usr/share/avocado/tests
    data     /usr/share/avocado/data
    logs     /root/avocado/job-results
     
    Temporary dir: /tmp/avocado_qfBbNq
     
    Variant 1:    /
     
    Job ID: dbed16bfadcdfb00512d7c8c24a260b7570076f4
     
    Process Process-1:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python2.7/site-packages/avocado/core/runner.py", line 303, in _run_test
        instance = loader.load_test(test_factory)
      File "/usr/lib/python2.7/site-packages/avocado/core/loader.py", line 311, in load_test
        test_instance = test_class(**test_parameters)
    TypeError: __init__() got an unexpected keyword argument 'base_logdir'
     
    Avocado crashed: TestError: Process died before it pushed early test_status.
    Please include the traceback info and command line used on your bug report
    Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

**Comment by jscotka** [comment]
Probably good to mentione that I've met also similar issue, caused by that, there is hardcoded timeout for class initialization to 60s, and when I've defined own `__init__` for class derived from avocado.Test and done there some package installation -> it caused that this limit were easily exceeded, and I were unable to find way how to increase this `__init__` limit

**Comment by clebergnu** [comment]
@jscotka can this be closed after the following fix?

https://pagure.io/modularity-testing-framework/c/88218561576df83529d3f1183e6607e2675103e9?branch=master

Or is the previous comment a second issue?

**Comment by jscotka** [comment]
comment https://github.com/avocado-framework/avocado/issues/1984#issuecomment-300135201 is completely anoter issue, just little bit connected with using __init__ method redefinition

**Comment by jscotka** [comment]
this issue can be closed, your solution works well.
Maybe it could be also somehow documented, that in case of multiple inheritance, you should have `avocado.Test` as first parent to able to call __init__
