### ISSUE TITLE
MemoryError: out of memory

### ISSUE THREAD

**Issue by amoskong** [avocado-framework/avocado#2009]
Version: 36.4

Avocado run 7 days (scylla-longevity test), and get a MemoryError at the end of test.
Will Avocado use more memory at the end of test? or loading/swapping sth to memory?

```
2017-05-02 08:54:08,638 output           L0642 DEBUG| Process Process-1:
2017-05-02 08:54:08,639 output           L0642 DEBUG| Traceback (most recent call last):
2017-05-02 08:54:08,641 output           L0642 DEBUG|   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2017-05-02 08:54:08,644 output           L0642 DEBUG|     self.run()
2017-05-02 08:54:08,644 output           L0642 DEBUG|   File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
2017-05-02 08:54:08,645 output           L0642 DEBUG|     self._target(*self._args, **self._kwargs)
2017-05-02 08:54:08,645 output           L0642 DEBUG|   File "/usr/lib/python2.7/site-packages/avocado/core/runner.py", line 249, in _run_test
2017-05-02 08:54:08,652 output           L0642 DEBUG|     queue.put(instance.get_state())
2017-05-02 08:54:08,652 output           L0642 DEBUG|   File "/usr/lib64/python2.7/multiprocessing/queues.py", line 390, in put
2017-05-02 08:54:08,653 output           L0642 DEBUG|     return send(obj)
2017-05-02 08:54:08,654 output           L0642 DEBUG| MemoryError: out of memory
```

**Comment by ldoktor** [comment]
Hello @amoskong, it'd be nice to monitor the memory utilization throughout the execution, whether it's continual increase, or a peek.

Anyway to your question the traceback suggests the test process tried to send the test status to the runner. That means it first gets the status from the test (a new dictionary with ~20 items mainly containing short strings) and then it tries to send it via queue (which means serializing this new dictionary and sending it over to the other process which needs to deserialize it). So yes, there are some data transferred, but it should be a matter of KB (well it's python so units of MB, but it should not be tenths or hundreds).

Do you use `avocado.utils.process` in your tests? If so the problem can be caused when the process finishes and it fills the `stdout`/`stderr` in `result` as it loads the full output and stores it in memory.

**Comment by ldoktor** [comment]
Btw just out of curiosity I made a simple measurement and got these results:

```
When:   total_mem_cgroup    runner_rss  test_rss

Before report:  126668800   99212  88492
get_state:      135286784   99212   88656
put_state:      135417856   99212   88656
test finished:  79716352    99212

runner loop:    79847424    99444
end_test disp:  80097280    99520
end_of_runner:  80224256    100228
job_end:        80347136    100424
res_disp_rend:  80740352    100492

all exit:       4108288
```

Where:
 * When - when the measurement was produced
 * total_mem_cgroup - `memory.memsw.usage_in_bytes` including xterm avocado was executed from
 * runner_rss - RSS memory of the main Avocado process
 * test_rss - RSS memory of the test process

**Comment by clebergnu** [comment]
@amoskong any updates on the questions raised by @ldoktor ?

**Comment by clebergnu** [comment]
@amoskong I'm closing this issue for now, please reopen if you're able to follow up with it.  Thanks!
