### ISSUE TITLE
Avocado fails to replay jobs if remote plugin is not installed

### ISSUE THREAD

**Issue by benzea** [avocado-framework/avocado#2116]
The replay plugin checks that remote_hostname is not set in the arguments. Unfortunately the attribute does not even exist if the plugin is not installed and then it fails with an attribute error:

```Avocado crashed:
Traceback (most recent call last):
  File "/usr/bin/avocado", line 85, in <module>
    app = AvocadoApp()
  File "/usr/lib/python2.7/site-packages/avocado/core/app.py", line 64, in __init__
    self.cli_dispatcher.map_method('run', self.parser.args)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 259, in map_method
    method_name, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 232, in map
    self._invoke_one_plugin(response.append, func, e, args, kwds)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 263, in _invoke_one_plugin
    response_callback(func(e, *args, **kwds))
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 237, in _call_extension_method
    return getattr(extension.obj, method_name)(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/avocado/plugins/replay.py", line 175, in run
    elif args.remote_hostname:
AttributeError: 'Namespace' object has no attribute 'remote_hostname'
```

The fix is as simple as adding a hasattr() to replay.py line 175.

**Comment by clebergnu** [comment]
@benzea thanks for reporting this issue.  And yes, your description and proposed approach to fix this issue makes sense.

**Comment by ldoktor** [comment]
Hello @benzea, thank you for suggesting this, next time don't be shy and send a patch (or feel free to still send it, I won't mind that). It'll make your issue resolved faster 😉
