### ISSUE TITLE
avocado aexpect tmp files not getting cleared

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#2247]
tmp files created by tests are _**not**_ getting cleaned properly and making the root filesystem completely filled leaving behind subsequent tests crashed and failed to start due to low space.

```
tmp]# ls
aexpect_00VFyXBZ  aexpect_9lZK98HD  aexpect_Et0jlBZr  aexpect_kblKLdzp  aexpect_q37n9czn  aexpect_x6y31o1P
aexpect_14TNLnHJ  aexpect_9QSlj1Jf  aexpect_eTUqlIma  aexpect_KhJIvAYQ  aexpect_QmjvVQaL  aexpect_xDhISDxi
aexpect_1sJZT5l3  aexpect_ae5INvB7  aexpect_EXN6jMWY  aexpect_kJMAyNIj  aexpect_qMQAnA5X  aexpect_xF1g0kE8
aexpect_1ULbqglB  aexpect_aeyJg1gw  aexpect_F1uNVDTj  aexpect_km9f4Atr  aexpect_QtnYFtF8  aexpect_xFP8CLtD
aexpect_1Vk9Ad43  aexpect_AJ8s1cpG  aexpect_F5jpRw2w  aexpect_KNVcsT5r  aexpect_qVF0cIKX  aexpect_XL7hKbDY
aexpect_29R4TSOF  aexpect_aKV1ejWx  aexpect_Fa3YEvt1  aexpect_KpEj9J7G  aexpect_raraFAhe  aexpect_XLeAfQ5w
aexpect_2cjEs9ut  aexpect_aLBwNHBF  aexpect_fABE0R44  aexpect_L41nOeEk  aexpect_re1NmnEI  aexpect_YdA8xPEJ
aexpect_2DRXXptK  aexpect_AwmLCFwo  aexpect_fmUu4aDv  aexpect_l43Evu7R  aexpect_RHndKMLP  aexpect_ydzuHndI
aexpect_2H2CZNkX  aexpect_axbIBgAG  aexpect_frACNbOU  aexpect_lCsnuM9w  aexpect_rpTH7yEg  aexpect_yiDhHIFs
aexpect_2i2zc3Pk  aexpect_bdynEuzE  aexpect_fz5fsrQW  aexpect_lf2cIbNU  aexpect_rQMJa4Mw  aexpect_yKBeHUY1
aexpect_2KjKnTzw  aexpect_bKpSTAoc  aexpect_GcWErV9G  aexpect_LKARRM4O  aexpect_rt0k43TL  aexpect_yNaZU9GG

```

```
avocado crashed: TestError: Process died before it pushed early test_status.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado_framework-54.1-py2.7.egg/avocado/core/job.py", line 471, in run_tests
    execution_order)

  File "/usr/lib/python2.7/site-packages/avocado_framework-54.1-py2.7.egg/avocado/core/runner.py", line 598, in run_suite
    deadline):

  File "/usr/lib/python2.7/site-packages/avocado_framework-54.1-py2.7.egg/avocado/core/runner.py", line 386, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/usr/lib/python2.7/site-packages/avocado_framework-54.1-py2.7.egg/avocado/core/runner.py", line 157, in wait_for_early_status
    raise exceptions.TestError("Process died before it pushed "

TestError: Process died before it pushed early test_status.

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
JOB HTML   : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2017-10-06T22.51-8ba4bd4/results.html
.....
.....
...
JOB ID     : 702d157c5325132bb2d5225dc2f2bd7631bb6528
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2017-10-07T23.50-702d157/job.log
Failure trying to set Avocado-VT job lock: [Errno 28] No space left on device: '/tmp/avocado-vt-joblock-702d157c5325132bb2d5225dc2f2bd7631bb6528-0-cgsw0l3d.pid'

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_plugins_vt-54.0-py2.7.egg/avocado_vt/plugins/vt_joblock.py:134
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-54.0-py2.7.egg/avocado_vt/plugins/vt_joblock.py", line 106, in _lock
    self.lock_file = self._create_self_lock_file(job)
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-54.0-py2.7.egg/avocado_vt/plugins/vt_joblock.py", line 85, in _create_self_lock_file
    raise LockCreationError(e)
LockCreationError: [Errno 28] No space left on device: '/tmp/avocado-vt-joblock-702d157c5325132bb2d5225dc2f2bd7631bb6528-0-cgsw0l3d.pid'

23:51:58 INFO    : 
```

**Comment by sathnaga** [comment]
It is more relevant for avocado-vt, created there, https://github.com/avocado-framework/avocado-vt/issues/1183
