### ISSUE TITLE
[BUG] utils: build.py fails with latest update

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#2476]
With the removal of few arguments, `build.run_make` fails.

Ex: caller: https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/memory/libhugetlbfs.py#L180

hits with the following issue.
```
05:40:59 DEBUG| Local variables:
05:40:59 DEBUG|  -> self <class 'libhugetlbfs.libhugetlbfs'>: 1-memory/libhugetlbfs.py:libhugetlbfs.test
05:40:59 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
05:40:59 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
05:40:59 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
05:40:59 ERROR| Traceback (most recent call last):
05:40:59 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-58.0-py2.7.egg/avocado/core/test.py", line 932, in _run_avocado
    raise test_exception
05:40:59 ERROR| AttributeError: 'NoneType' object has no attribute 'get'
05:40:59 ERROR| ERROR 1-memory/libhugetlbfs.py:libhugetlbfs.test -> AttributeError: 'NoneType' object has no attribute 'get'
05:40:59 ERROR|
05:40:59 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado_framework-58.0-py2.7.egg/avocado/core/test.py:834
05:40:59 ERROR| Traceback (most recent call last):
05:40:59 ERROR|   File "/root/harish/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/libhugetlbfs.py", line 185, in test
05:40:59 ERROR|     extra_args='BUILDTYPE=NATIVEONLY check').stdout)
05:40:59 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-58.0-py2.7.egg/avocado/utils/build.py", line 40, in run_make
05:40:59 ERROR|     env = process_kwargs.get('env', {})
05:40:59 ERROR| AttributeError: 'NoneType' object has no attribute 'get'
05:40:59 ERROR|
```

**Comment by harish-24** [comment]
Fails at https://github.com/avocado-framework/avocado/blob/master/avocado/utils/build.py#L40 argument is empty.

**Comment by harish-24** [comment]
Closing this with #2478
