### ISSUE TITLE
avocado crashed as [Errno 2] No such file or directory: '/var/lib/libvirt/images/avocado_bGRMUJ'

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#2521]
I try to execute avocado-misc test using  upstream  avocado lib but avocado crashed 

```

root@ubuntu:~/avocado# avocado run /root/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/hugepage_sanity.py
Failed to load plugin from module "avocado_vt.plugins.vt_list": OSError(2, 'No such file or directory')
Failed to load plugin from module "avocado_vt.plugins.vt": OSError(2, 'No such file or directory')
Failed to load plugin from module "avocado_vt.plugins.vt_bootstrap": OSError(2, 'No such file or directory')
Failed to load plugin from module "avocado_vt.plugins.vt_joblock": OSError(2, 'No such file or directory')
Avocado crashed unexpectedly: [Errno 2] No such file or directory: '/var/lib/libvirt/images/avocado_bGRMUJ'
You can find details in /var/tmp/avocado-traceback-2018-03-17_09:33:23-RKfpV7.log
root@ubuntu:~/avocado# cat /var/tmp/avocado-traceback-2018-03-17_09:33:23-RKfpV7.log
Avocado crashed:
Traceback (most recent call last):
  File "/usr/local/bin/avocado", line 4, in <module>
    __import__('pkg_resources').run_script('avocado-framework==59.0', 'avocado')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 765, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1545, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/avocado_framework-59.0-py2.7.egg/EGG-INFO/scripts/avocado", line 75, in <module>
    sys.exit(app.run())
  File "/usr/local/lib/python2.7/dist-packages/avocado_framework-59.0-py2.7.egg/avocado/core/app.py", line 97, in run
    data_dir.clean_tmp_files()
  File "/usr/local/lib/python2.7/dist-packages/avocado_framework-59.0-py2.7.egg/avocado/core/data_dir.py", line 269, in clean_tmp_files
    tmp_dir = get_tmp_dir()
  File "/usr/local/lib/python2.7/dist-packages/avocado_framework-59.0-py2.7.egg/avocado/core/data_dir.py", line 251, in get_tmp_dir
    tmp_dir = _tmp_tracker.get(basedir)
  File "/usr/local/lib/python2.7/dist-packages/avocado_framework-59.0-py2.7.egg/avocado/core/data_dir.py", line 213, in get
    dir=self.basedir)
  File "/usr/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/lib/libvirt/images/avocado_bGRMUJ'

root@ubuntu:~/avocado#
```

**Comment by apahim** [comment]
Errors are coming from Avocado-VT. Is Avocado-VT a requirement for you? If not, try `make clean; make develop`, but we should investigate the Avocado-VT error anyway.

**Comment by PraveenPenguin** [comment]
@apahim thanks now it worked when do `make clean; make develop`

**Comment by PraveenPenguin** [comment]
closing this issue as it tuns environment  issue @apahim thanks for help
