### ISSUE TITLE
Process: UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado#2561]
```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_plugins_vt-60.0-py2.7.egg/avocado_vt/test.py:415
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-60.0-py2.7.egg/virttest/error_context.py", line 135, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-60.0-py2.7.egg/virttest/env_process.py", line 762, in preprocess
    env["cpu_model"] = utils_misc.get_qemu_best_cpu_model(params)
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-60.0-py2.7.egg/virttest/utils_misc.py", line 2342, in get_qemu_best_cpu_model
    qemu_cpu_models = get_qemu_cpu_models(qemu_binary)
  File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-60.0-py2.7.egg/virttest/utils_misc.py", line 2228, in get_qemu_cpu_models
    return extract_qemu_cpu_models(result.stdout_text)
  File "/usr/lib/python2.7/site-packages/avocado_framework-60.0-py2.7.egg/avocado/utils/process.py", line 326, in stdout_text
    return self.stdout.decode(self.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb in position 1277: ordinal not in range(128)
```

The issue is caused by two things:

1. there is some junk in the output of command `qemu-kvm -cpu ?` see https://bugzilla.redhat.com/show_bug.cgi?id=1532195
2. after merged https://github.com/avocado-framework/avocado-vt/pull/1476, `stdout` would be replaced by `stdout_text` which currently would raise error if there are bytes could not be decoded in the output stream.

To solve this problem, I would suggest to pass `errors=ignore` to the `decode` function of `stdout_text` as default to ignore such failures.

@clebergnu @apahim @ldoktor what is your opinions? Thanks.

**Comment by ldoktor** [comment]
I don't think using `errors=ignore` should be the default. Anyway I do see the need for such option so how about introducing `CmdResult.get_stdout(errors=None)` which would be generic way to get stdout (stderr) with custom errors setting?

**Comment by ldoktor** [comment]
Also note that on python2 this raises exception, but hopefully with https://trello.com/c/wsd2z7WS/1265-unify-py3-py2-default-encoding-handling we should get better defaults and it should simply include the garbage characters...

**Comment by luckyh** [comment]
That sounds good! Let's wait for the new approach. Thanks.

**Comment by clebergnu** [comment]
`result.stdout` is already available, and user can call `result.stdout.decode()` with `encoding=` and `errors=`.
