### ISSUE TITLE
virt: revert snapshot: libvirtError: File exists

### ISSUE THREAD

**Issue by amoskong** [avocado-framework/avocado#2622]
* Version info
avocado 36.4
libvirt-3.7.0-4.fc27.x86_64
libvirt-client-3.7.0-4.fc27.x86_64
libvirt-daemon-3.7.0-4.fc27.x86_64

* Description
This problem isn't easy to be reproduced, the snapshot revert works well for most of time.
It seems the problem of libvirt, anyone touched this problem?

* Avocado Log:
```
2018-05-09 03:43:58,183 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/remote/runner.py:263
2018-05-09 03:43:58,186 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-05-09 03:43:58,186 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/remote/runner.py", line 318, in tear_down
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|     self.vm.restore_snapshot()
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/virt.py", line 252, in restore_snapshot
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|     self.revert_snapshot()
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/virt.py", line 238, in revert_snapshot
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|     self.domain.revertToSnapshot(self.snapshot)
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|   File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1982, in revertToSnapshot
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR|     if ret == -1: raise libvirtError ('virDomainRevertToSnapshot() failed', dom=self)
2018-05-09 03:43:58,187 stacktrace       L0042 ERROR| libvirtError: File exists
```

**Comment by ldoktor** [comment]
Hello @amoskong, I'm not a heavy user of this feature, but never had such issue. From our side the usage is pretty basic so it must be libvirt issue. Would you please try reaching upstream python-libvirt community and explain them the workflow? Not sure whether/how this plugin changed but simplified version of what we do in current release is:

```python
hyper = Hypervisor(hypervisor_uri)
hyper.connect()
domain = hyper.find_domain_by_name(domain_name)
domain.snapshotCreateXML(xml)
domain.revertToSnapshot(self.snapshot)
```

Closing it here as the exception comes from `libvirt.py` and not our code...
