### ISSUE TITLE
fail to install avocado on ubuntu 18.04

### ISSUE THREAD

**Issue by amoskong** [avocado-framework/avocado#2633]
Anyone tied to install avocado 36.04 on ubuntu 18.04?

```
root@ubuntu18:~# pip install  avocado-framework==36.4
Collecting avocado-framework==36.4
Installing collected packages: avocado-framework
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: avocado-framework==36.4 .dist-info directory not found
root@ubuntu18:~# ls /usr/local/lib/python2.7/dist-packages|grep avocado
avocado
avocado-36.4.dist-info

root@ubuntu18:~# pip install --force-reinstall  avocado-framework==36.4
Collecting avocado-framework==36.4
Installing collected packages: avocado-framework
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: avocado-framework==36.4 .dist-info directory not found
root@ubuntu18:~# pip uninstall avocado-framework
Cannot uninstall requirement avocado-framework, not installed
root@ubuntu18:~# pip uninstall avocado
Uninstalling avocado-36.4:
  /usr/local/lib/python2.7/dist-packages/avocado-36.4.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/avocado-36.4.dist-info/METADATA
....
```

**Comment by ldoktor** [comment]
It looks like the wheel 36.4 package installation is broken. You can install it from sources using `pip install --no-binary :all: avocado-framework==36.4` and @clebergnu can you please double-check it's on our side? Alternatively could you please remove the binary whl package for 32lts? 61 and 52 works well...

**Comment by amoskong** [comment]
Thanks, I had successfully install avocado 36.4 in ubuntu 18.04.

**Comment by ldoktor** [comment]
Glad to hear that. Btw 36 is unsupported (for a while) so you really should move to the next LTS which is 52.x. Anyway I added a card to solve this (best effort) so closing this issue.

**Comment by clebergnu** [comment]
@ldoktor there's no binary wheel package on 36lts:

https://pypi.org/project/avocado-framework/36.4/#files

**Comment by ldoktor** [comment]
Then do you have any ideas on how to solve this issue? (ps we can move the discussion to https://trello.com/c/pQrnVFSB/1336-bug-disable-binary-package-for-36x )

**Comment by amoskong** [comment]
Sure, I already tried 52.x
