### ISSUE TITLE
timeout of avocado.utils.process.run() doesn't work with `sudo`

### ISSUE THREAD

**Issue by amoskong** [avocado-framework/avocado#2693]
Problem: 
Root user can't kill sudo process, and there is no permission exception raised.

It should not a Avocado framework problem, and we can solve it by using sudo together, or remove all sudo.

* Test with normal user:
```
(normal user failed to kill sudo process)
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import process
>>> process.run('sudo sleep 10', timeout=1)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "avocado/utils/process.py", line 507, in send_signal
    self._popen.send_signal(sig)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1554, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 1] Operation not permitted

Command: sudo sleep 10
Exit status: 0
Duration: 10.0446128845
Stdout:

Stderr:

```

```
(python is executed by sudo, it succeeds to kill sudo process)
$ sudo python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import process
>>> process.run('sudo sleep 10', timeout=1)
Command: sudo sleep 10
Exit status: 0
Duration: 1.0067679882
Stdout:

Stderr:


>>> 
```

* Test with root user:
```
(root user can't kill sudo process, and no error raised)
[root@localhost muninn]# python
Python 2.7.5 (default, Apr 11 2018, 07:36:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import process
>>> process.run('sudo sleep 10', timeout=1)
Command: sudo sleep 10
Exit status: 0
Duration: 10.0067999363
Stdout:

Stderr:


>>> process.run('sleep 10', timeout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1031, in run
    raise CmdError(cmd, sp.result)
avocado.utils.process.CmdError: Command 'sleep 10' failed (rc=-15)
```

Related with: https://github.com/scylladb/scylla-artifact-tests/issues/103

**Comment by ldoktor** [comment]
Hello @amoskong, well this is a corner case introduced by user and could be handled by asynchronous execution and custom execution of `process.run("sudo kill %s" % pid)`. Still we could improve the `kill_process_tree` to support `sudo=True`.

What is worse is that we fail even on:

```python
>>> from avocado.utils import process
>>> process.run("sleep 10", timeout=1, sudo=True)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 1076, in run
    self.function(*self.args, **self.kwargs)
  File "avocado/utils/process.py", line 778, in timeout_handler
    self.send_signal(sig)
  File "avocado/utils/process.py", line 719, in send_signal
    self._popen.send_signal(sig)
  File "/usr/lib64/python2.7/subprocess.py", line 1269, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 1] Operation not permitted
```

and we should address that. One solution would be to attempt to use `sudo=True` when sending the signal to processes executed with `sudo=True`. Does it make sense?

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve timeout handling for "sudo=True" processes](https://trello.com/c/ROPWdFFr/1358-improve-timeout-handling-for-sudotrue-processes)

**Comment by amoskong** [comment]
It makes sense.

```
>>> process.run("sudo sleep 10", timeout=1, sudo=True)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 1084, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 507, in send_signal
    self._popen.send_signal(sig)
  File "/usr/lib64/python2.7/site-packages/subprocess32.py", line 1890, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 1] Operation not permitted

Command: /bin/sudo -n sudo sleep 10
Exit status: 0
Duration: 10.0204949379
Stdout:

Stderr:


>>> 
```

BTW, I solved(workaround) my original problem by executing cmd without 'sudo'.

**Comment by ldoktor** [comment]
Btw you don't (and should not) execute `"sudo sleep 10"`, but simply `"sleep 10", sudo=True` which actually executes `sudo -n sleep 10` (to avoid interaction). Also with https://trello.com/c/ROPWdFFr/1358-improve-timeout-handling-for-sudotrue-processes fixed it should allow forwarding signals even for `sudo=True`.

**Comment by amoskong** [comment]
Thanks.
