### ISSUE TITLE
unexpected keyword argument when pass '-h'

### ISSUE THREAD

**Issue by Blackrose** [avocado-framework/avocado#2759]
Hi All, I am newer on avocado. Now, I am wring a recipe to install avocado into yocto image.I had already build into my custom image.And I can got the version.Besides, other argument always shows me "unexpected keyword argument".
Below is version message
```
root@board:~# avocado -v
Avocado 63.0
```
Below is pass '-h ' argument
```
root@board:~# avocado -h
Avocado crashed unexpectedly: __init__() got an unexpected keyword argument 'on_load_failure_callback'
You can find details in /var/tmp/avocado-traceback-2018-08-12_10:20:56-uC35ZC.log
root@board:~# cat /var/tmp/avocado-traceback-2018-08-12_10:20:56-uC35ZC.log
Avocado crashed:
Traceback (most recent call last):
  File "/usr/bin/avocado", line 74, in <module>
    app = AvocadoApp()
  File "/usr/lib/python2.7/site-packages/avocado/core/app.py", line 54, in __init__
    self.parser.start()
  File "/usr/lib/python2.7/site-packages/avocado/core/parser.py", line 138, in start
    variants = varianter.Varianter(getattr(self.args, "varianter_debug", False))
  File "/usr/lib/python2.7/site-packages/avocado/core/varianter.py", line 185, in __init__
    self._variant_plugins = dispatcher.VarianterDispatcher()
  File "/usr/lib/python2.7/site-packages/avocado/core/dispatcher.py", line 232, in __init__
    super(VarianterDispatcher, self).__init__('avocado.plugins.varianter')
  File "/usr/lib/python2.7/site-packages/avocado/core/dispatcher.py", line 46, in __init__
    propagate_map_exceptions=True)
TypeError: __init__() got an unexpected keyword argument 'on_load_failure_callback'
```
Could you give me some hint?

**Comment by Blackrose** [comment]
I change version 63 to 62.It's work on my board.And I had another problem, I use remote runner argument to execute an test on board.The avocado of PC shows "Avocado job failed: JobError: Remote machine does not seem to have avocado installed".But I definitely sure the avocado is install on board.

**Comment by clebergnu** [comment]
@Blackrose is this by any change the same issue that was reported on the mailing list? Either way, are you still facing the same issue? If so, would you care to detail how Avocado was installed on the remote machine (the development board system IUUC)? Thanks

**Comment by Blackrose** [comment]
I had resolved this issue.The remote machine need use bash as default. Though my board use sh from busybox. When I change shell from sh to bash, this error has gone. I saw the pass sign on test.
