### ISSUE TITLE
assertRaises() doesn't seem to work properly

### ISSUE THREAD

**Issue by rbeims** [avocado-framework/avocado#2791]
I have some tests written for python unittests, and I would like to use them in avocado, together with avocado parameters.
The avocado documentation states that its main class derives from unittests, so I replaced the unittests superclass with avocado.Test in one of my files. 
Now when running the test in avocado, the test errors out because of an exception, but this exception is raised specifically for determining the success of the test with assertRaises().

Can someone think of any reason why the assertRaises should not work when using the avocado class?

```self.assertRaises(Exception, self.send_and_receive, "list_users", [])```

output from the test:
```2018-08-22 13:50:21,686 test ERROR| Traceback (most recent call last):
2018-08-22 13:50:21,686 test  ERROR|   File "/usr/lib/python3.7/site-packages/avocado/core/test.py", line 922, in _run_avocado
    raise test_exception
2018-08-22 13:50:21,686 test  ERROR|   File "/usr/lib/python3.7/site-packages/avocado/core/test.py", line 826, in _run_avocado
    testMethod()
2018-08-22 13:50:21,686 test  ERROR|   File "websockets.py", line 134, in test_user_handling
    reply = self.send_and_receive("list_users", [])
2018-08-22 13:50:21,686 test  ERROR|   File "websockets.py", line 68, in send_and_receive
    return self.read_reply()
2018-08-22 13:50:21,686 test  ERROR|   File "websockets.py", line 60, in read_reply
    raise Exception()
2018-08-22 13:50:21,686 test  ERROR| websockets.Exception
2018-08-22 13:50:21,686 test  ERROR| ERROR 4-websockets.py:TestWebsocketInterface.test_user_handling -> Exception:
```

Shouldn't I expect a pass in this case, instead of an error?

**Comment by clebergnu** [comment]
In my first quick analysis, I believe you're absolutely right, and that should result in a PASS.  Let me take a look at where the possible issue is, and how hard it's to come up with a fix.

**Comment by clebergnu** [comment]
@rbeims do you mind trying out this reproducer code:

```
from avocado import Test


class MyException(Exception):
    pass


def raises_exception():
    raise MyException


class Assert(Test):

    def test_assert_raises(self):
        with self.assertRaises(MyException):
            raises_exception()

    def test_fails_to_raise(self):
        with self.assertRaises(MyException):
            pass
```

The expected result is something like:

```
$ avocado run examples/tests/assert.py 
JOB ID     : 758ba8cda3a96f19f37ea5157108f2610f63bd32
JOB LOG    : /home/cleber/avocado/job-results/job-2019-01-24T18.54-758ba8c/job.log
 (1/2) examples/tests/assert.py:Assert.test_assert_raises: PASS (0.02 s)
 (2/2) examples/tests/assert.py:Assert.test_fails_to_raise: FAIL: MyException not raised (0.06 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.28 s
JOB HTML   : /home/cleber/avocado/job-results/job-2019-01-24T18.54-758ba8c/results.html
```

**Comment by clebergnu** [comment]
@rbeims actually, you can just test #3007.

**Comment by clebergnu** [comment]
Closing based on #3007
