### ISSUE TITLE
kernel: TypeError in calling KernelBuild.download

### ISSUE THREAD

**Issue by lolyu** [avocado-framework/avocado#2873]
```shell
>>> from avocado.utils import kernel
>>> kernel.KernelBuild('4.4.133')
KernelBuild('4.4.133, None, /tmp/avocado_avocado.utils.kernel69PdJQ')
>>> k = kernel.KernelBuild('4.4.133')
>>> k.download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/avocado/utils/kernel.py", line 79, in download
    full_url = base_url + kernel_file
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
By reading into `avocado.utils.kernel.KernelBuild.download`:
```python
    def download(self, url=None):
        """
        Download kernel source.
 
        :param url: override the url from where to fetch the kernel
                    source tarball
        :type url: str or None
        """
        kernel_file = self.SOURCE.format(version=self.version)
        if url is not None:
            base_url = self.URL.format(major=self.version.split('.', 1)[0])
        else:
            base_url = url
        full_url = base_url + kernel_file
 
        self.asset_path = asset.Asset(full_url, asset_hash=None,
                                      algorithm=None, locations=None,
```
if `url` is `None`, `base_url` should be assigned to the default one instead of `url`.

**Comment by cacarrara** [comment]
Fix ##2893
