### ISSUE TITLE
traceback caused by running avocado via ssh with set LC_ALL=C

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2907]
see PR in cockpit project: 
https://github.com/cockpit-project/cockpit/pull/10544
there is command like ``env LC_ALL=C ssh avocado run /tmp/avocadotest.py`` causing this trouble.
But this trouble is not relevant just to ``process`` lib I've met it also with scheduler, that function inside avocado ``runner`` like ``_get_tests...`` failed with same error

```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:831
Traceback (most recent call last):
  File "/tmp/avocado_tests/checklogin-basic.py", line 48, in testLogin
    c.run_shell_command(setup_cmd, cleanup_cmd)
  File "/tmp/avocado_tests/cockpit.py", line 40, in run_shell_command
    process.run(cmd, shell=True)
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1320, in run
    klass = get_sub_process_klass(cmd)
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1257, in get_sub_process_klass
    elif should_run_inside_wrapper(cmd):
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1231, in should_run_inside_wrapper
    args = cmd_split(cmd)
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 286, in cmd_split
    data = cmd.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
```

**Comment by clebergnu** [comment]
@jscotka if you know the encoding of the command you're running (and it's not the Python's default encoding), you should give `run()` that encoding as the argument.  Please check the input you give to `run()`, and the result of `locale.getpreferredencoding()`.

**Comment by ldoktor** [comment]
Exactly. You are running this:

```python
     def testLogin(self):
         c = cockpit.Cockpit()
         b = c.browser
 
         # Setup users and passwords
         setup_cmd = "useradd %s -s /bin/bash -c 'Barney Bär'; echo %s:abcdefg | chpasswd" % (
             username, username)
         cleanup_cmd = "userdel -r %s" % username
c.run_shell_command(setup_cmd, cleanup_cmd)
```

therefor you are trying to execute non-ascii characters using system encoding (which is ascii), therefor it's bound to fail. Please specify the encoding you use in your code (should be utf-8 on py3) and in order to work properly I'd suggest to use `LC_ALL=C.utf8` as well.

**Comment by jscotka** [comment]
Ah, thanks. I've missed  it and trouble were, that from some reason it worked well inside older avocado version, and there were same code invocation via LC_ALL=C, so it was strange that it stops working

**Comment by ldoktor** [comment]
Yes, older Avocado was py2 and was pretty lenient in terms of encoding. In order to support py3 we had to explicitly encode/decode all the places where strings/unicodes/bytes are combined, which also requires all the tests/libs to do the same. Anyway we did our best to provide better default (system encoding) than python (ascii or utf8) so in your case, as you are using utf8 chars, I'd simply use `LC_ALL=C.utf8` which avocado detects and uses).

**Comment by ldoktor** [comment]
Note you can use `proc.stdout_text` and instead of explicit decoding you could use `astring.to_text` from the `avocado.utils.astring` library (along with other useful string handling methods there).

Anyway as mentioned earlier, no changes would be probably necessary if you simply used the proper system encoding (`LC_ALL=C.utf8`) as you are in fact using those wide characters.

All in all, py3 support is not for free, it is more pedantic in string handling and we all need to adjust our code to cope with that. We learned to be lazy, now we suffer the consequences...

**Comment by jscotka** [comment]
@ldoktor sure :-) thanks for debugging this issue
