### ISSUE TITLE
avocado 67.0 package fails to build for Fedora 30 due to selftest issue

### ISSUE THREAD

**Issue by mmathesius** [avocado-framework/avocado#2978]
Upon checkout of avocado 67.0, running `make MOCK_CONFIG=fedora-30-x86_64 rpm-release` fails with:
```
======================================================================
ERROR: test_run_unicode_output (selftests.unit.test_utils_process.TestProcessRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-67.0/selftests/unit/test_utils_process.py", line 320, in test_run_unicode_output                                                 
    result = process.run(cmd, encoding='utf-8')
  File "/builddir/build/BUILD/avocado-67.0/avocado/utils/process.py", line 1355, in run                                                                                
    cmd_result = sp.run(timeout=timeout)
  File "/builddir/build/BUILD/avocado-67.0/avocado/utils/process.py", line 875, in run                                                                                 
    self._init_subprocess()
  File "/builddir/build/BUILD/avocado-67.0/avocado/utils/process.py", line 640, in _init_subprocess                                                                    
    env=self.env)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__                                                                                                     
    errread, errwrite)                                                                                                                                                 
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child                                                                                              
    raise child_exception
TypeError: execv() arg 2 must contain only strings

----------------------------------------------------------------------
```

Builds using MOCK_CONFIG of fedora-28-x86_64, fedora-29-x86_64, and epel-7-x86_64 all succeed.

I suspect this has something to do with the encoding of the command string passed to `process.run()`, but I can't quite put my finger on it...

**Comment by clebergnu** [comment]
@mmathesius can you please test if the fix on #3013 works for you? Thanks for reporting it.

**Comment by clebergnu** [comment]
I was suspecting Fedora 30 requires specific locales to be installed because of this message:

```
+ /usr/bin/python2 selftests/run
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```
And it turned to to be the case.

**Comment by mmathesius** [comment]
@clebergnu As noted in https://github.com/avocado-framework/avocado/pull/3013#issuecomment-459149797, I tested that fix and it works. Thanks!
