### ISSUE TITLE
utils.vmimage.get: UnicodeDecodeError

### ISSUE THREAD

**Issue by lolyu** [avocado-framework/avocado#3020]
```shell
>>> from avocado.utils import vmimage
>>> vmimage.get('centos')
<Image name=CentOS version=7 arch=x86_64>
>>> vmimage.get('centos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lolyu/repo/avocado/avocado/utils/vmimage.py", line 427, in get
    snapshot_dir=snapshot_dir)
  File "/home/lolyu/repo/avocado/avocado/utils/vmimage.py", line 327, in __init__
    self.get()
  File "/home/lolyu/repo/avocado/avocado/utils/vmimage.py", line 352, in get
    asset_path = archive.extract_lzma(asset_path)
  File "/home/lolyu/repo/avocado/avocado/utils/archive.py", line 123, in extract_lzma
    newfile_obj.write(lzma.decompress(file_obj.read()))
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```

**Comment by lolyu** [comment]
It is caused by `avocado.utils.archive.extract_lzma` opens compressed file in text mode.

**Comment by lolyu** [comment]
#3019
