### ISSUE TITLE
Bad FDDrainer descriptor during process stdout logging

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#3208]
In same cases the process module will fail to complete its stdout logging:

```
08:14:05 INFO | Running 'vgdisplay c22_vm4_ramdisk'
08:14:05 DEBUG| [stdout]   --- Volume group ---
08:14:05 DEBUG| [stdout]   VG Name               c22_vm4_ramdisk
08:14:05 DEBUG| [stdout]   System ID             
08:14:05 DEBUG| [stdout]   Format                lvm2
08:14:05 DEBUG| [stdout]   Metadata Areas        1
08:14:05 DEBUG| [stdout]   Metadata Sequence No  10
08:14:05 DEBUG| [stdout]   VG Access             read/write
08:14:05 DEBUG| [stdout]   VG Status             resizable
08:14:05 DEBUG| [stdout]   MAX LV                0
08:14:05 DEBUG| [stdout]   Cur LV                4
08:14:05 DEBUG| [stderr] Exception in thread b'vgdisplay c22_vm4_ramdisk'-stdout:

08:14:05 DEBUG| [stderr] Traceback (most recent call last):

08:14:05 DEBUG| [stderr]   File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner

08:14:05 DEBUG| [stderr]     self.run()

08:14:05 DEBUG| [stderr]   File "/usr/lib64/python3.7/threading.py", line 865, in run

08:14:05 DEBUG| [stderr]     self._target(*self._args, **self._kwargs)

08:14:05 DEBUG| [stderr]   File "/usr/lib/python3.7/site-packages/avocado/utils/process.py", line 439, in _drainer

08:14:05 DEBUG| [stderr]     tmp = os.read(self.fd, 8192)

08:14:05 DEBUG| [stderr] OSError: [Errno 9] Bad file descriptor

08:14:05 DEBUG| [stderr] 

08:14:05 INFO | Command 'vgdisplay c22_vm4_ramdisk' finished with -13 after 0.052590131759643555s
08:14:05 ERROR| Command 'vgdisplay c22_vm4_ramdisk' failed.
```

In such cases the command has not finished yet as well as reading its stdout and it could be that some external factor is closing the file descriptor.

**Comment by lolyu** [comment]
Hi, could you please provide more details related to this issue, like the script name, Python version, and the reproduction rate? I ran into a similar problem like this only in Python2.

**Comment by pevogam** [comment]
Hi @lolyu, I get this with python3. Regarding a script name, this originates from running the lv utils provided within avocado before and after the vm env processing (and thus a test).

**Comment by pevogam** [comment]
I would close this as we have moved away from using LVM for vm state management and have not experienced such errors ever since + can no longer verify whether it could be potentially fixed or not + a lot of avocado releases have happened ever since. If anyone encounters something like this again, they will likely be able to also provide more recent fresh data that will be more useful to debugging anyway.
