### ISSUE TITLE
avocado crashes with: AttributeError: 'str' object has no attribute 'str_filesystem'

### ISSUE THREAD

**Issue by msehnout** [avocado-framework/avocado#3250]
I'm trying to run a very simple test, but I get this error:

terminal output:
```
$ avocado run --output-check-record both test/test_avocado.py
JOB ID     : 837fe52dc3e42cc0e6b88025976b5ae84a407ec3
JOB LOG    : /home/msehnout/avocado/job-results/job-2019-08-08T14.40-837fe52/job.log

Avocado crashed: TestError: Process died before it pushed early test_status.
Traceback (most recent call last):

  File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/job.py", line 530, in run_tests
    execution_order)

  File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/runner.py", line 630, in run_suite
    deadline):

  File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/runner.py", line 405, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/runner.py", line 153, in wait_for_early_status
    raise exceptions.TestError("Process died before it pushed "

avocado.core.exceptions.TestError: Process died before it pushed early test_status.

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

job.log:
```
$ cat /home/msehnout/avocado/job-results/latest/job.log
2019-08-08 14:40:34,643 extension        L0189 DEBUG| found extension EntryPoint.parse('human = avocado.plugins.human:HumanJob')
2019-08-08 14:40:34,644 extension        L0189 DEBUG| found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
2019-08-08 14:40:34,644 extension        L0189 DEBUG| found extension EntryPoint.parse('teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir')
2019-08-08 14:40:34,648 sysinfo          L0405 DEBUG| File /etc/avocado/sysinfo/commands does not exist.
2019-08-08 14:40:34,648 sysinfo          L0416 DEBUG| File /etc/avocado/sysinfo/files does not exist.
2019-08-08 14:40:34,648 sysinfo          L0444 DEBUG| File /etc/avocado/sysinfo/profilers does not exist.
2019-08-08 14:40:34,649 sysinfo          L0502 INFO | System log file not found (looked for ['/var/log/messages', '/var/log/syslog', '/var/log/system.log'])
2019-08-08 14:40:34,659 job              L0382 INFO | Command line: /home/msehnout/.local/bin/avocado run --output-check-record both test/test_avocado.py
2019-08-08 14:40:34,659 job              L0383 INFO |
2019-08-08 14:40:34,659 job              L0417 INFO | Avocado version: 70.0
2019-08-08 14:40:34,659 job              L0418 INFO |
2019-08-08 14:40:34,659 job              L0422 INFO | Config files read (in order):
2019-08-08 14:40:34,659 job              L0424 INFO | /home/msehnout/.local/lib/python3.7/site-packages/avocado/etc/avocado/avocado.conf
2019-08-08 14:40:34,659 job              L0424 INFO | /home/msehnout/.local/lib/python3.7/site-packages/avocado/etc/avocado/conf.d/result_upload.conf
2019-08-08 14:40:34,659 job              L0424 INFO | /home/msehnout/.local/lib/python3.7/site-packages/avocado/etc/avocado/conf.d/resultsdb.conf
2019-08-08 14:40:34,659 job              L0424 INFO | /home/msehnout/.local/lib/python3.7/site-packages/avocado/etc/avocado/conf.d/jobscripts.conf
2019-08-08 14:40:34,659 job              L0424 INFO | /home/msehnout/.local/lib/python3.7/site-packages/avocado/etc/avocado/conf.d/gdb.conf
2019-08-08 14:40:34,659 job              L0424 INFO | /home/msehnout/.config/avocado/avocado.conf
2019-08-08 14:40:34,659 job              L0425 INFO |
2019-08-08 14:40:34,659 job              L0427 INFO | Avocado config:
2019-08-08 14:40:34,660 job              L0436 INFO | Section.Key                              Value
2019-08-08 14:40:34,660 job              L0436 INFO | datadir.paths.base_dir                   /var/lib/avocado
2019-08-08 14:40:34,660 job              L0436 INFO | datadir.paths.test_dir                   /usr/share/doc/avocado/tests
2019-08-08 14:40:34,660 job              L0436 INFO | datadir.paths.data_dir                   /var/lib/avocado/data
2019-08-08 14:40:34,660 job              L0436 INFO | datadir.paths.logs_dir                   ~/avocado/job-results
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collect.enabled                  True
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collect.commands_timeout         -1
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collect.installed_packages       False
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collect.profiler                 False
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collect.locale                   C
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collect.per_test                 False
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collectibles.commands            /etc/avocado/sysinfo/commands
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collectibles.files               /etc/avocado/sysinfo/files
2019-08-08 14:40:34,660 job              L0436 INFO | sysinfo.collectibles.profilers           /etc/avocado/sysinfo/profilers
2019-08-08 14:40:34,660 job              L0436 INFO | runner.output.colored                    True
2019-08-08 14:40:34,660 job              L0436 INFO | runner.output.utf8
2019-08-08 14:40:34,660 job              L0436 INFO | runner.timeout.after_interrupted         60
2019-08-08 14:40:34,660 job              L0436 INFO | runner.timeout.process_died              10
2019-08-08 14:40:34,660 job              L0436 INFO | runner.timeout.process_alive             60
2019-08-08 14:40:34,661 job              L0436 INFO | remoter.behavior.reject_unknown_hosts    False
2019-08-08 14:40:34,661 job              L0436 INFO | remoter.behavior.disable_known_hosts     False
2019-08-08 14:40:34,661 job              L0436 INFO | job.output.loglevel                      debug
2019-08-08 14:40:34,661 job              L0436 INFO | restclient.connection.hostname           localhost
2019-08-08 14:40:34,661 job              L0436 INFO | restclient.connection.port               9405
2019-08-08 14:40:34,661 job              L0436 INFO | restclient.connection.username
2019-08-08 14:40:34,661 job              L0436 INFO | restclient.connection.password
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.disable                          []
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.skip_broken_plugin_notification  []
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.loaders                          ['file', '@DEFAULT']
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.jobscripts.pre                   /etc/avocado/scripts/job/pre.d/
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.jobscripts.post                  /etc/avocado/scripts/job/post.d/
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.jobscripts.warn_non_existing_dir False
2019-08-08 14:40:34,661 job              L0436 INFO | plugins.jobscripts.warn_non_zero_status  True
2019-08-08 14:40:34,661 job              L0436 INFO | gdb.paths.gdb                            /usr/bin/gdb
2019-08-08 14:40:34,661 job              L0436 INFO | gdb.paths.gdbserver                      /usr/bin/gdbserver
2019-08-08 14:40:34,661 job              L0437 INFO |
2019-08-08 14:40:34,661 job              L0440 INFO | Avocado Data Directories:
2019-08-08 14:40:34,661 job              L0441 INFO |
2019-08-08 14:40:34,662 job              L0442 INFO | base     /home/msehnout/avocado
2019-08-08 14:40:34,662 job              L0443 INFO | tests    /home/msehnout/avocado/tests
2019-08-08 14:40:34,662 job              L0444 INFO | data     /home/msehnout/avocado/data
2019-08-08 14:40:34,662 job              L0445 INFO | logs     /home/msehnout/avocado/job-results/job-2019-08-08T14.40-837fe52
2019-08-08 14:40:34,662 job              L0446 INFO |
2019-08-08 14:40:34,662 job              L0452 INFO | No variants available, using defaults only
2019-08-08 14:40:34,662 job              L0452 INFO |
2019-08-08 14:40:34,662 job              L0452 INFO | Variant :    /
2019-08-08 14:40:34,662 job              L0455 INFO | Temporary dir: /var/tmp/avocado_omxse14m/avocado_job_lqhgqjau
2019-08-08 14:40:34,662 job              L0456 INFO |
2019-08-08 14:40:34,662 job              L0374 INFO | Job ID: 837fe52dc3e42cc0e6b88025976b5ae84a407ec3
2019-08-08 14:40:34,662 job              L0377 INFO |
2019-08-08 14:40:34,684 output           L0631 DEBUG| [stderr] Process Process-1:

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr] Traceback (most recent call last):

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]   File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]     self.run()

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]   File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]     self._target(*self._args, **self._kwargs)

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]   File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/runner.py", line 326, in _run_test

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]     instance = loader.load_test(test_factory)

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]   File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/loader.py", line 412, in load_test

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]     test_instance = test_class(**test_parameters)

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]   File "/home/msehnout/.local/lib/python3.7/site-packages/avocado/core/test.py", line 358, in __init__

2019-08-08 14:40:34,686 output           L0631 DEBUG| [stderr]     logdir = os.path.join(base_logdir, self.name.str_filesystem)

2019-08-08 14:40:34,687 output           L0631 DEBUG| [stderr] AttributeError: 'str' object has no attribute 'str_filesystem'

2019-08-08 14:40:34,694 extension        L0189 DEBUG| found extension EntryPoint.parse('json = avocado.plugins.jsonresult:JSONResult')
2019-08-08 14:40:34,695 extension        L0189 DEBUG| found extension EntryPoint.parse('xunit = avocado.plugins.xunit:XUnitResult')
2019-08-08 14:40:34,695 extension        L0189 DEBUG| found extension EntryPoint.parse('zip_archive = avocado.plugins.archive:Archive')
```
Code that triggers the issue:
https://github.com/msehnout/osbuild/tree/avocado-issue

I used `pip3 install --user` method to install Avocado and I'm running Fedora 30.

**Comment by clebergnu** [comment]
Hi,

The problem seems to be with the class attribute `name`.  Avocado's INSTRUMENTED tests expect the `name` attribute to be an instance of `avocado.core.test.TestID`.

If you're looking for a way to classify the tests, maybe using `:avocado: tags=timezone` would work for you.

**Comment by msehnout** [comment]
Thanks! Removing the name attribute fixed the problem.
