### ISSUE TITLE
"make check" never finishes

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado#3253]
No time to debug right now, but I can not really run `make check` any more as it always hangs. Attached the output of `make check | tee log.txt` that I let running for 15m, then I had to kill it with `ctrl+c`. There were still some python processes behind (removed some non-avocado processes):

```
ps ax | grep python3
 5244 pts/13   S+     0:00 grep --color=auto python3
26563 pts/12   S+     0:04 /usr/bin/python3 -m avocado nrun selftests/inspekt-indent.sh selftests/inspekt-lint.sh selftests/inspekt-style.sh selftests/modules-boundaries.sh selftests/signedoff-check.sh selftests/unit/ selftests/functional/ optional_plugins/golang/tests/ optional_plugins/html/tests/ optional_plugins/loader_yaml/tests/ optional_plugins/robot/tests/ optional_plugins/runner_remote/tests/ optional_plugins/runner_vm/tests/ optional_plugins/varianter_cit/tests/ optional_plugins/varianter_yaml_to_mux/tests/
28030 pts/12   S+     0:02 /usr/bin/python3 -m avocado.core.nrunner task-run -i 489-test_basic.RunnerSimpleTest.test_kill_stopped_sleep -k python-unittest -u selftests.functional.test_basic.RunnerSimpleTest.test_kill_stopped_sleep -s 127.0.0.1:8888
28079 pts/12   R+     8:09 /usr/bin/python3 -m avocado.core.nrunner task-run -i 489-test_basic.RunnerSimpleTest.test_kill_stopped_sleep -k python-unittest -u selftests.functional.test_basic.RunnerSimpleTest.test_kill_stopped_sleep -s 127.0.0.1:8888
```

[log.txt](https://github.com/avocado-framework/avocado/files/3493022/log.txt)

I'm wondering whether it's just me or everybody. At this point I don't have much time to debug...

**Comment by ldoktor** [comment]
Also let me attach the output after ctrl+c

```
b"************* Module selftests.unit.test_utils_network\nI1101: 44,21: get_all_local_addrs: Module 'netifaces' has no 'interfaces' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.\nI1101: 45,22: get_all_local_addrs: Module 'netifaces' has no 'ifaddresses' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.\nI1101: 47,48: get_all_local_addrs: Module 'netifaces' has no 'AF_INET' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.\nI1101: 49,48: get_all_local_addrs: Module 'netifaces' has no 'AF_INET6' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.\n************* Module passtest\nW0107: 19,8: PassTest.test: Unnecessary pass statement\n"
^CTraceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/medic/Work/Projekty/avocado/avocado/avocado/__main__.py", line 11, in <module>
    sys.exit(main.run())
  File "/home/medic/Work/Projekty/avocado/avocado/avocado/core/app.py", line 91, in run
    return method(self.parser.config)
  File "/home/medic/Work/Projekty/avocado/avocado/avocado/plugins/nrun.py", line 167, in run
    loop.run_until_complete(self.status_server.wait())
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1735, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
make: *** [Makefile:135: check] Chyba 120
```

and I forgot to mention I have some Avocado variables set:

```
AVOCADO_PARALLEL_CHECK=yes
AVOCADO_LOG_DEBUG=yes
AVOCADO_CHECK_LEVEL=99
```

**Comment by clebergnu** [comment]
Hi @ldoktor I've tested with the same environment variables, and couldn't reproduce, I got:

```
$ env | grep AVOCADO
AVOCADO_PARALLEL_CHECK=yes
AVOCADO_LOG_DEBUG=yes
AVOCADO_CHECK_LEVEL=99

$ make check
...
Status server: exiting due to all tasks finished
{'pass': 719, 'skip': 16}
```

A heads up is that the nrunner is so far quite limited wrt how it finishes its execution -- basically it waits for all runners to report back, there's no timeout or babysitting of the test runners.  So, it may be that one file in your dir may be interpreted as a test that is somehow crashing one of the runner execution.

**Comment by ldoktor** [comment]
Currently it's passing on my machine as well, but previously (as you can see in the "ps ax" output) some of the tests did not finish (and there were serveral failures). So let's close it as it was probably caused by overloaded system, but I don't like it much...

Btw it'd be nice to list the names of tests that failed after the execution, currently I always spend a lot of time searching for the failures...

**Comment by ldoktor** [comment]
... and color output would be also welcome :D
