### ISSUE TITLE
Fix selftests.functional.test_nrunner.TaskRun.test_recipe_exec_3 on s390x / ppc64le

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3492]
This is about a failure that has happened on Travis on s390x:

https://travis-ci.org/avocado-framework/avocado/jobs/635296475#L1426

```
======================================================================
FAIL: test_recipe_exec_3 (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/avocado-framework/avocado/selftests/functional/test_nrunner.py", line 152, in test_recipe_exec_3
    self.assertGreater(len(lines), 1)
AssertionError: 1 not greater than 1
----------------------------------------------------------------------
Ran 1 test in 1.537s
```

**Comment by clebergnu** [comment]
It looks like on s390x (maybe on other platforms?) it's possible for a task such as:

```
{"id": 3, "runnable": {"kind": "exec", "uri": "/bin/sleep", "args": ["0.01"]}}
```

To be executed and complete before the:

```python
#: The amount of time (in seconds) between each internal status check
RUNNER_RUN_CHECK_INTERVAL = 0.01
```

Because the code that produces a ```{'status': 'running'...``` may never be executed (and this is expected) and only the ```{'status': 'finished'...``` one may be returned.

**Comment by willianrampazzo** [comment]
I confirm the bug:

```
======================================================================
FAIL: test_recipe_exec_3 (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 152, in test_recipe_exec_3
    self.assertGreater(len(lines), 1)
AssertionError: 0 not greater than 1

----------------------------------------------------------------------
Ran 1 test in 0.306s
```

**Comment by willianrampazzo** [comment]
In my machine, one unusual behavior is that when this specific test fails, other tests also fail, and one of them tries to execute outside of the venv, which does not happen when all tests succeed.

```
(python3) [linux1@avocado avocado]$ avocado nrun selftests/functional/test_nrunner.py
Results server started at: 127.0.0.1:8888
4-selftests.functional.test_nrunner.RunnableRun.test_recipe spawned
5-selftests.functional.test_nrunner.RunnableRun.test_noop_valid_kwargs spawned
8-selftests.functional.test_nrunner.TaskRun.test_noop spawned
Task complete (fail): 5-selftests.functional.test_nrunner.RunnableRun.test_noop_valid_kwargs
Task 5-selftests.functional.test_nrunner.RunnableRun.test_noop_valid_kwargs output:
======================================================================
FAIL: test_noop_valid_kwargs (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 72, in test_noop_valid_kwargs
    self.assertEqual(res.exit_status, exit_codes.AVOCADO_ALL_OK)
AssertionError: 255 != 0

----------------------------------------------------------------------
Ran 1 test in 0.394s

FAILED (failures=1)


Task complete (fail): 8-selftests.functional.test_nrunner.TaskRun.test_noop
Task 8-selftests.functional.test_nrunner.TaskRun.test_noop output:
======================================================================
FAIL: test_noop (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 96, in test_noop
    self.assertIn(b"'status': 'finished'", res.stdout)
AssertionError: b"'status': 'finished'" not found in b''

----------------------------------------------------------------------
Ran 1 test in 0.417s

FAILED (failures=1)


Task complete (error): 4-selftests.functional.test_nrunner.RunnableRun.test_recipe
Task 4-selftests.functional.test_nrunner.RunnableRun.test_recipe output:
======================================================================
ERROR: test_recipe (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 60, in test_recipe
    first_status = lines[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.445s

FAILED (errors=1)


6-selftests.functional.test_nrunner.RunnableRun.test_noop_invalid_kwargs spawned
9-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_1 spawned
10-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_2 spawned
Task complete (error): 9-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_1
Task 9-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_1 output:
======================================================================
ERROR: test_recipe_exec_1 (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 112, in test_recipe_exec_1
    first_status = lines[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.278s

FAILED (errors=1)


3-selftests.functional.test_nrunner.RunnableRun.test_exec_echo spawned
Task complete (fail): 6-selftests.functional.test_nrunner.RunnableRun.test_noop_invalid_kwargs
Task 6-selftests.functional.test_nrunner.RunnableRun.test_noop_invalid_kwargs output:
======================================================================
FAIL: test_noop_invalid_kwargs (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 77, in test_noop_invalid_kwargs
    self.assertIn(b'Invalid keyword parameter: "foo"', res.stderr)
AssertionError: b'Invalid keyword parameter: "foo"' not found in b"Avocado crashed unexpectedly: The 'bcrypt>=3.1.3' distribution was not found and is required by paramiko\nYou can find details in /home/linux1/venv/python3/data/crashes/avocado-traceback-2020-01-10_14:12:14-58eyuvlq.log\n"

----------------------------------------------------------------------
Ran 1 test in 0.397s

FAILED (failures=1)


11-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_3 spawned
Task complete (error): 10-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_2
Task 10-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_2 output:
======================================================================
ERROR: test_recipe_exec_2 (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 132, in test_recipe_exec_2
    first_status = lines[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.474s

FAILED (errors=1)


1-selftests.functional.test_nrunner.RunnableRun.test_noop spawned
Task complete (fail): 3-selftests.functional.test_nrunner.RunnableRun.test_exec_echo
Task 3-selftests.functional.test_nrunner.RunnableRun.test_exec_echo output:
======================================================================
FAIL: test_exec_echo (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 40, in test_exec_echo
    self.assertIn(b"'status': 'finished'", res.stdout)
AssertionError: b"'status': 'finished'" not found in b''

----------------------------------------------------------------------
Ran 1 test in 0.481s

FAILED (failures=1)


Task complete (fail): 11-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_3
Task 11-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_3 output:
======================================================================
FAIL: test_recipe_exec_3 (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 153, in test_recipe_exec_3
    self.assertGreater(len(lines), 1)
AssertionError: 0 not greater than 1

----------------------------------------------------------------------
Ran 1 test in 0.303s

FAILED (failures=1)


2-selftests.functional.test_nrunner.RunnableRun.test_exec spawned
12-selftests.functional.test_nrunner.ResolveSerializeRun.test spawned
Task complete (fail): 1-selftests.functional.test_nrunner.RunnableRun.test_noop
Task 1-selftests.functional.test_nrunner.RunnableRun.test_noop output:
======================================================================
FAIL: test_noop (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 17, in test_noop
    self.assertIn(b"'status': 'finished'", res.stdout)
AssertionError: b"'status': 'finished'" not found in b''

----------------------------------------------------------------------
Ran 1 test in 0.476s

FAILED (failures=1)


7-selftests.functional.test_nrunner.RunnableRun.test_exec_kwargs spawned
Task complete (error): 12-selftests.functional.test_nrunner.ResolveSerializeRun.test
Task 12-selftests.functional.test_nrunner.ResolveSerializeRun.test output:
======================================================================
ERROR: test (selftests.functional.test_nrunner.ResolveSerializeRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 173, in test
    res = process.run(cmd)
  File "/home/linux1/src/avocado/avocado/utils/process.py", line 1039, in run
    raise CmdError(cmd, sp.result)
avocado.utils.process.CmdError: Command '/usr/bin/python3 ./scripts/avocado nlist --write-recipes-to-directory=/var/tmp/avocado__selftests.functional.test_nrunner__ResolveSerializeRun__setUp__od90chkv -- /bin/true' failed.
stdout: b''
stderr: b"Avocado crashed unexpectedly: The 'bcrypt>=3.1.3' distribution was not found and is required by paramiko\nYou can find details in /home/linux1/venv/python3/data/crashes/avocado-traceback-2020-01-10_14:12:15-eveefune.log\n"
additional_info: None

----------------------------------------------------------------------
Ran 1 test in 0.309s

FAILED (errors=1)


Finished spawning tasks
Task complete (fail): 2-selftests.functional.test_nrunner.RunnableRun.test_exec
Task 2-selftests.functional.test_nrunner.RunnableRun.test_exec output:
======================================================================
FAIL: test_exec (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 28, in test_exec
    self.assertIn(b"'status': 'finished'", res.stdout)
AssertionError: b"'status': 'finished'" not found in b''

----------------------------------------------------------------------
Ran 1 test in 0.258s

FAILED (failures=1)


Task complete (fail): 7-selftests.functional.test_nrunner.RunnableRun.test_exec_kwargs
Task 7-selftests.functional.test_nrunner.RunnableRun.test_exec_kwargs output:
======================================================================
FAIL: test_exec_kwargs (selftests.functional.test_nrunner.RunnableRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linux1/src/avocado/selftests/functional/test_nrunner.py", line 86, in test_exec_kwargs
    self.assertIn(b"'status': 'finished'", res.stdout)
AssertionError: b"'status': 'finished'" not found in b''

----------------------------------------------------------------------
Ran 1 test in 0.258s

FAILED (failures=1)


Status server: exiting due to all tasks finished
{'fail': 8, 'error': 4}
(python3) [linux1@avocado avocado]$
```

**Comment by willianrampazzo** [comment]
After installing all the avocado package dependencies on the system, and do not use a venv, I cannot reproduce the bug anymore.

Maybe the CI had a package installation fail during the setup, and the side effect was this bug. I am just guessing here.

**Comment by clebergnu** [comment]
Also happened on `ppc64le`:

https://travis-ci.org/avocado-framework/avocado/jobs/641464678?utm_medium=notification&utm_source=github_status

```
Task 655-selftests.functional.test_nrunner.TaskRun.test_recipe_exec_3 output:
======================================================================
FAIL: test_recipe_exec_3 (selftests.functional.test_nrunner.TaskRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/avocado-framework/avocado/selftests/functional/test_nrunner.py", line 152, in test_recipe_exec_3
    self.assertGreater(len(lines), 1)
AssertionError: 1 not greater than 1
----------------------------------------------------------------------
Ran 1 test in 4.865s
FAILED (failures=1)
```

**Comment by clebergnu** [comment]
I've stress tested this specific test on both a 390x and aarch64 (not on an ppc64), running 100 iterations, with 40 tasks at once, on emulated (slow) sytems. I'm closing this since I can not reproduce it on c50d6b4bcbdf6770a189c4788b13db42393d2121.
