### ISSUE TITLE
[BUG] In a corner case, when tearDown exists, avocado assets fetch command crashes.

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#3661]
While testing https://github.com/wainersm/qemu/tree/acceptance_cpu_hotplug, I found a corner case on `avocado assets fetch` command when trying to fetch the images from `tests/acceptance/boot_linux.py` with the command `avocado assets fetch boot_linux.py`. Avocado crashes with the following messages:

```
Avocado crashed:
Traceback (most recent call last):
  File "/home/wrampazz/.local/bin/avocado", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/wrampazz/src/avocado/avocado.dev/scripts/avocado", line 78, in <module>
    sys.exit(app.run())
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/core/app.py", line 97, in run
    return method(self.parser.config)
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/assets.py", line 298, in run
    success, fail = fetch_assets(test_file)
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/assets.py", line 201, in fetch_assets
    handler = FetchAssetHandler(test_file, klass, method)
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/assets.py", line 66, in __init__
    self.visit(self.tree)
  File "/usr/lib64/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib64/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/lib64/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/assets.py", line 140, in visit_ClassDef
    self.generic_visit(node)
  File "/usr/lib64/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/lib64/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/assets.py", line 172, in visit_Assign
    self.asgmts[cur_klass][cur_method][name] = node.value.s
KeyError: 'tearDown'
```

The following test examples work as expected:

```
from avocado import Test

class FetchKernel(Test):

    def test(self):
        kernel_url = ('https://archives.fedoraproject.org/pub/archive/fedora'
                      '/linux/releases/29/Everything/x86_64/os/images/pxeboot'
                      '/vmlinuz')
        kernel_hash = '23bebd2680757891cf7adedb033532163a792495'
        kernel_path = self.fetch_asset(kernel_url, asset_hash=kernel_hash)

    def tearDown(self):
        if False:
            pass
        super(FetchKernel, self).tearDown()
```
and
```
from avocado import Test

class FetchKernel(Test):

    def test(self):
        pass

    def tearDown(self):
        if False:
            pass
        super(FetchKernel, self).tearDown()
```

The root cause is still unknown.

**Comment by willianrampazzo** [comment]
The main reason for the crash is to have multiple test classes in the same file with an assignment in the class attribute after the first class. In this case, `self.current_method` needs to be reset when starting to parse a new class.
