### ISSUE TITLE
Investigate: FAIL: test_sleep_longer_timeout on Travis, ppc architecture

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#3689]
```
======================================================================
FAIL: test_sleep_longer_timeout (selftests.functional.test_job_timeout.JobTimeOutTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/avocado-framework/avocado/selftests/functional/test_job_timeout.py", line 112, in test_sleep_longer_timeout
    self.run_and_check(cmd_line, 0, 2, 0, 0, 0)
  File "/home/travis/build/avocado-framework/avocado/selftests/functional/test_job_timeout.py", line 61, in run_and_check
    (e_rc, result))
AssertionError: 8 != 0 : Avocado did not return rc 0:
command: '/home/travis/virtualenv/python3.7.2/bin/python3 ./scripts/avocado run --job-results-dir /tmp/avocado__selftests.functional.test_job_timeout__JobTimeOutTest__setUp__hp_v7t9n --sysinfo=off --xunit - --job-timeout=5 /tmp/avocado_timeout_functionalpb35mbta/sleep.sh examples/tests/passtest.py'
exit_status: 8
duration: 33.54085183143616
interrupted: False
pid: 4438
encoding: 'UTF-8'
stdout: b'<?xml version="1.0" encoding="UTF-8"?>\n<testsuite errors="0" failures="0" name="job-2020-04-03T21.33-5b69f45" skipped="1" tests="2" time="3.494" timestamp="2020-04-03T21:34:18.062664">\n\t<testcase classname="SimpleTest" name="1-/tmp/avocado_timeout_functionalpb35mbta/sleep.sh" time="2.312"/>\n\t<testcase classname="TimeOutSkipTest" name="2-examples/tests/passtest.py:PassTest.test" time="1.182">\n\t\t<skipped/>\n\t</testcase>\n</testsuite>\n\n'
stderr: b'/home/travis/build/avocado-framework/avocado/avocado/plugins/run.py:287: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.\n  FutureWarning)\n'
----------------------------------------------------------------------
Ran 1 test in 33.570s
FAILED (failures=1)
```

**Comment by clebergnu** [comment]
I could replicate this very easily on an emulated (very slow) s390x system:

```
Task 1-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout output:
======================================================================
FAIL: test_sleep_longer_timeout (selftests.functional.test_job_timeout.JobTimeOutTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cleber/src/avocado/selftests/functional/test_job_timeout.py", line 107, in test_sleep_longer_timeout
    self.run_and_check(cmd_line, 0, 2, 0, 0, 0)
  File "/home/cleber/src/avocado/selftests/functional/test_job_timeout.py", line 56, in run_and_check
    (e_rc, result))
AssertionError: 8 != 0 : Avocado did not return rc 0:
command: '/usr/bin/python3 -m avocado run --job-results-dir /var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz --sysinfo=off --xunit - --job-timeout=5 /var/tmp/avocado_timeout_functional6890dchu/sleep.sh examples/tests/passtest.py'
exit_status: 8
duration: 61.777382612228394
interrupted: False
pid: 2718
encoding: 'UTF-8'
stdout: b'<?xml version="1.0" encoding="UTF-8"?>\n<testsuite errors="1" failures="0" name="job-2020-08-04T19.48-8c8de45" skipped="1" tests="2" time="13.062" timestamp="2020-08-04T19:48:38.203885">\n\t<testcase classname="SimpleTest" name="1-/var/tmp/avocado_timeout_functional6890dchu/sleep.sh" time="10.813">\n\t\t<error message="Test interrupted by SIGTERM\nRunner error occurred: Timeout reached\nOriginal status: ERROR\n{\'name\': \'1-/var/tmp/avocado_timeout_functional6890dchu/sleep.sh\', \'logdir\': \'/var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz/job-2020-08-04T19.48-8c8de45/test-results/1-_var_tmp_avocado_timeout_functional6890dchu_sleep.sh\', \'logfile\': \'/var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz/job-2020-08-04T19.48-8c8de45/test-results/1-_var_tmp_avocado_timeout_functional6890dchu_sleep.sh/debug.log\', \'status\': \'ERROR\', \'running\': False, \'paused\': False, \'time_start\': 1596570504.17564, \'time_elapsed\': 10.813265562057495, \'time_end\': 1596570514.9889057, \'fail_reason\': \'Test interrupted by SIGTERM\', \'fail_class\': \'RuntimeError\', \'traceback\': \'Traceback (most recent call last):\\n  File &quot;/home/cleber/src/avocado/avocado/core/test.py&quot;, line 856, in _run_avocado\\n    raise test_exception\\n  File &quot;/home/cleber/src/avocado/avocado/core/test.py&quot;, line 762, in _run_avocado\\n    testMethod()\\n  File &quot;/home/cleber/src/avocado/avocado/core/test.py&quot;, line 1156, in test\\n    self._execute_cmd()\\n  File &quot;/home/cleber/src/avocado/avocado/core/test.py&quot;, line 1130, in _execute_cmd\\n    re_warn = re.compile(regex, re.MULTILINE)\\n  File &quot;/usr/lib64/python3.7/re.py&quot;, line 234, in compile\\n    return _compile(pattern, flags)\\n  File &quot;/usr/lib64/python3.7/re.py&quot;, line 286, in _compile\\n    p = sre_compile.compile(pattern, flags)\\n  File &quot;/usr/lib64/python3.7/sre_compile.py&quot;, line 775, in compile\\n    groupindex = p.pattern.groupdict\\n  File &quot;/home/cleber/src/avocado/avocado/plugins/runner.py&quot;, line 77, in sigterm_handler\\n    raise RuntimeError(&quot;Test interrupted by SIGTERM&quot;)\\nRuntimeError: Test interrupted by SIGTERM\\n\', \'timeout\': None, \'whiteboard\': \'\', \'phase\': \'FINISHED\', \'class_name\': \'SimpleTest\', \'job_logdir\': \'/var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz/job-2020-08-04T19.48-8c8de45\', \'job_unique_id\': \'8c8de45458c023fa0a4624e61ac08789ae494ae0\', \'params\': []}" type="RuntimeError\nRUNNER">\n<![CDATA[Traceback (most recent call last):\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 856, in _run_avocado\n    raise test_exception\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 762, in _run_avocado\n    testMethod()\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 1156, in test\n    self._execute_cmd()\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 1130, in _execute_cmd\n    re_warn = re.compile(regex, re.MULTILINE)\n  File "/usr/lib64/python3.7/re.py", line 234, in compile\n    return _compile(pattern, flags)\n  File "/usr/lib64/python3.7/re.py", line 286, in _compile\n    p = sre_compile.compile(pattern, flags)\n  File "/usr/lib64/python3.7/sre_compile.py", line 775, in compile\n    groupindex = p.pattern.groupdict\n  File "/home/cleber/src/avocado/avocado/plugins/runner.py", line 77, in sigterm_handler\n    raise RuntimeError("Test interrupted by SIGTERM")\nRuntimeError: Test interrupted by SIGTERM\n]]>\t\t</error>\n\t\t<system-out>\n<![CDATA[19:48:24 INFO | Running \'/var/tmp/avocado_timeout_functional6890dchu/sleep.sh\'\n19:48:27 INFO | Command \'/var/tmp/avocado_timeout_functional6890dchu/sleep.sh\' finished with 0 after 3.13173770904541s\n19:48:27 INFO | Exit status: 0\n19:48:27 INFO | Duration: 3.13173770904541\n19:48:28 ERROR| \n19:48:28 ERROR| Reproduced traceback from: /home/cleber/src/avocado/avocado/core/test.py:767\n19:48:28 ERROR| Traceback (most recent call last):\n19:48:28 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 1156, in test\n19:48:28 ERROR|     self._execute_cmd()\n19:48:28 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 1130, in _execute_cmd\n19:48:28 ERROR|     re_warn = re.compile(regex, re.MULTILINE)\n19:48:28 ERROR|   File "/usr/lib64/python3.7/re.py", line 234, in compile\n19:48:28 ERROR|     return _compile(pattern, flags)\n19:48:29 ERROR|   File "/usr/lib64/python3.7/re.py", line 286, in _compile\n19:48:29 ERROR|     p = sre_compile.compile(pattern, flags)\n19:48:29 ERROR|   File "/usr/lib64/python3.7/sre_compile.py", line 775, in compile\n19:48:29 ERROR|     groupindex = p.pattern.groupdict\n19:48:29 ERROR|   File "/home/cleber/src/avocado/avocado/plugins/runner.py", line 77, in sigterm_handler\n19:48:29 ERROR|     raise RuntimeError("Test interrupted by SIGTERM")\n19:48:29 ERROR| RuntimeError: Test interrupted by SIGTERM\n19:48:29 ERROR| \n19:48:29 DEBUG| Local variables:\n19:48:34 DEBUG|  -> self <class \'avocado.core.test.SimpleTest\'>: 1-/var/tmp/avocado_timeout_functional6890dchu/sleep.sh\n19:48:34 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)\n19:48:34 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)\n19:48:34 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)\n19:48:34 ERROR| Traceback (most recent call last):\n\n19:48:34 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 856, in _run_avocado\n    raise test_exception\n\n19:48:34 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 762, in _run_avocado\n    testMethod()\n\n19:48:34 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 1156, in test\n    self._execute_cmd()\n\n19:48:34 ERROR|   File "/home/cleber/src/avocado/avocado/core/test.py", line 1130, in _execute_cmd\n    re_warn = re.compile(regex, re.MULTILINE)\n\n19:48:34 ERROR|   File "/usr/lib64/python3.7/re.py", line 234, in compile\n    return _compile(pattern, flags)\n\n19:48:34 ERROR|   File "/usr/lib64/python3.7/re.py", line 286, in _compile\n    p = sre_compile.compile(pattern, flags)\n\n19:48:34 ERROR|   File "/usr/lib64/python3.7/sre_compile.py", line 775, in compile\n    groupindex = p.pattern.groupdict\n\n19:48:34 ERROR|   File "/home/cleber/src/avocado/avocado/plugins/runner.py", line 77, in sigterm_handler\n    raise RuntimeError("Test interrupted by SIGTERM")\n\n19:48:34 ERROR| RuntimeError: Test interrupted by SIGTERM\n\n19:48:34 ERROR| ERROR 1-/var/tmp/avocado_timeout_functional6890dchu/sleep.sh -> RuntimeError: Test interrupted by SIGTERM\n19:48:34 INFO | \n\nRunner error occurred: Timeout reached\nOriginal status: ERROR\n{\'name\': \'1-/var/tmp/avocado_timeout_functional6890dchu/sleep.sh\', \'logdir\': \'/var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz/job-2020-08-04T19.48-8c8de45/test-results/1-_var_tmp_avocado_timeout_functional6890dchu_sleep.sh\', \'logfile\': \'/var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz/job-2020-08-04T19.48-8c8de45/test-results/1-_var_tmp_avocado_timeout_functional6890dchu_sleep.sh/debug.log\', \'status\': \'ERROR\', \'running\': False, \'paused\': False, \'time_start\': 1596570504.17564, \'time_elapsed\': 10.813265562057495, \'time_end\': 1596570514.9889057, \'fail_reason\': \'Test interrupted by SIGTERM\', \'fail_class\': \'RuntimeError\', \'traceback\': \'Traceback (most recent call last):\\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 856, in _run_avocado\\n    raise test_exception\\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 762, in _run_avocado\\n    testMethod()\\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 1156, in test\\n    self._execute_cmd()\\n  File "/home/cleber/src/avocado/avocado/core/test.py", line 1130, in _execute_cmd\\n    re_warn = re.compile(regex, re.MULTILINE)\\n  File "/usr/lib64/python3.7/re.py", line 234, in compile\\n    return _compile(pattern, flags)\\n  File "/usr/lib64/python3.7/re.py", line 286, in _compile\\n    p = sre_compile.compile(pattern, flags)\\n  File "/usr/lib64/python3.7/sre_compile.py", line 775, in compile\\n    groupindex = p.pattern.groupdict\\n  File "/home/cleber/src/avocado/avocado/plugins/runner.py", line 77, in sigterm_handler\\n    raise RuntimeError("Test interrupted by SIGTERM")\\nRuntimeError: Test interrupted by SIGTERM\\n\', \'timeout\': None, \'whiteboard\': \'\', \'phase\': \'FINISHED\', \'class_name\': \'SimpleTest\', \'job_logdir\': \'/var/tmp/avocado__selftests__JobTimeOutTest__setUp__y1szu2tz/job-2020-08-04T19.48-8c8de45\', \'job_unique_id\': \'8c8de45458c023fa0a4624e61ac08789ae494ae0\', \'params\': []}\n]]>\t\t</system-out>\n\t</testcase>\n\t<testcase classname="TimeOutSkipTest" name="2-examples/tests/passtest.py:PassTest.test" time="2.248">\n\t\t<skipped/>\n\t</testcase>\n</testsuite>\n\n'
stderr: b'/home/cleber/src/avocado/avocado/plugins/run.py:290: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. \n  FutureWarning)\n'

----------------------------------------------------------------------
Ran 1 test in 62.309s

FAILED (failures=1)


Status server: exiting due to all tasks finished
Tasks result summary: {'fail': 10}
Tasks ended with 'fail': 10-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 2-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 3-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 9-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 6-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 8-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 4-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 5-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 7-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout, 1-selftests/functional/test_job_timeout.py:JobTimeOutTest.test_sleep_longer_timeout
```

What I believe that's going on here is that we expect that no tests will be skipped, and they end up being skipped:

```
skipped="1"
```

The test assumes, wrongfully, that within the 5 seconds, a simple `passtest.py` will finish successfully.  Since the only way we can control the environment in which those tests run is currently by marking them with `:avocado: tags=parallel:1` so that they are executed once at a time on `selftests/pre_release/jobs/timesensitive.py`.
