### ISSUE TITLE
Failed connecting :22 while both interface pinging still its failing

### ISSUE THREAD

**Issue by smruti77** [avocado-framework/avocado#3760]
both machine is pinging still self._connect() is failing times.

```
'/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check  '''
2020-04-30 03:18:27,976 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check  ''' finished with 255 after 0.0062923431396484375s
2020-04-30 03:18:27,977 process          L0436 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@:22): No such file or directory
2020-04-30 03:18:27,991 stacktrace       L0039 ERROR|
2020-04-30 03:18:27,991 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-04-30 03:18:27,992 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-30 03:18:27,993 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py", line 89, in setUp
2020-04-30 03:18:27,993 stacktrace       L0045 ERROR|     password=self.peer_password)
2020-04-30 03:18:27,993 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 105, in __init__
2020-04-30 03:18:27,993 stacktrace       L0045 ERROR|     self.remote_session = self._connect()
2020-04-30 03:18:27,993 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 117, in _connect
2020-04-30 03:18:27,994 stacktrace       L0045 ERROR|     raise NWException(msg)
2020-04-30 03:18:27,994 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Failed connecting :22
```

**Comment by smruti77** [comment]
[connection.log](https://github.com/avocado-framework/avocado/files/4557129/connection.log)

**Comment by abdhaleegit** [comment]
@beraldoleal  fails to connect to peer using the network.py utils
Could you please have look into this issue, it is blocking all our tests

@PraveenPenguin @narasimhan-v FYI

**Comment by beraldoleal** [comment]
@smruti77 @abdhaleegit, Looks like your host is empty.

```
'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check  '''
2020-04-30 03:18:27,976 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check  ''' finished with 255 after 0.0062923431396484375s
2020-04-30 03:18:27,977 process          L0436 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@:22): No such file or directory
```
/.ssh/avocado-master-root@:22): No such file or directory

Note that there is no host information before the port: **@:22**

Can you please give me more details about this? What are the methods that your test is calling?

**Comment by abdhaleegit** [comment]
@beraldoleal This is the test which is calling the methods from interfaces.py
https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/net/network_test.py

looks like a bad parsing, the host is not empty
# ls .ssh/
avocado-master-root@205.20.20.200:22  id_rsa  id_rsa.pub  known_hosts

**Comment by beraldoleal** [comment]
Looks like your ` self.peer_public_ip = self.params.get("peer_public_ip", default="")` is returning a empty string, right?

Can you double-check what is inside `self.peer_public_ip`?

**Comment by abdhaleegit** [comment]
@beraldoleal sorry my bad, my yaml is not uptodate with the test script.  works now after passing public ip
Thanks

**Comment by abdhaleegit** [comment]
@smruti77 please close this
