### ISSUE TITLE
getting ERROR: Failed connecting 101.10.10.193:22 while interface is pinging.

### ISSUE THREAD

**Issue by smruti77** [avocado-framework/avocado#3801]
``` Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 101.10.10.193 '''
2020-05-11 05:42:20,063 process          L0436 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@101.10.10.193:22): Connection refused
2020-05-11 05:42:20,064 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 101.10.10.193 ''' finished with 255 after 0.006710052490234375s
2020-05-11 05:42:20,279 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 101.10.10.193 '''
2020-05-11 05:42:20,288 process          L0436 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@101.10.10.193:22): Connection refused
2020-05-11 05:42:20,288 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 101.10.10.193 ''' finished with 255 after 0.00662541389465332s
2020-05-11 05:42:20,291 stacktrace       L0039 ERROR|
2020-05-11 05:42:20,292 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-05-11 05:42:20,293 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-11 05:42:20,293 stacktrace       L0045 ERROR|   File "/root/smruti/avocado-misc-tests/io/net/iperf_test.py", line 80, in setUp
2020-05-11 05:42:20,293 stacktrace       L0045 ERROR|     password=self.peer_password)
2020-05-11 05:42:20,293 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 105, in __init__
2020-05-11 05:42:20,293 stacktrace       L0045 ERROR|     self.remote_session = self._connect()
2020-05-11 05:42:20,293 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 117, in _connect
2020-05-11 05:42:20,294 stacktrace       L0045 ERROR|     raise NWException(msg)
2020-05-11 05:42:20,294 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Failed connecting 101.10.10.193:22
```

**Comment by abdhaleegit** [comment]
@beraldoleal We are seeing this on our systems, where the ip is pingable and sshable.. still the connection fails some times, but not all the time

**Comment by beraldoleal** [comment]
Do you have telnet on 22 to that host? This seems to be a network issue and not a library issue.

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please check this as I agree with @beraldoleal as this is not library issue

**Comment by abdhaleegit** [comment]
> Do you have telnet on 22 to that host? Can you run ssh to this host with the user and password used in this library?
> 
> This seems to be a network issue and not a library issue.
I am able to manually ssh from this host using same credentials.
[root@ltc-lp1 net]# telnet 9.a.xyz.abc 22
Trying 9.a.xyz.abc...
Connected to 9.a.xyz.abc.
Escape character is '^]'.
SSH-2.0-OpenSSH_8.0

Invalid SSH identification string.
Connection closed by foreign host.

Is this something wrong with the telnet

**Comment by beraldoleal** [comment]
@abdhaleegit can you fully login into the machine with a ssh client? And try multiple times, since that the problem happens just a few times?

**Comment by vaishnavibhat** [comment]
Facing the same issue with my runs today. This is intermittent though but seen very frequently.

**Comment by beraldoleal** [comment]
Ok, since that is intermittent, it seems to not be related to the network library. I'm closing this. Please reopen if you are sure that is a library issue.

**Comment by abdhaleegit** [comment]
> @abdhaleegit can you fully login into the machine with a ssh client? And try multiple times, since that the problem happens just a few times?
Yes I am able to fully ssh to client and tried multiple and it fails

**Comment by vaishnavibhat** [comment]
#ls /root/.ssh/
avocado-master-root@11.1.1.246:22  avocado-master-root@9.xx.xxx.xxx:22  id_rsa  id_rsa.pub  known_hosts

Deleting the below files and staring the test is helping me proceed. 
avocado-master-root@11.1.1.246:22  
avocado-master-root@9.xx.xxx.xxx:22
