### ISSUE TITLE
Importing main from test fails

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#3897]
The following ERROR with latest avocado.

```
2020-06-09 12:19:21,649 stacktrace       L0039 ERROR|
2020-06-09 12:19:21,649 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:779
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR|   File "/usr/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 1421, in test
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR|     self.error(self.exception)
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR|   File "/usr/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 980, in error
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR|     raise exceptions.TestError(message)
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR| avocado.core.exceptions.TestError: Traceback (most recent call last):
2020-06-09 12:19:21,650 stacktrace       L0045 ERROR|   File "/usr/lib64/python3.6/imp.py", line 235, in load_module
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|     return load_source(name, filename, file)
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|   File "/usr/lib64/python3.6/imp.py", line 172, in load_source
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|     module = _load(spec)
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|   File "<frozen importlib._bootstrap>", line 684, in _load
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|   File "/home/harish/avocado-misc-tests/memory/ndctl.py", line 29, in <module>
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|     from avocado import main
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR| ImportError: cannot import name 'main'
2020-06-09 12:19:21,651 stacktrace       L0045 ERROR|
2020-06-09 12:19:21,651 stacktrace       L0046 ERROR|
```
The issue occurs when importing main from a testcase.
`from avocado import main`

Please help with fixing this.
```
# avocado -v
Avocado 80.0
```
The issue seems to have occurred with the recent changes.
Please let know if any other details are required.

**Comment by willianrampazzo** [comment]
Hi @harish-24, this feature was deprecated on release 79 and removed on 80. Check here: https://github.com/avocado-framework/avocado/pull/3845.

**Comment by clebergnu** [comment]
@harish-24 the fix may be as simple as removing the `main` import and its usage, assuming you're running tests with the `avocado` command line tool.  If you were in fact using the "standalone" feature, then you'll need to either reconsider or adapt.

FIY, there was a simple a "shout out" on the mailing list about it:

https://www.redhat.com/archives/avocado-devel/2020-May/msg00014.html

**Comment by harish-24** [comment]
@willianrampazzo @clebergnu Thank you for the update. Din't notice in the mailing list, Sorry for the noise. Closing this.
