### ISSUE TITLE
interfaces.py :  Create a new network config file if not present and move to backup 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework/avocado#4076]
```
2020-08-10 05:39:07,325 stacktrace       L0039 ERROR|
2020-08-10 05:39:07,325 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:804
2020-08-10 05:39:07,332 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-08-10 05:39:07,332 stacktrace       L0045 ERROR|   File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/multicast.py", line 132, in tearDown
2020-08-10 05:39:07,332 stacktrace       L0045 ERROR|     self.networkinterface.restore_from_backup()
2020-08-10 05:39:07,332 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/network/interfaces.py", line 339, in restore_from_backup
2020-08-10 05:39:07,332 stacktrace       L0045 ERROR|     "Backup file not available, could not restore file.")
2020-08-10 05:39:07,332 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Backup file not available, could not restore file.
2020-08-10 05:39:07,332 stacktrace       L0046 ERROR|

**Comment by abdhaleegit** [comment]
currently the code for ip config handles this way; if config file is their it will move to backup or else it will create new one without move operation. 

So if no config exists, create new one and also move to backup

**Comment by smruti77** [comment]
#1862

**Comment by beraldoleal** [comment]
@smruti77 not understood the relationship between 1862 and this. 

Also, @abdhaleegit, after the discussion here https://github.com/avocado-framework/avocado/pull/4077, and since this is a library that exports "reasons" to the upper layers, this should be handled properly with try.. except.

I'm closing this, but please, feel free to reopen the discussion.

**Comment by smruti77** [comment]
@beraldoleal just pointed that PR its because this issue handle in another way, so no need to handle like this and for closing the issue.
