### ISSUE TITLE
When avocado (or perhaps even test) is inside path which containst ` `, it fails

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado#415]
When you put avocado inside `/whatever/path with spaces/in/it`, test fails:

```
[medic@t530 avocado ]$ ./scripts/avocado run DEVCONF/Basic_usage/output_compare.sh --show-job-log
Profilers declared: ['vmstat 1', 'journalctl -f']
Profiler disabled
Not logging /proc/slabinfo (lack of permissions)
Profilers declared: ['vmstat 1', 'journalctl -f']
Profiler disabled
START DEVCONF/Basic_usage/output_compare.sh

Test instance parameters:
    id = DEVCONF/Basic_usage/output_compare.sh
    omit_non_tests = False

Default parameters:

Test instance params override defaults whenever available

Running '/home/medic/Work/Projekty/2015-DevConf - Avocado workshop/tmp/avocado/DEVCONF/Basic_usage/output_compare.sh'

Traceback (most recent call last):
  File "/home/medic/Work/Projekty/2015-DevConf - Avocado workshop/tmp/avocado/avocado/test.py", line 538, in action
    result = process.run(self.path, verbose=True, env=test_params)
  File "/home/medic/Work/Projekty/2015-DevConf - Avocado workshop/tmp/avocado/avocado/utils/process.py", line 938, in run
    cmd_result = sp.run(timeout=timeout)
  File "/home/medic/Work/Projekty/2015-DevConf - Avocado workshop/tmp/avocado/avocado/utils/process.py", line 497, in run
    self._init_subprocess()
  File "/home/medic/Work/Projekty/2015-DevConf - Avocado workshop/tmp/avocado/avocado/utils/process.py", line 298, in _init_subprocess
    env=self.env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):

  File "/home/medic/Work/Projekty/2015-DevConf - Avocado workshop/tmp/avocado/avocado/test.py", line 427, in runTest
    raise action_exception

OSError: [Errno 2] No such file or directory

FAIL DEVCONF/Basic_usage/output_compare.sh -> OSError: [Errno 2] No such file or directory

Not logging /proc/slabinfo (lack of permissions)

```

**Comment by lmr** [comment]
Closing per #459
