### ISSUE TITLE
Avocado `jobs show` with a nrunner based runner

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4150]
Reproducer follows:

```
$ avocado run --test-runner=nrunner /bin/uname 
JOB ID     : 984df6eed86ace8a52a1327481a3e9f05b79880a
JOB LOG    : /home/cleber/avocado/job-results/job-2020-08-27T14.43-984df6e/job.log
 (suite01-1/1) /bin/uname: PASS (0.00 s)
 (suite01-1/1) /bin/uname: STARTED
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2020-08-27T14.43-984df6e/results.html
JOB TIME   : 1.04 s
[cleber@localhost avocado]$ avocado jobs show latest
Avocado crashed unexpectedly: Expecting value: line 1 column 1 (char 0)
You can find details in /home/cleber/avocado/data/crashes/avocado-traceback-2020-08-27_14:43:55-egm5d8pc.log
```

And crash log:

```
Avocado crashed:
Traceback (most recent call last):
  File "/home/cleber/.local/bin/avocado", line 11, in <module>
    load_entry_point('avocado-framework', 'console_scripts', 'avocado')()
  File "/home/cleber/src/avocado/avocado/avocado/core/main.py", line 76, in main
    return app.run()
  File "/home/cleber/src/avocado/avocado/avocado/core/app.py", line 112, in run
    return method(self.parser.config)
  File "/home/cleber/src/avocado/avocado/avocado/plugins/jobs.py", line 254, in run
    job = json.load(fp)
  File "/usr/lib64/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by clebergnu** [comment]
The same issue can be seem with:

```
$ avocado jobs get-output-files latest /tmp/
Avocado crashed unexpectedly: Expecting value: line 1 column 1 (char 0)
You can find details in /home/cleber/avocado/data/crashes/avocado-traceback-2020-08-27_14:46:24-iwy3kz41.log
```

Same crash log:

```
Avocado crashed:
Traceback (most recent call last):
  File "/home/cleber/.local/bin/avocado", line 11, in <module>
    load_entry_point('avocado-framework', 'console_scripts', 'avocado')()
  File "/home/cleber/src/avocado/avocado/avocado/core/main.py", line 76, in main
    return app.run()
  File "/home/cleber/src/avocado/avocado/avocado/core/app.py", line 112, in run
    return method(self.parser.config)
  File "/home/cleber/src/avocado/avocado/avocado/plugins/jobs.py", line 254, in run
    job = json.load(fp)
  File "/usr/lib64/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by beraldoleal** [comment]
@clebergnu, cant reproduce:


```bash
[local@laptop avocado]$ avocado run --test-runner=nrunner /bin/uname 
JOB ID     : e960f67210967afc3215fec9d64a3998dc4d06ab
JOB LOG    : /home/local/avocado/job-results/job-2020-08-27T15.52-e960f67/job.log
 (suite01-1/1) /bin/uname: PASS (0.00 s)
 (suite01-1/1) /bin/uname: STARTED
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/local/avocado/job-results/job-2020-08-27T15.52-e960f67/results.html
JOB TIME   : 1.02 s
[local@laptop avocado]$ avocado jobs show latest
JOB ID      : latest
JOB LOG     : /home/local/avocado/job-results/job-2020-08-27T15.52-e960f67/job.log
SPAWNER     : process

Test ID              End Time            Run Time Status
suite01-1-/bin/uname 1970/01/11 20:18:42 0.002459 PASS
RESULTS     : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 |WARN 0 | INTERRUPT 0 | CANCEL 0
```

With master.

**Comment by clebergnu** [comment]
> @clebergnu, cant reproduce:
> 
> ```shell
> [local@laptop avocado]$ avocado run --test-runner=nrunner /bin/uname 
> JOB ID     : e960f67210967afc3215fec9d64a3998dc4d06ab
> JOB LOG    : /home/local/avocado/job-results/job-2020-08-27T15.52-e960f67/job.log
>  (suite01-1/1) /bin/uname: PASS (0.00 s)
>  (suite01-1/1) /bin/uname: STARTED
> RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB HTML   : /home/local/avocado/job-results/job-2020-08-27T15.52-e960f67/results.html
> JOB TIME   : 1.02 s
> [local@laptop avocado]$ avocado jobs show latest
> JOB ID      : latest
> JOB LOG     : /home/local/avocado/job-results/job-2020-08-27T15.52-e960f67/job.log
> SPAWNER     : process
> 
> Test ID              End Time            Run Time Status
> suite01-1-/bin/uname 1970/01/11 20:18:42 0.002459 PASS
> RESULTS     : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 |WARN 0 | INTERRUPT 0 | CANCEL 0
> ```
> 
> With master.

Weird... also on master.  Double checking here.

**Comment by willianrampazzo** [comment]
Also working here:

```
[wrampazz@wrampazz avocado.dev]$ avocado run --test-runner=nrunner /bin/uname
JOB ID     : 0e5a26c0e962d9a4c509bac5550cf1b775f9e741
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-08-27T16.04-0e5a26c/job.log
 (suite01-1/1) /bin/uname: PASS (0.00 s)
 (suite01-1/1) /bin/uname: STARTED
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-08-27T16.04-0e5a26c/results.html
JOB TIME   : 1.48 s

[wrampazz@wrampazz avocado.dev]$ avocado jobs show latest
JOB ID      : latest
JOB LOG     : /home/wrampazz/avocado/job-results/job-2020-08-27T16.04-0e5a26c/job.log
SPAWNER     : process

Test ID              End Time            Run Time Status
suite01-1-/bin/uname 1970/01/02 12:10:18 0.001691 PASS
RESULTS     : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 |WARN 0 | INTERRUPT 0 | CANCEL 0
[wrampazz@wrampazz avocado.dev]$
```

**Comment by clebergnu** [comment]
Something with some of my stale results files.  After a clean up, it's now working.
