### ISSUE TITLE
The migration testing and vt-config file problems

### ISSUE THREAD

**Issue by anascko** [avocado-framework/avocado#4163]
When trying to use the vt-config file and run migration tests seem avocado couldn't get params and testing fails with exeption:
10:10:55 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:750
10:10:55 ERROR| Traceback (most recent call last):
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/avocado_vt/test.py", line 253, in setUp
10:10:55 ERROR|     self._runTest()
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/avocado_vt/test.py", line 421, in _runTest
10:10:55 ERROR|     params = env_process.preprocess(self, params, env)
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/error_context.py", line 135, in new_fn
10:10:55 ERROR|     return fn(*args, **kwargs)
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/env_process.py", line 1356, in preprocess
10:10:55 ERROR|     fs_source_func=preprocess_fs_source)
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/env_process.py", line 878, in process
10:10:55 ERROR|     _call_vm_func()
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/env_process.py", line 790, in _call_vm_func
10:10:55 ERROR|     vm_func(test, vm_params, env, vm_name)
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/env_process.py", line 297, in preprocess_vm
10:10:55 ERROR|     migration_exec_cmd=params.get("migration_exec_cmd_dst"))
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/error_context.py", line 135, in new_fn
10:10:55 ERROR|     return fn(*args, **kwargs)
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/qemu_vm.py", line 2879, in create
10:10:55 ERROR|     self.devices, self.spice_options = self.make_create_command()
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/qemu_vm.py", line 1474, in make_create_command
10:10:55 ERROR|     devs = devices.machine_by_params(params)
10:10:55 ERROR|   File "/usr/lib/python3.6/site-packages/virttest/qemu_devices/qcontainer.py", line 1392, in machine_by_params
10:10:55 ERROR|     (machine_type))
10:10:55 ERROR| avocado.core.exceptions.TestSkipError: Unsupported machine type pseries-2.12.
10:10:55 ERROR| 
10:10:55 ERROR| SKIP 001
[ld_migrate.txt](https://github.com/avocado-framework/avocado/files/5151114/ld_migrate.txt)

example vt-config file
[ld_migrate.txt](https://github.com/avocado-framework/avocado/files/5151123/ld_migrate.txt)

:

**Comment by beraldoleal** [comment]
Hi @anascko can you also paste the command-line used, if possible?

**Comment by anascko** [comment]
@beraldoleal 
Sorry, the command is:
avocado run --vt-config /var/lib/libvirt/images/avocado/avocado-vt/backends/qemu/cfg/ld_migrate.cfg --vt-guest-os "$GUEST_OS" --vt-arch "{guest-arch}" --vt-machine-type "{vt-machine}"

**Comment by PaulYuuu** [comment]
Hello @anascko, logs should be about avocado-vt, do you still encounter this problem?
If yes, can you try to execute following commands on your host and provide results?

```python
>>> from avocado.utils import process
>>> process.run("/root/qemu/ppc64-softmmu/qemu-system-ppc64 -M \?",ignore_status=True,shell=True,verbose=False).stdout_text
'Supported machines are:\n40p                  IBM RS/6000 7020 (40p)\nbamboo               bamboo\ng3beige              Heathrow based PowerMAC\nmac99                Mac99 based PowerMAC\nmpc8544ds            mpc8544ds\nnone                 empty machine\npowernv10            IBM PowerNV (Non-Virtualized) POWER10\npowernv8             IBM PowerNV (Non-Virtualized) POWER8\npowernv              IBM PowerNV (Non-Virtualized) POWER9 (alias of powernv9)\npowernv9             IBM PowerNV (Non-Virtualized) POWER9\nppce500              generic paravirt e500 platform\npseries-2.1          pSeries Logical Partition (PAPR compliant)\npseries-2.10         pSeries Logical Partition (PAPR compliant)\npseries-2.11         pSeries Logical Partition (PAPR compliant)\npseries-2.12         pSeries Logical Partition (PAPR compliant)\npseries-2.12-sxxm    pSeries Logical Partition (PAPR compliant)\npseries-2.2          pSeries Logical Partition (PAPR compliant)\npseries-2.3          pSeries Logical Partition (PAPR compliant)\npseries-2.4          pSeries Logical Partition (PAPR compliant)\npseries-2.5          pSeries Logical Partition (PAPR compliant)\npseries-2.6          pSeries Logical Partition (PAPR compliant)\npseries-2.7          pSeries Logical Partition (PAPR compliant)\npseries-2.8          pSeries Logical Partition (PAPR compliant)\npseries-2.9          pSeries Logical Partition (PAPR compliant)\npseries-3.0          pSeries Logical Partition (PAPR compliant)\npseries-3.1          pSeries Logical Partition (PAPR compliant)\npseries-4.0          pSeries Logical Partition (PAPR compliant)\npseries-4.1          pSeries Logical Partition (PAPR compliant)\npseries-4.2          pSeries Logical Partition (PAPR compliant)\npseries-5.0          pSeries Logical Partition (PAPR compliant)\npseries              pSeries Logical Partition (PAPR compliant) (alias of pseries-5.1)\npseries-5.1          pSeries Logical Partition (PAPR compliant) (default)\nref405ep             ref405ep\nsam460ex             aCube Sam460ex\ntaihu                taihu\nvirtex-ml507         Xilinx Virtex ML507 reference design\n'
