### ISSUE TITLE
legacy replay: failed to replay with test status FAIL

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4176]
Trying to follow our documentation examples, we have:

```bash
(avocado) [local@laptop avocado]$ avocado run /bin/true /bin/false
JOB ID     : 5216928ea7ff462ea6e18b572ba75d5f2311ab5f
JOB LOG    : /home/local/avocado/job-results/job-2020-09-02T09.02-5216928/job.log
 (1/2) /bin/true: PASS (0.01 s)
 (2/2) /bin/false: FAIL: Exited with status: '1', stdout: '' stderr: '' (0.07 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/local/avocado/job-results/job-2020-09-02T09.02-5216928/results.html
JOB TIME   : 0.37 s
```

and when trying to replay:

```bash
(avocado) [local@laptop avocado]$ avocado run --replay latest --replay-test-status FAIL
Overriding the replay loaders with the --loaders value given on the command line.
Overriding the replay failfast with the --failfast value given on the command line.
Overriding the replay ignore-missing-references with the --ignore-missing-references value given on the command line.
Overriding the replay execution-order with the --execution-order value given on the command line.
Using src job variants data only, use `--replay-ignore variants` to override them.
Overriding the replay loaders with the --loaders value given on the command line.
Overriding the replay failfast with the --failfast value given on the command line.
Overriding the replay ignore-missing-references with the --ignore-missing-references value given on the command line.
Overriding the replay execution-order with the --execution-order value given on the command line.
Using src job variants data only, use `--replay-ignore variants` to override them.
JOB ID     : 6f384aa49168e5d7577117c1f0d4103c4787e1f7
SRC JOB ID : 5216928ea7ff462ea6e18b572ba75d5f2311ab5f
JOB LOG    : /home/local/avocado/job-results/job-2020-09-02T09.02-6f384aa/job.log
Error running method "initialize" of plugin "json_variants": list indices must be integers or slices, not str
Error running method "__len__" of plugin "json_variants": Calling Varianter __len__ beforeinitialization is not supported

Avocado crashed: TestError: Process died before it pushed early test_status.
Traceback (most recent call last):

  File "/home/local/src/beraldo/avocado/avocado/core/job.py", line 604, in run_tests
    summary |= suite.run(self)

  File "/home/local/src/beraldo/avocado/avocado/core/suite.py", line 266, in run
    return self.runner.run_suite(job, self)

  File "/home/local/src/beraldo/avocado/avocado/plugins/runner.py", line 384, in run_suite
    deadline):

  File "/home/local/src/beraldo/avocado/avocado/plugins/runner.py", line 168, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/home/local/src/beraldo/avocado/avocado/core/runner.py", line 138, in wait_for_early_status
    raise exceptions.TestError("Process died before it pushed "

avocado.core.exceptions.TestError: Process died before it pushed early test_status.

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new

```

**Comment by willianrampazzo** [comment]
As we are deprecating the legacy `replay`, I think we can update the documentation to use the new `replay` subcommand for now. Although it does not support the `--replay-test-status` parameter yet, we won't spend efforts fixing something that will not exist soon.

**Comment by beraldoleal** [comment]
I'm ok with that. @clebergnu what do you think here? Do we need to keep the legacy replay on the LTS release?

**Comment by clebergnu** [comment]
> I'm ok with that. @clebergnu what do you think here? Do we need to keep the legacy replay on the LTS release?

I think this is fixed here: https://github.com/avocado-framework/avocado/pull/4188
