### ISSUE TITLE
[Software-Manager] Cannot find `sudo` in PATH but it is available.

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4263]
While running `avocado-software-manager`, it complains about not finding the `sudo` command in any of the `PATH` dirs, but it is available in one of them.

```
[wrampazz@wrampazz avocado.dev]$ avocado-software-manager install vim-common
dnf module for Python is required. Using the basic support from rpm and dnf commands
Command 'sudo' could not be found in any of the PATH dirs: ['/usr/local/sbin', '/usr/bin', '/home/wrampazz/bin', '/usr/sbin', '/sbin', '/var/lib/snapd/snap/bin', '/usr/local/bin', '/usr/libexec', '/home/wrampazz/.local/bin', '/bin', '/usr/share/Modules/bin']
Parameter sudo=True provided, but sudo was not found. Please consider adding sudo to your OS image
Running '/usr/bin/dnf -y install vim-common'
Command '/usr/bin/dnf -y install vim-common' finished with 1 after 0.18606805801391602s
Failed to install vim-common

[wrampazz@wrampazz avocado.dev]$ which sudo
/usr/bin/sudo
```

**Comment by willianrampazzo** [comment]
I have not investigated deeper, but the problem may be here https://github.com/avocado-framework/avocado/blob/master/avocado/utils/path.py#L77

```
[wrampazz@wrampazz avocado-82lts]$ python
Python 3.8.5 (default, Aug 12 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import path
>>> path.find_command('sudo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/utils/path.py", line 109, in find_command
    raise CmdNotFoundError(cmd, path_paths)
avocado.utils.path.CmdNotFoundError: Command 'sudo' could not be found in any of the PATH dirs: ['/home/wrampazz/.local/bin', '/var/lib/snapd/snap/bin', '/home/wrampazz/bin', '/usr/libexec', '/sbin', '/usr/sbin', '/bin', '/usr/share/Modules/bin', '/usr/local/bin', '/usr/bin', '/usr/local/sbin']

>>> path.find_command('echo')
'/bin/echo'
>>>
```

**Comment by clebergnu** [comment]
If your system is like mine, the following check on `find_command()` will fail for `/usr/bin/sudo`:

```python
                if not os.access(cmd_path, os.R_OK | os.X_OK):
```

**Comment by willianrampazzo** [comment]
> If your system is like mine, the following check in `find_command()` will fail for `/usr/bin/sudo`:
> 
> ```python
>                 if not os.access(cmd_path, os.R_OK | os.X_OK):
> ```

Yep, that is it:

```
---s--x--x.  1 root root       186592 Sep 15 12:07  sudo

>>> os.access("/usr/bin/sudo", os.R_OK | os.X_OK)
False
```
