### ISSUE TITLE
Testlog plugin do not output fail on check.py

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4341]
When enabling the test log plugin on `selftest/check.py` with the following:

```
diff --git a/selftests/check.py b/selftests/check.py
index 920d9971..60112f76 100755
--- a/selftests/check.py
+++ b/selftests/check.py
@@ -508,7 +508,8 @@ def main():
     # Job execution
     # ========================================================================
     config = {'core.show': ['app'],
-              'run.test_runner': 'nrunner'}
+              'run.test_runner': 'nrunner',
+              'job.output.testlogs.statuses': ['FAIL', 'ERROR']}
     with Job(config, suites) as j:
         return j.run()
```

And forcing a fail, the log is not shown:

```
...
RESULTS    : PASS 927 | ERROR 0 | FAIL 1 | SKIP 49 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-12-04T16.49-84ea030/results.html
JOB TIME   : 220.09 s
Log content for test "check-238-selftests/unit/fail.py:PassTest.test" (FAIL)
Error running method "post" of plugin "testlogs": [Errno 2] No such file or directory: '<unknown>'
make: *** [Makefile:127: check] Error 1
```

The expected result is something like:

```
RESULTS    : PASS 927 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-12-04T16.41-a40ef9d/results.html
JOB TIME   : 220.09 s
Log content for test "check-238-selftests/unit/fail.py:PassTest.test" (FAIL)
16:41:28 ERROR| 
16:41:28 ERROR| Reproduced traceback from: /home/wrampazz/src/avocado/avocado.quick-dev/avocado/core/test.py:767
16:41:28 ERROR| Traceback (most recent call last):
16:41:28 ERROR|   File "/home/wrampazz/src/avocado/custom/passtest.py", line 10, in test
16:41:28 ERROR|     self.fail()
16:41:28 ERROR|   File "/home/wrampazz/src/avocado/avocado.quick-dev/avocado/core/test.py", line 953, in fail
16:41:28 ERROR|     raise exceptions.TestFail(message)
16:41:28 ERROR| avocado.core.exceptions.TestFail: None
16:41:28 ERROR| 
16:41:28 DEBUG| Local variables:
16:41:28 DEBUG|  -> self <class 'passtest.PassTest'>: 1-passtest.py:PassTest.test
16:41:28 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
16:41:28 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
16:41:28 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
16:41:28 ERROR| FAIL 1-passtest.py:PassTest.test -> TestFail: None
16:41:28 INFO |
```

**Comment by willianrampazzo** [comment]
So, the job results are created during the job execution, but it seems it gets messed up with multiple jobs running.

Here is the `test` object of a single job run:

```
{'end': 1607114433.4337378, 'fail_reason': 'None', 'id': '3-passtest.py:PassTest.test2', 'logdir': '/home/wrampazz/avocado/job-results/job-2020-12-04T17.40-7a7ef18/test-results/3-passtest.py_PassTest.test2', 'logfile': '/home/wrampazz/avocado/job-results/job-2020-12-04T17.40-7a7ef18/test-results/3-passtest.py_PassTest.test2/debug.log', 'start': 1607114433.3963182, 'status': 'FAIL', 'time': 0.03741955757141113, 'whiteboard': ''}
```

Here is the `test` object from the `check.py` run:

```
{'end': 180499.806592928, 'fail_reason': '<unknown>', 'id': 'check-2-selftests/inspekt-style.sh', 'logdir': '', 'logfile': '<unknown>', 'start': 180499.473613308, 'status': 'FAIL', 'time': 0.3329796200268902, 'whiteboard': '<unknown>'}
```

**Comment by richtja** [comment]
@willianrampazzo Hi I did some tests and had different outputs that you. I can replicate this bug also in single job run. For single and multiple jobs, the test object is same:

```
 {'end': 183656.503226494, 'fail_reason': '<unknown>', 'id': '029ef333-6f25-4201-9b87-ae0bd8872f2f-1-/home/jarichte/Avocado/avocado/examples/tests/failtest.py:FailTest.test', 'logdir': '', 'logfile': '<unknown>', 'start': 183656.460184297, 'status': 'FAIL', 'time': 0.04304219700861722, 'whiteboard': '<unknown>'}
```
but when I used legacy runner instead of nrunner everything works fine:
```
{'end': 1613558718.2736585, 'fail_reason': 'This test is supposed to fail', 'id': '08c91987-6b26-46ef-8cff-21758e780044-1-/home/jarichte/Avocado/avocado/examples/tests/failtest.py:FailTest.test', 'logdir': '/home/jarichte/avocado/job-results/job-2021-02-17T11.45-bb50d48/test-results/08c91987-6b26-46ef-8cff-21758e780044-1-_home_jarichte_Avocado_avocado_examples_tests_failtest.py_FailTest.test', 'logfile': '/home/jarichte/avocado/job-results/job-2021-02-17T11.45-bb50d48/test-results/08c91987-6b26-46ef-8cff-21758e780044-1-_home_jarichte_Avocado_avocado_examples_tests_failtest.py_FailTest.test/debug.log', 'start': 1613558718.0979617, 'status': 'FAIL', 'time': 0.17569684982299805, 'whiteboard': ''}
```
So it looks like a problem inside nrunner. Can you please check that you have the same behavior, thanks.
