### ISSUE TITLE
Improve asset hash mismatch error message during fetch

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4342]
In the current implementation, when an asset is fetched but there is a hash mismatch, the error message says the download failed:

```
2020-12-04 19:26:42,233 boot_xen         L0047 INFO | xen_url: https://deb.debian.org/debian-security/pool/updates/main/x/xen/xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb, hash:4326c63c9f346c6189bca1128d80c54e
2020-12-04 19:26:42,237 asset            L0320 INFO | Asset not in cache, fetching it.
2020-12-04 19:26:42,237 download         L0067 INFO | Fetching https://deb.debian.org/debian-security/pool/updates/main/x/xen/xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb -> /home/alex/avocado/data/cache/by_location/a9513b030295ed2988bdde6f076d363fb5c38217/xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb.m3568vh_
2020-12-04 19:26:42,361 download         L0051 DEBUG| Retrieved URL "https://deb.debian.org/debian-security/pool/updates/main/x/xen/xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb": content-length 3583644, date: "Fri, 04 Dec 2020 19:26:42 GMT", last-modified: "Thu, 01 Oct 2020 20:29:19 GMT"
2020-12-04 19:26:43,447 stacktrace       L0039 ERROR|
2020-12-04 19:26:43,447 stacktrace       L0042 ERROR| Reproduced traceback from: /home/alex/lsrc/qemu.git/builds/arm.all/tests/venv/lib/python3.7/site-packages/avocado/core/test.py:764
2020-12-04 19:26:43,447 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-12-04 19:26:43,447 stacktrace       L0045 ERROR|   File "/home/alex/lsrc/qemu.git/builds/arm.all/tests/venv/lib/python3.7/site-packages/avocado/core/test.py", line 1027, in fetch_asset
2020-12-04 19:26:43,447 stacktrace       L0045 ERROR|     asset_path = asset_func()
2020-12-04 19:26:43,447 stacktrace       L0045 ERROR|   File "/home/alex/lsrc/qemu.git/builds/arm.all/tests/venv/lib/python3.7/site-packages/avocado/utils/asset.py", line 360, in fetch
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|     raise OSError("Failed to fetch %s." % self.asset_name)
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR| OSError: Failed to fetch xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb.
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|   File "/home/alex/lsrc/qemu.git/builds/arm.all/tests/acceptance/boot_xen.py", line 49, in test_arm64_xen_and_domU
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|     xen_deb  = self.fetch_asset(xen_url, asset_hash=xen_hash)
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|   File "/home/alex/lsrc/qemu.git/builds/arm.all/tests/acceptance/avocado_qemu/__init__.py", line 208, in fetch_asset
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|     cancel_on_missing=cancel_on_missing)
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|   File "/home/alex/lsrc/qemu.git/builds/arm.all/tests/venv/lib/python3.7/site-packages/avocado/core/test.py", line 1034, in fetch_asset
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|     self.cancel(missing_asset_message)
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|   File "/home/alex/lsrc/qemu.git/builds/arm.all/tests/venv/lib/python3.7/site-packages/avocado/core/test.py", line 984, in cancel
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR|     raise exceptions.TestCancel(message)
2020-12-04 19:26:43,448 stacktrace       L0045 ERROR| avocado.core.exceptions.TestCancel: Missing asset https://deb.debian.org/debian-security/pool/updates/main/x/xen/xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb
2020-12-04 19:26:43,448 stacktrace       L0046 ERROR|
2020-12-04 19:26:43,448 test             L0933 ERROR| CANCEL 1-./tests/acceptance/boot_xen.py:BootXen.test_arm64_xen_and_domU -> TestCancel: Missing asset https://deb.debian.org/debian-security/pool/updates/main/x/xen/xen-hypervisor-4.11-arm64_4.11.4+37-g3263f257ca-1_arm64.deb
2020-12-04 19:26:43,448 test             L0922 INFO |
2020-12-04 19:26:43,459 job              L0610 INFO | Test results available in /home/alex/avocado/job-results/job-2020-12-04T19.26-60a5a0d
```

Avocado needs to give a clear message of what was the cause of the failure.

**Comment by beraldoleal** [comment]
I'm working on #4313 and I think I have a better idea of this now. So I will give it a try here too.
