### ISSUE TITLE
 Control socket connect(/root/.ssh/avocado-master-root@abc:22): No such file or directory ssh session connect fails for first time

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework/avocado#4386]
Ssh session connect fails to create control socket for the first time connecting between 2 machine

```
4:52:13 DEBUG| [stdout] Desired Variable Capacity Weight             : 0
04:52:14 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -O check 10.12.13.14 '''
04:52:14 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@10.12.13.14:22): No such file or directory
04:52:14 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -O check 10.12.13.14 ''' finished with 255 after 0.012701988220214844s
04:52:14 ERROR|
04:52:14 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py:753
04:52:14 ERROR| Traceback (most recent call last):
04:52:14 ERROR|   File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/virt-net/network_virtualization.py", line 77, in setUp
04:52:14 ERROR|     self.cancel("failed connecting to HMC")
04:52:14 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py", line 984, in cancel
04:52:14 ERROR|     raise exceptions.TestCancel(message)
04:52:14 ERROR| avocado.core.exceptions.TestCancel: failed connecting to HMC
04:52:14 ERROR|
04:52:14 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -O exit 10.12.13.14 '''
04:52:14 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@10.12.13.14:22): No such file or directory
04:52:14 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -O exit 10.12.13.14 ''' finished with 255 after 0.005923271179199219s

```
ls .ssh/
id_rsa  id_rsa.pub  known_hosts  tmp_authorized_keys2

But when I tried manual ssh to remote machine and than start the ssh.connect works

` $ scp root@10.12.13.14
The authenticity of host abc.com (10.12.13.14) can't be established.
ECDSA key fingerprint is SHA256:pd8Ir2tHlDEUuRNeFPYQvW1NZ1ApxKnbo9AgLO6uFJw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'abc.com' (ECDSA) to the list of known hosts.
Password: 
root@abc:~> 

# ls .ssh/
id_rsa  id_rsa.pub  known_hosts  tmp_authorized_keys2

```
021-01-19 05:14:54,477 process          L0416 DEBUG| [stdout] Desired Variable Capacity Weight             : 0
2021-01-19 05:14:54,479 process          L0604 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -O check 10.12.13.14 '''
2021-01-19 05:14:54,487 process          L0416 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-hscroot@10.12.13.14:22): No such file or directory
2021-01-19 05:14:54,487 process          L0686 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -O check 10.12.13.14 ''' finished with 255 after 0.006031990051269531s
2021-01-19 05:14:54,775 process          L0604 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 10.12.13.14 '''
2021-01-19 05:14:54,783 process          L0416 DEBUG| [stderr] Master running (pid=165025)
2021-01-19 05:14:54,783 process          L0686 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -O check 10.12.13.14 ''' finished with 0 after 0.0062046051025390625s
2021-01-19 05:14:54,791 process          L0604 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -q 10.12.13.14 'lssyscfg -r sys  -F name''
2021-01-19 05:14:54,821 process          L0416 DEBUG| [stdout] ltcden13
2021-01-19 05:14:54,822 process          L0416 DEBUG| [stdout] ltcden10
2021-01-19 05:14:54,822 process          L0416 DEBUG| [stdout] ltcden11
```

**Comment by beraldoleal** [comment]
Are you manually removing the control file before this? For instance, calling `.cleanup_master()` or manually?
