### ISSUE TITLE
Unit test names hard to pin down and debug

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#4397]
Hi all, I have recently turned on the flag about running unit tests during the Avocado RPM build and get some failing unit tests which are not run through avocado rather than default python unittest modules:
```
RESULTS    : PASS 940 | ERROR 0 | FAIL 16 | SKIP 36 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /mnt/local/results/job-2021-02-02T18.11-b3df800/results.html
JOB TIME   : 175.56 s
```
Filtering the result HTML reports for the failed tests reveals:
![image](https://user-images.githubusercontent.com/1969979/106639879-19f24000-658e-11eb-9ad7-3579ba060c3e.png)
However, there are no error messages in the LOG_UI when the tests fail as well as no error messages in the "Info" section of the HTML report. Clicking on the links does not bring to the folder name but this aside, if I locate the corresponding test folders, inside there is nothing:
```
> ls job-2021-02-02T18.11-b3df800/test-results/check-636-selftests_functional_test_nrunner.py_ResolveSerializeRun.test
data
> cat job-2021-02-02T18.11-b3df800/test-results/check-636-selftests_functional_test_nrunner.py_ResolveSerializeRun.test/*
None
```
So then I tried to at least locate the errors in the `job.log`, however searching for the corresponding test name does not bring to anything:
```
> grep job-2021-02-02T18.11-b3df800/ResolveSerializeRun.test job.log 
> grep job-2021-02-02T18.11-b3df800/ResolveSerializeRun job.log
> echo $?
1
```
Is there any easy matching between the unit test names displayed in either the job report or UI that I could easily match?

Btw, the errors from tests I cannot yet match correctly look like:
```
2021-02-02 18:12:09,136 test             L0530 INFO | START 75a71185-cd59-4a24-b7d4-d10887da3201-1-/bin/false
2021-02-02 18:12:09,136 test             L0205 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)
2021-02-02 18:12:09,137 process          L0604 INFO | Running '/bin/false'
2021-02-02 18:12:09,141 process          L0685 INFO | Command '/bin/false' finished with 1 after 0.000698089599609375s
2021-02-02 18:12:09,142 test             L1090 INFO | Exit status: 1
2021-02-02 18:12:09,142 test             L1091 INFO | Duration: 0.000698089599609375
2021-02-02 18:12:09,143 stacktrace       L0039 ERROR| 
2021-02-02 18:12:09,143 stacktrace       L0041 ERROR| Reproduced traceback from: /root/rpmbuild/BUILD/avocado-84.0/avocado/core/test.py:767
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR| Traceback (most recent call last):
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR|   File "/root/rpmbuild/BUILD/avocado-84.0/avocado/core/test.py", line 1108, in _execute_cmd
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR|     result = process.run(self._command,
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR|   File "/root/rpmbuild/BUILD/avocado-84.0/avocado/utils/process.py", line 1037, in run
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command '/bin/false' failed.
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR| stdout: b''
2021-02-02 18:12:09,144 stacktrace       L0045 ERROR| stderr: b''
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR| additional_info: None
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR| 
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR| 
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR| Traceback (most recent call last):
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR|   File "/root/rpmbuild/BUILD/avocado-84.0/avocado/core/test.py", line 1155, in test
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR|     self._execute_cmd()
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR|   File "/root/rpmbuild/BUILD/avocado-84.0/avocado/core/test.py", line 1117, in _execute_cmd
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR|     raise exceptions.TestFail(test_failure)
2021-02-02 18:12:09,145 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Exited with status: '1', stdout: '' stderr: ''
2021-02-02 18:12:09,145 stacktrace       L0046 ERROR| 
2021-02-02 18:12:09,145 test             L0772 DEBUG| Local variables:
2021-02-02 18:12:09,174 test             L0775 DEBUG|  -> self <class 'avocado.core.test.SimpleTest'>: 75a71185-cd59-4a24-b7d4-d10887da3201-1-/bin/false
2021-02-02 18:12:09,175 test             L0930 ERROR| FAIL 75a71185-cd59-4a24-b7d4-d10887da3201-1-/bin/false -> TestFail: Exited with status: '1', stdout: '' stderr: ''
```
which seems like something I would expect to fail :eyes:

**Comment by beraldoleal** [comment]
are you running on a virtual env ? `make check/ develop` first ? Usually this happens when we don't have some requirements installed.

**Comment by pevogam** [comment]
> are you running on a virtual env ? `make check/ develop` first ? Usually this happens when we don't have some requirements installed.

I use an automated pipeline that roughly looks like
```
git clone https://github.com/avocado-framework/avocado --branch master
tar cvzf avocado.tar.gz --exclude='.git' avocado
dnf builddep -y ../avocado.spec
# cp to SOURCES and SPECS
rpmbuild -ba avocado.spec
```
Shouldn't any dependencies for the RPM build be specified in the SPEC file itself and thus covered by `dnf builddep`?

Running `make check` inside the cloned folder yields errors:
```
 (nrunner-interface-7/18) selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-tap: ERROR: [Errno 2] No such file or directory (avocado-runner-tap --help): 'avocado-runner-tap' (0.08 s)
 (nrunner-interface-8/18) selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-golang: STARTED
 (nrunner-interface-8/18) selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-golang: ERROR: [Errno 2] No such file or directory (avocado-runner-golang --help): 'avocado-runner-golang' (0.07 s)
 (nrunner-interface-9/18) selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-robot: STARTED
 (nrunner-interface-9/18) selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-robot: ERROR: [Errno 2] No such file or directory (avocado-runner-robot --help): 'avocado-runner-robot' (0.07 s)
 (nrunner-interface-10/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner: STARTED
 (nrunner-interface-10/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner: ERROR: [Errno 2] No such file or directory (avocado-runner capabilities): 'avocado-runner' (0.07 s)
 (nrunner-interface-11/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-noop: STARTED
 (nrunner-interface-11/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-noop: ERROR: [Errno 2] No such file or directory (avocado-runner-noop capabilities): 'avocado-runner-noop' (0.07 s)
 (nrunner-interface-12/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-exec: STARTED
 (nrunner-interface-12/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-exec: ERROR: [Errno 2] No such file or directory (avocado-runner-exec capabilities): 'avocado-runner-exec' (0.07 s)
 (nrunner-interface-13/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-exec-test: STARTED
 (nrunner-interface-13/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-exec-test: ERROR: [Errno 2] No such file or directory (avocado-runner-exec-test capabilities): 'avocado-runner-exec-test' (0.07 s)
 (nrunner-interface-14/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-python-unittest: STARTED
 (nrunner-interface-14/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-python-unittest: ERROR: [Errno 2] No such file or directory (avocado-runner-python-unittest capabilities): 'avocado-runner-python-unittest' (0.07 s)
 (nrunner-interface-15/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-avocado-instrumented: STARTED
 (nrunner-interface-15/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-avocado-instrumented: ERROR: [Errno 2] No such file or directory (avocado-runner-avocado-instrumented capabilities): 'avocado-runner-avocado-instrumented' (0.07 s)
 (nrunner-interface-16/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-tap: STARTED
 (nrunner-interface-16/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-tap: ERROR: [Errno 2] No such file or directory (avocado-runner-tap capabilities): 'avocado-runner-tap' (0.05 s)
 (nrunner-interface-17/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-golang: STARTED
 (nrunner-interface-17/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-golang: ERROR: [Errno 2] No such file or directory (avocado-runner-golang capabilities): 'avocado-runner-golang' (0.08 s)
 (nrunner-interface-18/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-robot: STARTED
 (nrunner-interface-18/18) selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-robot: ERROR: [Errno 2] No such file or directory (avocado-runner-robot capabilities): 'avocado-runner-robot' (0.07 s)
```
but I am referring specifically to the rpm build process where the unit tests should work together with satisfying the RPM build requirements if I am correct.

**Comment by beraldoleal** [comment]
in your pipeline are you using avocado.spec or python-avocado.spec? avocado.spec doesn't exists. This might be the case.

**Comment by pevogam** [comment]
> in your pipeline are you using avocado.spec or python-avocado.spec? avocado.spec doesn't exists. This might be the case.

Sorry for misleading you, the pipeline simply renames the spec with the name of the folder, the spec is otherwise the one from the master branch.

**Comment by pevogam** [comment]
I think the cause back then was in not inheriting from the avocado test class, closing this as no longer valid.
