### ISSUE TITLE
PIP + GIT based installs fail on some systems

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4588]
This is the output when deploying Avocado on a Debian system using a pip+https URL:

```
Exception:
Traceback (most recent call last):
  File "/builds/cleber.gnu/qemu/build/tests/venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2649, in version
    return self._version
  File "/builds/cleber.gnu/qemu/build/tests/venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2756, in __getattr__
    raise AttributeError(attr)
AttributeError: _version
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/cleber.gnu/qemu/build/tests/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/builds/cleber.gnu/qemu/build/tests/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 369, in run
    self._warn_about_conflicts(to_install)
  File "/builds/cleber.gnu/qemu/build/tests/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 495, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/builds/cleber.gnu/qemu/build/tests/venv/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 100, in check_install_conflicts
    would_be_installed = _simulate_installation_of(to_install, package_set)
  File "/builds/cleber.gnu/qemu/build/tests/venv/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 128, in _simulate_installation_of
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/builds/cleber.gnu/qemu/build/tests/venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2654, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file", avocado-framework [unknown version] (/tmp/pip-install-h5sjpxpb/avocado-framework/pip-egg-info))
```

The standard Debian environments are known to be minimalist when it comes to Python - they use a `python3-minimal` package by default.  Notice how `pkg_resources`, for instance, is installed as part of the venv and supposedly has version `0.0.0`.

Anyway, let's try to identify the limitations and propose a fix/workaround for the deployment on those environments.

**Comment by beraldoleal** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945214

**Comment by beraldoleal** [comment]
@clebergnu as pointed on my previous comment, this seems to be a `test-path` module issue that according to the bug report it was fixed already.

I did a run today, with podman and debian:sid and debian:bullseye, the following command did the expected:

```
pip3 install -e git+https://github.com/avocado-framework/avocado
```

I will close this for now, but, please feel free to reopen if needed.
