### ISSUE TITLE
Regression that breaks travis on master

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#472]
It looks like PR #471, which is basically PR #469 without one patch broke our selftests, and thus Travis:

```
======================================================================
FAIL: test_run_double_mplex (multiplex_tests.MultiplexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cleber/src/avocado/selftests/all/functional/avocado/multiplex_tests.py", line 104, in test_run_double_mplex
    self.run_and_check(cmd_line, expected_rc, 14 * 4)
  File "/home/cleber/src/avocado/selftests/all/functional/avocado/multiplex_tests.py", line 42, in run_and_check
    "".join(job_log_lines))
AssertionError: The multiplexed job log output has less lines than expected
19:51:28 test       L0132 INFO | START passtest.py.1
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 0.5
19:51:28 test       L0141 DEBUG|     tag = 1
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.1
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.2
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 1
19:51:28 test       L0141 DEBUG|     tag = 2
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.2
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.3
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 5
19:51:28 test       L0141 DEBUG|     tag = 3
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.3
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.4
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 10
19:51:28 test       L0141 DEBUG|     tag = 4
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.4
19:51:28 test       L0495 INFO | 


======================================================================
FAIL: test_run_mplex_doublepass (multiplex_tests.MultiplexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cleber/src/avocado/selftests/all/functional/avocado/multiplex_tests.py", line 88, in test_run_mplex_doublepass
    self.run_and_check(cmd_line, expected_rc=0, expected_lines=2 * 4 * 14)
  File "/home/cleber/src/avocado/selftests/all/functional/avocado/multiplex_tests.py", line 42, in run_and_check
    "".join(job_log_lines))
AssertionError: The multiplexed job log output has less lines than expected
19:51:28 test       L0132 INFO | START passtest.py.1
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 0.5
19:51:28 test       L0141 DEBUG|     tag = 1
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.1
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.2
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 1
19:51:28 test       L0141 DEBUG|     tag = 2
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.2
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.3
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 5
19:51:28 test       L0141 DEBUG|     tag = 3
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.3
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.4
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 10
19:51:28 test       L0141 DEBUG|     tag = 4
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.4
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.1
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 0.5
19:51:28 test       L0141 DEBUG|     tag = 1
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.1
19:51:28 test       L0495 INFO | 
19:51:28 test       L0132 INFO | START passtest.py.2
19:51:28 test       L0133 DEBUG| 
19:51:28 test       L0134 DEBUG| Test instance parameters:
19:51:28 test       L0141 DEBUG|     id = passtest
19:51:28 test       L0141 DEBUG|     sleep_length = 1
19:51:28 test       L0141 DEBUG|     tag = 2
19:51:28 test       L0142 DEBUG| 
19:51:28 test       L0145 DEBUG| Default parameters:
19:51:28 test       L0149 DEBUG| 
19:51:28 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:28 test       L0151 DEBUG| 
19:51:28 test       L0514 INFO | PASS passtest.py.2
19:51:28 test       L0495 INFO | 
19:51:29 test       L0132 INFO | START passtest.py.3
19:51:29 test       L0133 DEBUG| 
19:51:29 test       L0134 DEBUG| Test instance parameters:
19:51:29 test       L0141 DEBUG|     id = passtest
19:51:29 test       L0141 DEBUG|     sleep_length = 5
19:51:29 test       L0141 DEBUG|     tag = 3
19:51:29 test       L0142 DEBUG| 
19:51:29 test       L0145 DEBUG| Default parameters:
19:51:29 test       L0149 DEBUG| 
19:51:29 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:29 test       L0151 DEBUG| 
19:51:29 test       L0514 INFO | PASS passtest.py.3
19:51:29 test       L0495 INFO | 
19:51:29 test       L0132 INFO | START passtest.py.4
19:51:29 test       L0133 DEBUG| 
19:51:29 test       L0134 DEBUG| Test instance parameters:
19:51:29 test       L0141 DEBUG|     id = passtest
19:51:29 test       L0141 DEBUG|     sleep_length = 10
19:51:29 test       L0141 DEBUG|     tag = 4
19:51:29 test       L0142 DEBUG| 
19:51:29 test       L0145 DEBUG| Default parameters:
19:51:29 test       L0149 DEBUG| 
19:51:29 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:29 test       L0151 DEBUG| 
19:51:29 test       L0514 INFO | PASS passtest.py.4
19:51:29 test       L0495 INFO | 


======================================================================
FAIL: test_run_mplex_passtest (multiplex_tests.MultiplexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cleber/src/avocado/selftests/all/functional/avocado/multiplex_tests.py", line 83, in test_run_mplex_passtest
    self.run_and_check(cmd_line, expected_rc, 14 * 4)
  File "/home/cleber/src/avocado/selftests/all/functional/avocado/multiplex_tests.py", line 42, in run_and_check
    "".join(job_log_lines))
AssertionError: The multiplexed job log output has less lines than expected
19:51:30 test       L0132 INFO | START passtest.py.1
19:51:30 test       L0133 DEBUG| 
19:51:30 test       L0134 DEBUG| Test instance parameters:
19:51:30 test       L0141 DEBUG|     id = passtest
19:51:30 test       L0141 DEBUG|     sleep_length = 0.5
19:51:30 test       L0141 DEBUG|     tag = 1
19:51:30 test       L0142 DEBUG| 
19:51:30 test       L0145 DEBUG| Default parameters:
19:51:30 test       L0149 DEBUG| 
19:51:30 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:30 test       L0151 DEBUG| 
19:51:30 test       L0514 INFO | PASS passtest.py.1
19:51:30 test       L0495 INFO | 
19:51:30 test       L0132 INFO | START passtest.py.2
19:51:30 test       L0133 DEBUG| 
19:51:30 test       L0134 DEBUG| Test instance parameters:
19:51:30 test       L0141 DEBUG|     id = passtest
19:51:30 test       L0141 DEBUG|     sleep_length = 1
19:51:30 test       L0141 DEBUG|     tag = 2
19:51:30 test       L0142 DEBUG| 
19:51:30 test       L0145 DEBUG| Default parameters:
19:51:30 test       L0149 DEBUG| 
19:51:30 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:30 test       L0151 DEBUG| 
19:51:30 test       L0514 INFO | PASS passtest.py.2
19:51:30 test       L0495 INFO | 
19:51:30 test       L0132 INFO | START passtest.py.3
19:51:30 test       L0133 DEBUG| 
19:51:30 test       L0134 DEBUG| Test instance parameters:
19:51:30 test       L0141 DEBUG|     id = passtest
19:51:30 test       L0141 DEBUG|     sleep_length = 5
19:51:30 test       L0141 DEBUG|     tag = 3
19:51:30 test       L0142 DEBUG| 
19:51:30 test       L0145 DEBUG| Default parameters:
19:51:30 test       L0149 DEBUG| 
19:51:30 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:30 test       L0151 DEBUG| 
19:51:30 test       L0514 INFO | PASS passtest.py.3
19:51:30 test       L0495 INFO | 
19:51:30 test       L0132 INFO | START passtest.py.4
19:51:30 test       L0133 DEBUG| 
19:51:30 test       L0134 DEBUG| Test instance parameters:
19:51:30 test       L0141 DEBUG|     id = passtest
19:51:30 test       L0141 DEBUG|     sleep_length = 10
19:51:30 test       L0141 DEBUG|     tag = 4
19:51:30 test       L0142 DEBUG| 
19:51:30 test       L0145 DEBUG| Default parameters:
19:51:30 test       L0149 DEBUG| 
19:51:30 test       L0150 DEBUG| Test instance params override defaults whenever available
19:51:30 test       L0151 DEBUG| 
19:51:30 test       L0514 INFO | PASS passtest.py.4
19:51:30 test       L0495 INFO | 

```

Since that build failed while still on `git fetch`, the real regression can not be seen on Travis:

https://travis-ci.org/avocado-framework/avocado/builds/53862837

But, `make check` fails on my machine, and it will probably fail on further PRs.

@lmr and @ruda, please take a look. The fix should be really trivial (line count change).

**Comment by lmr** [comment]
Sorry guys, my bad :(
