### ISSUE TITLE
Plugin robot requirements needs updating

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#4739]
The robot plugin (`avocado-framework-plugin-robot`) has a requirement on` 'robotframework<=3.1.2'`. This version of robotframework is old and needs fixing for Python 3.10 that are in more recent versions. 

This makes the selftests to fail on Python3.10:

```
Traceback (most recent call last):
  File "/home/ana/python310/bin/avocado-runner-robot", line 33, in <module>
    sys.exit(load_entry_point('avocado-framework-plugin-robot', 'console_scripts', 'avocado-runner-robot')())
  File "/home/ana/python310/bin/avocado-runner-robot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ana/avocado/optional_plugins/robot/avocado_robot/__init__.py", line 22, in <module>
    from robot import run
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/__init__.py", line 44, in <module>
    from robot.rebot import rebot, rebot_cli
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/rebot.py", line 40, in <module>
    from robot.conf import RebotSettings
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/conf/__init__.py", line 27, in <module>
    from .settings import RobotSettings, RebotSettings
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/conf/settings.py", line 22, in <module>
    from robot.output import LOGGER, loggerhelper
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/output/__init__.py", line 22, in <module>
    from .output import Output
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/output/output.py", line 16, in <module>
    from . import pyloggingconf
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/output/pyloggingconf.py", line 19, in <module>
    from robot.utils import get_error_details, unic
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/utils/__init__.py", line 36, in <module>
    from .argumentparser import ArgumentParser, cmdline2list
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/utils/argumentparser.py", line 28, in <module>
    from .misc import plural_or_not
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/utils/misc.py", line 21, in <module>
    from .robottypes import is_integer
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/utils/robottypes.py", line 25, in <module>
    from .robottypes3 import (is_bytes, is_dict_like, is_integer, is_list_like,
  File "/home/ana/python310/lib/python3.10/site-packages/robotframework-3.1.2-py3.10.egg/robot/utils/robottypes3.py", line 16, in <module>
    from collections import Mapping, UserString
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)

```

**Comment by beraldoleal** [comment]
Hi @ana, thanks for creating this issue.

I just would like to remark that after #4389 , this is not going to be part of this repo anymore. We just need to choose to fix this before or after the split.
