### ISSUE TITLE
VersionConflict error when installing from source code.

### ISSUE THREAD

**Issue by cforno12** [avocado-framework/avocado#4989]
**Describe the bug**
Whenever I install avocado from source code I get a version conflict if the source code is a newer version. i.e. I have version 89.0 installed then I install from source, which at the time of writing this is version 90.0 and I get this backtrace:

```
Traceback (most recent call last):
  File "is_bond.py", line 1, in <module>
    from avocado.utils.network import LocalHost, NetworkInterface
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/__init__.py", line 33, in <module>
    initialize_plugins()
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/__init__.py", line 214, in initialize_plugins
    InitDispatcher().map_method('initialize')
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/dispatcher.py", line 124, in __init__
    super(InitDispatcher, self).__init__('avocado.plugins.init')
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/enabled_extension_manager.py", line 26, in __init__
    super(EnabledExtensionManager, self).__init__(namespace, invoke_kwds)
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/extension_manager.py", line 63, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (avocado-framework 90.0 (/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg), Requirement.parse('avocado-framework==89.0'))
```

**Steps to reproduce**
Install older version (89.0) from pip. Then install from source code.

**Expected behavior**
Newer version should wipe out the older version and upgrade to the new one when installing from source.

**Current behavior**
`pkg_resources.VersionConflict` error. See Traceback above.

**System information (please complete the following information):**
 - OS: `lsb_release -a`
 -# lsb_release -a
```
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le:cxx-4.1-noarch:cxx-4.1-ppc64le:desktop-4.1-noarch:desktop-4.1-ppc64le:languages-4.1-noarch:languages-4.1-ppc64le:printing-4.1-noarch:printing-4.1-ppc64le
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.5 Beta (Ootpa)
Release:	8.5
Codename:	Ootpa
```

 - Avocado version: `avocado -v`
```
Traceback (most recent call last):
  File "/usr/local/bin/avocado", line 11, in <module>
    load_entry_point('avocado-framework==90.0', 'console_scripts', 'avocado')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/__init__.py", line 33, in <module>
    initialize_plugins()
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/__init__.py", line 214, in initialize_plugins
    InitDispatcher().map_method('initialize')
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/dispatcher.py", line 124, in __init__
    super(InitDispatcher, self).__init__('avocado.plugins.init')
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/enabled_extension_manager.py", line 26, in __init__
    super(EnabledExtensionManager, self).__init__(namespace, invoke_kwds)
  File "/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/extension_manager.py", line 63, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (avocado-framework 90.0 (/root/.local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg), Requirement.parse('avocado-framework==89.0'))
```
 - Avocado installation method: pip, rpm, github ?
 From source: `python3 setup.py install`

**Additional information**
This has happened multiple times and I've often had to nuke python and pip to work around this.

**Comment by cforno12** [comment]
This can be solved through `make clean`
