### ISSUE TITLE
Avocado crashed unexpectedly: name 'static_method' is not defined

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#5105]
CI has started to fail (see log below) and I have just reproduced the problem locally. This issue comes from the lastest update of resultsdb_api to version 2.1.4. resultsdb-api is a requirements of  resultsdb.

```
$ python -m avocado run examples/tests/passtest.py 
Avocado crashed unexpectedly: name 'static_method' is not defined
You can find details in $HOME/avocado/data/crashes/avocado-traceback-2021-11-09_10:04:49-o1jt4lme.log

$ cat $HOME/avocado/data/crashes/avocado-traceback-2021-11-09_10:04:49-o1jt4lme.log
Avocado crashed:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "$HOME/avocado/avocado/__main__.py", line 10, in <module>
    sys.exit(main())
  File "$HOME/avocado/avocado/core/main.py", line 81, in main
    app = AvocadoApp()
  File "$HOME/avocado/avocado/core/app.py", line 54, in __init__
    self._load_cli_plugins()
  File "$HOME/avocado/avocado/core/app.py", line 77, in _load_cli_plugins
    self._cli_dispatcher = CLIDispatcher()
  File "$HOME/avocado/avocado/core/dispatcher.py", line 36, in __init__
    super(CLIDispatcher, self).__init__('avocado.plugins.cli')
  File "$HOME/avocado/avocado/core/enabled_extension_manager.py", line 26, in __init__
    super(EnabledExtensionManager, self).__init__(namespace, invoke_kwds)
  File "$HOME/avocado/avocado/core/extension_manager.py", line 63, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "$HOME/avocado/optional_plugins/resultsdb/avocado_resultsdb/__init__.py", line 22, in <module>
    import resultsdb_api
  File "$HOME/.local/lib/python3.10/site-packages/resultsdb_api.py", line 116, in <module>
    class ResultsDBAuth(object):
  File "$HOME/.local/lib/python3.10/site-packages/resultsdb_api.py", line 122, in ResultsDBAuth
    @static_method
NameError: name 'static_method' is not defined
```

**Comment by ana** [comment]
This is solved quickly pinning to 2.1.3, I have sent https://github.com/avocado-framework/avocado/pull/5106
We should consider updating resultsdb post-release.
