### ISSUE TITLE
Discoverer is not working with Job API

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5243]
**Describe the bug**
If you use Job API to create test suit from config without test references, but with information for discoverer, the avocado will fail. The problem is that discoverer doesn't get config from test suite, so it is using `settings.as_dict()` which doesn't have data form Job API script.

**Steps to reproduce**
```
import sys

from avocado.core.suite import TestSuite
from avocado.core.job import Job

config = {'vt.config': /var/lib/avocado/data/avocado-vt/backends/qemu/cfg/example.cfg}
suite = [TestSuite.from_config(name='vt-test', config=config)]

with Job(config, suite) as j:
    sys.exit(j.run())
```
```
python test.py
```

**Expected behavior**
```
python test.py
JOB ID     : e504484ac5e3e40efad1296db2b72ac4eeb29a04
JOB LOG    : /home/jariche/avocado/job-results/job-2022-01-25T01.08-e504484/job.log
 (1/1) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.boot: STARTED
 (1/1) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.boot: PASS (92.17 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/jariche/avocado/job-results/job-2022-01-25T01.08-e504484/results.html
JOB TIME   : 93.89 s
```

**Current behavior**
```
python test.py 
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    suite = [TestSuite.from_config(name='migration', config=config)]
  File "/usr/local/lib/python3.6/site-packages/avocado/core/suite.py", line 369, in from_config
    suite = cls._from_config_with_resolver(config, name)
  File "/usr/local/lib/python3.6/site-packages/avocado/core/suite.py", line 199, in _from_config_with_resolver
    config=config)
  File "/usr/local/lib/python3.6/site-packages/avocado/core/resolver.py", line 225, in resolve
    resolutions.extend(discoverer.discover())
  File "/usr/local/lib/python3.6/site-packages/avocado/core/resolver.py", line 145, in discover
    for result in results:
```

**Additional information**
For reproduce this you need avocado-vt because avocado itself doesn't use discoverer.

**Comment by richtja** [comment]
After the investigation, this wasn't a problem of avocado, the problem was only on the avocado-vt side, and it was fixed in [#3340](https://github.com/avocado-framework/avocado-vt/pull/3340)
