### ISSUE TITLE
avocado 95.0 fails with"avocado run: error: unrecognized arguments: --mux-yaml" 

### ISSUE THREAD

**Issue by hxlpub** [avocado-framework/avocado#5319]
avocado 95.0 fails with"avocado run: error: unrecognized arguments: --mux-yaml" ,
the details as followed:Failed to load plugin from module "avocado_varianter_yaml_to_mux.varianter_yaml_to_mux": ModuleNotFoundError("No module named 'avocado_varianter_yaml_to_mux.varianter_yaml_to_mux'") :   File "/usr/local/lib/python3.9/site-packages/avocado_framework-95.0-py3.9.egg/avocado/core/extension_manager.py", line 63, in __init__     plugin = ep.load()   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load     return self.resolve()   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve     module = __import__(self.module_name, fromlist=['__name__'], level=0)  avocado run: error: unrecognized arguments: --mux-yaml
i've already installed plugin avocado_varianter_yaml_to_mux

**Comment by hxlpub** [comment]
then i tried import avocado_varianter_yaml_to_mux.varianter_yaml_to_mux
it shows Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'avocado_varianter_yaml_to_mux.varianter_yaml_to_mux'

**Comment by ana** [comment]
hi @hxlpub 
Thanks for your bug report!
Could you please provide more information about your problem? I'll copy the question template in another comment.

Right now, I can't reproduce your problem:

```
$ python3
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import avocado_varianter_yaml_to_mux.varianter_yaml_to_mux
>>> 
```
or

```
$  avocado run examples/tests/passtest.py --mux-yaml examples/yaml_to_mux/hw/hw.yaml
+çJOB ID     : 92fe9d5858de2cd05761f4fd38aa8f7711b755b7
JOB LOG    : /home/a/avocado/job-results/job-2022-04-08T11.39-92fe9d5/job.log
 (3/6) examples/tests/passtest.py:PassTest.test;run-cpu-amd-disk-scsi-b3e2: STARTED
 (1/6) examples/tests/passtest.py:PassTest.test;run-cpu-intel-disk-scsi-d340: STARTED
 (5/6) examples/tests/passtest.py:PassTest.test;run-cpu-arm-disk-scsi-0ceb: STARTED
 (4/6) examples/tests/passtest.py:PassTest.test;run-cpu-amd-disk-virtio-9d9f: STARTED
 (2/6) examples/tests/passtest.py:PassTest.test;run-cpu-intel-disk-virtio-40ba: STARTED
 (6/6) examples/tests/passtest.py:PassTest.test;run-cpu-arm-disk-virtio-0254: STARTED
 (3/6) examples/tests/passtest.py:PassTest.test;run-cpu-amd-disk-scsi-b3e2: PASS (0.01 s)
 (1/6) examples/tests/passtest.py:PassTest.test;run-cpu-intel-disk-scsi-d340: PASS (0.01 s)
 (5/6) examples/tests/passtest.py:PassTest.test;run-cpu-arm-disk-scsi-0ceb: PASS (0.01 s)
 (4/6) examples/tests/passtest.py:PassTest.test;run-cpu-amd-disk-virtio-9d9f: PASS (0.01 s)
 (2/6) examples/tests/passtest.py:PassTest.test;run-cpu-intel-disk-virtio-40ba: PASS (0.01 s)
 (6/6) examples/tests/passtest.py:PassTest.test;run-cpu-arm-disk-virtio-0254: PASS (0.01 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/a/avocado/job-results/job-2022-04-08T11.39-92fe9d5/results.html
JOB TIME   : 1.29 s

```

**Comment by ana** [comment]
@@hxlpub

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce**
Steps to reproduce the behavior with a reproducible whenever possible.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Current behavior**
What you are getting?

**System information (please complete the following information):**
 - OS: `lsb_release -a`
 - Avocado version: `avocado -v`
 - Avocado installation method: pip, rpm, github ?

**Additional information**
Add any other information about the problem here. Test details can be added here.

**Comment by hxlpub** [comment]
Thanks for your reply!
The problem is (i do not know if it is a bug or not ):
 i installed avocado and its plugins avocado_varianter_yaml_to_mux  by rpms
then   import avocado_varianter_yaml_to_mux.varianter_yaml_to_mux
it happened :
>>> import avocado_varianter_yaml_to_mux.varianter_yaml_to_mux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'avocado_varianter_yaml_to_mux.varianter_yaml_to_mux'

OS: Stream-9-Beta2
Avocado version: Avocado 82.0
Avocado installation method: rpms

**Comment by ana** [comment]
@hxlpub 
Could you also provide the output of:

`rpm -qa | grep avocado
`

Thanks

**Comment by hxlpub** [comment]
@ana 
`[root@hik2 opt]# rpm -qa |grep avocado
python-avocado-common-82.0-2.el9.noarch
python3-avocado-82.0-2.el9.noarch
python3-avocado-plugins-varianter-yaml-to-mux-82.0-2.el9.noarch
`

**Comment by hxlpub** [comment]
@ana 
i do not think it's a bug ...more likely to  be something about my env

**Comment by hxlpub** [comment]
@ana 
i have a new problem happend on my another posix:
`cd optional_plugins/varianter_yaml_to_mux ;python3.9 setup.py install;avocado plugins
 Plugins that generate test variants (varianter):
    dict_variants Python Dictionary based varianter
    json_variants JSON serialized based Varianter
`
no yaml_to_mux installed ,i hope for your reply
