### ISSUE TITLE
Avocado crashes when the suite name contains slash

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5365]
**Steps to reproduce**
Job API:
```
import sys

from avocado.core.job import Job
from avocado.core.suite import TestSuite
from avocado.core.nrunner.runnable import Runnable


test = Runnable('exec-test', '/bin/true')
suite = TestSuite('suite/pom', tests=[test])

with Job({}, [suite]) as j:
    sys.exit(j.run())

```
run $ python /tmp/suite.py

**Expected behavior**
```
$ python /tmp/suite.py 
JOB ID     : 46b10715a349fd75ab01336cb98fd08f92876fdf
JOB LOG    : /home/jarichte/avocado/job-results/job-2022-04-29T15.21-46b1071/job.log
 (suite\pom-1/1) /bin/true: STARTED
 (suite\pom-1/1) /bin/true: PASS (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/jarichte/avocado/job-results/job-2022-04-29T15.21-46b1071/results.html
JOB TIME   : 0.90 s
```

**Current behavior**
```
$ python /tmp/suite.py 
JOB ID     : a8b564c41907f0e9d8f4becfa5a14b1ce24df3b3
JOB LOG    : /home/jarichte/avocado/job-results/job-2022-04-29T15.17-a8b564c/job.log

Avocado crashed: FileNotFoundError: [Errno 2] No such file or directory: '/home/jarichte/avocado/job-results/job-2022-04-29T15.17-a8b564c/jobdata/variants-1-suite/pom.json'
Traceback (most recent call last):

  File "/home/jarichte/Avocado/avocado/avocado/core/job.py", line 605, in run_tests
    jobdata.record(self, sys.argv)

  File "/home/jarichte/Avocado/avocado/avocado/core/jobdata.py", line 81, in record
    record_suite_variant(path_suite_variant, suite)

  File "/home/jarichte/Avocado/avocado/avocado/core/jobdata.py", line 44, in record_suite_variant
    with open(path_variants, 'w', encoding='utf-8') as variants_file:

FileNotFoundError: [Errno 2] No such file or directory: '/home/jarichte/avocado/job-results/job-2022-04-29T15.17-a8b564c/jobdata/variants-1-suite/pom.json'

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

**System information (please complete the following information):**
 - OS: 
 LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 35 (Thirty Five)
Release:	35
Codename:	ThirtyFive
 - Avocado version: master
 - Avocado installation method: github

**Comment by richtja** [comment]
This was fixed in https://github.com/avocado-framework/avocado/pull/5366
