### ISSUE TITLE
Unknown top level 'scripts' for avocado-external-runner entry point

### ISSUE THREAD

**Issue by Apteryks** [avocado-framework/avocado#5370]
Hi,

The avocado-external-runner entrypoint script defined at:
https://github.com/avocado-framework/avocado/blob/32626243d969ad4bc62a26e006e9e0e43e738411/setup.py#L325 is specified as: `scripts.external_runner:main`, but the installed Avocado package doesn't provide any 'scripts' package at the top level.  Is this expected?

There's a sanity check phase in Guix that tests that each entry point can be loaded, and it fails like:
```
...trying to load endpoint console_scripts avocado-external-runner: ERROR:
Traceback (most recent call last):
  File "/gnu/store/35ix1m6m8a5s21j02ajhdyqxb2xkshfb-sanity-check.py", line 85, in <module>
    ep.load()
  File "/gnu/store/b6j1qw1a5rkbfvcy7lc9fm95abbzpa4x-python-3.9.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/gnu/store/b6j1qw1a5rkbfvcy7lc9fm95abbzpa4x-python-3.9.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'scripts'
```

Avocado 96.0, Python 3.9.9.

**Comment by beraldoleal** [comment]
Hi @Apteryks thanks for reporting this. It looks like a valid bug.

**Comment by clebergnu** [comment]
Looks like this is an easy fix:

```diff
diff --git a/scripts/external_runner.py b/scripts/external_runner.py
index 50b8ca29f..441966e22 100755
--- a/scripts/external_runner.py
+++ b/scripts/external_runner.py
@@ -29,7 +29,7 @@ import argparse
 import sys
 
 from avocado.core.job import Job
-from avocado.core.nrunner import Runnable
+from avocado.core.nrunner.runnable import Runnable
 from avocado.core.suite import TestSuite
 from avocado.utils.path import find_command
```
