### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'config'

### ISSUE THREAD

**Issue by RanjithaKamath** [avocado-framework/avocado#5392]
We are using avocado for the first time and receiving the following error on running "avocado plugins" cmd

/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/data/crashes/avocado-traceback-2022-06-02_13:10:29-salkjjgc.log
Avocado crashed:
Traceback (most recent call last):
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/bin/avocado", line 8, in <module>
sys.exit(main())
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/lib/python3.8/site-packages/avocado/core/main.py", line 76, in main
return app.run()
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/lib/python3.8/site-packages/avocado/core/app.py", line 112, in run
return method(self.parser.config)
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/lib/python3.8/site-packages/avocado/plugins/plugins.py", line 46, in run
(dispatcher.ResultEventsDispatcher(config),
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/lib/python3.8/site-packages/avocado/core/dispatcher.py", line 74, in __init__
super(ResultEventsDispatcher, self).__init__(
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/lib/python3.8/site-packages/avocado/core/enabled_extension_manager.py", line 26, in __init__
super(EnabledExtensionManager, self).__init__(namespace, invoke_kwds)
File "/c/Users/jayeshbh/npcit_integration/npcit/venv_python3/lib/python3.8/site-packages/avocado/core/extension_manager.py", line 63, in __init__
obj = plugin(**invoke_kwds)
TypeError: __init__() got an unexpected keyword argument 'config'

**Comment by RanjithaKamath** [comment]
I have a script which used to run on python 2 and now am told to convert to python3.And this script uses avocado framework with some plugins. The earlier version of avocado used was 59 with python2 and currently i have upgraded it to 82.0 with python3.

We have created test scripts in python and the python file path has been given inside the yaml file  as test reference.
And below command is being used to run the avocado test case.
**command**=avocado run --show-job-log --job-results-dir {avocado_job_dir} --loaders yaml_testsuite -- {yaml_file_name}

Below are the versions being used to run the script
avocado-framework==82.0
avocado-framework-my-journal @ file:///c/Users/kamath/Documents/Projects/PCIT_python3/npcit/npcit_tests_status_plugin
avocado-framework-plugin-loader-yaml==82.0
avocado-framework-plugin-result-html==82.0
avocado-framework-plugin-varianter-yaml-to-mux==82.0


But unfortunately i am not to even run avocado plugins command to check the plugins installed and getting following errors
 **avocado plugins**
Avocado crashed unexpectedly: __init__() got an unexpected keyword argument 'config'
You can find details in /var/lib/avocado/data/crashes/avocado-traceback-2022-06-09_16:45:31-2edccf1v.log

Avocado crashed:
Traceback (most recent call last):
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/bin/avocado", line 8, in <module>
    sys.exit(main())
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/lib/python3.8/site-packages/avocado/core/main.py", line 76, in main
    return app.run()
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/lib/python3.8/site-packages/avocado/core/app.py", line 112, in run
    return method(self.parser.config)
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/lib/python3.8/site-packages/avocado/plugins/plugins.py", line 46, in run
    (dispatcher.ResultEventsDispatcher(config),
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/lib/python3.8/site-packages/avocado/core/dispatcher.py", line 74, in __init__
    super(ResultEventsDispatcher, self).__init__(
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/lib/python3.8/site-packages/avocado/core/enabled_extension_manager.py", line 26, in __init__
    super(EnabledExtensionManager, self).__init__(namespace, invoke_kwds)
  File "/c/Users/kamath/Documents/Projects/PCIT_python3/venv_py3/lib/python3.8/site-packages/avocado/core/extension_manager.py", line 63, in __init__
    obj = plugin(**invoke_kwds)
TypeError: __init__() got an unexpected keyword argument 'config'

**Comment by richtja** [comment]
Hi @RanjithaKamath I am so sorry for the late reply, and I am not sure if this is still relevant for you, but can you tell me how you install the avocado 82, because I wasn't able to reproduce this issue. I did this:

```
$ pip install avocado-framework==82 avocado-framework-plugin-loader-yaml==82 avocado-framework-plugin-result-html==82 avocado-framework-plugin-varianter-yaml-to-mux==82

...

$ avocado -v
Avocado 82.0

$ avocad plugins
 Plugins that always need to be initialized (init): 
jobscripts    Jobscripts plugin initialization
json_variants JSON serialized based varianter initialization
jsonresult    JSON job result plugin initialization
nrunner       nrunner initialization
podman        Podman (container) based spawner initialization
run           Initializes the run options
sysinfo       Initializes sysinfo settings
tap           TAP - Test Anything Protocol - result plugin initilization
xunit         xUnit job result initialization
yaml_to_mux   YamlToMux initialization plugin

Plugins that add new commands (cli.cmd):
assets    Manage assets
config    Shows avocado config keys
diff      Shows the difference between 2 jobs.
distro    Shows detected Linux distribution
exec-path Returns path to avocado bash libraries and exits.
jobs      Manage Avocado jobs
list      List available tests
plugins   Displays plugin information
replay    Runs a new job using a previous job as its configuration
run       Runs one or more tests (native test, test alias, binary or script)
sysinfo   Collect system information
variants  Tool to analyze and visualize test variants and params
vmimage   Provides VM images acquired from official repositories

Plugins that add new options to commands (cli):
html          HTML job report options for 'run' subcommand
journal       Journal options for the 'run' subcommand
json          JSON output options for 'run' command
json_variants JSON serialized based Varianter options for the 'run' subcommand
loader_yaml   YAML test loader options for the 'run' subcommand
nrunner       nrunner command line options for "run"
replay_legacy Replay options for 'run' subcommand
tap           TAP - Test Anything Protocol results
wrapper       Implements the '--wrapper' flag for the 'run' subcommand
xunit         xUnit output options
yaml_to_mux   YamlToMux options for the 'run' subcommand
zip_archive   Result archive (ZIP) support to run command

Plugins that run before/after the execution of jobs (job.prepost):
human       Human Interface UI
jobscripts  Runs scripts before/after the job is run
merge_files Merge of equal expected files
teststmpdir Creates a temporary directory for tests consumption

Plugins that generate job result in different formats (result):
html        HTML result support
json        JSON result support
xunit       XUnit result support
zip_archive Result archive (ZIP) support

Plugins that generate job result based on job/test events (result_events):
fetchasset Fetch assets before the test run
human      Human Interface UI
journal    Journal event based results implementation
sysinfo    Collects system information before/after the job is run
tap        TAP - Test Anything Protocol results

Plugins that generate test variants (varianter): 
dict_variants Python Dictionary based varianter
json_variants JSON serialized based Varianter
yaml_to_mux   Multiplexer plugin to parse yaml files to params

Plugins that resolve test references (resolver): 
avocado-instrumented Test resolver for Avocado Instrumented tests
exec-test            Test resolver for executable files to be handled as tests
python-unittest      Test resolver for Python Unittests
tap                  Test resolver for executable files to be handled as tests

Plugins that run test suites on a job (runners): 
nrunner nrunner based implementation of job compliant runner
runner  The conventional test runner

Plugins that spawn tasks and know about their status (spawner): 
podman  Podman (container) based spawner
process Process based spawner
