### ISSUE TITLE
Task timeout handling broken

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5413]
**Describe the bug**
When enforcing a task's timeout, Avocado will crash. Apparently, this happens when more tasks are running than CPUs available.

**Steps to reproduce**
Create a configuration with the following content:

```
[task.timeout]
running = 1
```

And run two (or more) tests that will take longer than the task "running" timeout:

```
$ taskset -c 0 avocado --config=/tmp/c run examples/tests/sleeptenmin.py{,}
```

**Expected behavior**
A proper handling of the interrupted tasks and their messages:

```
JOB ID     : 6aa2e46be6be1c11ba1d2bc35c07a8329092cb1d
JOB LOG    : /home/cleber/avocado/job-results/job-2022-06-23T18.27-6aa2e46/job.log
 (1/2) examples/tests/sleeptenmin.py:SleepTenMin.test: STARTED
 (2/2) examples/tests/sleeptenmin.py:SleepTenMin.test: STARTED
 (1/2) examples/tests/sleeptenmin.py:SleepTenMin.test:  INTERRUPTED: Test interrupted: Timeout reached (0.28 s)
 (2/2) examples/tests/sleeptenmin.py:SleepTenMin.test:  INTERRUPTED: Test interrupted: Timeout reached (0.27 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 2 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2022-06-23T18.27-6aa2e46/results.html
JOB TIME   : 1.73 s
```

**Current behavior**
```
$ taskset -c 0 avocado --config=/tmp/c run examples/tests/sleeptenmin.py{,}
JOB ID     : 028a6b2e4a32b6009aa4b8698e4d0943471dda08
JOB LOG    : /home/cleber/avocado/job-results/job-2022-06-23T18.23-028a6b2/job.log
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Runner._update_status() done, defined at /home/cleber/src/avocado/avocado/avocado/plugins/runner_nrunner.py:206> exception=KeyError('time_start')>
Traceback (most recent call last):
  File "/home/cleber/src/avocado/avocado/avocado/plugins/runner_nrunner.py", line 221, in _update_status
    message_handler.process_message(message, task, job)
  File "/home/cleber/src/avocado/avocado/avocado/core/messages.py", line 68, in process_message
    handler.process_message(message, task, job)
  File "/home/cleber/src/avocado/avocado/avocado/core/messages.py", line 55, in process_message
    self.handle(message, task, job)
  File "/home/cleber/src/avocado/avocado/avocado/core/messages.py", line 158, in handle
    time_start = message['time_start']
KeyError: 'time_start'
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2022-06-23T18.23-028a6b2/results.html
JOB TIME   : 1.90 s
```

**System information (please complete the following information):**
 - OS: ```LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 36 (Thirty Six)
Release:	36
Codename:	ThirtySix```
 - Avocado version: c93f18e50546a0f2bf7dbf8c19b89fb122af059f
 - Avocado installation method: git

**Comment by clebergnu** [comment]
This was bisected to:

```
612b630c33d061f5cfb8848320230a2f4602c89b is the first bad commit
commit 612b630c33d061f5cfb8848320230a2f4602c89b
Merge: 17ebff971 c27203ae1
Author: Beraldo Leal <bleal@redhat.com>
Date:   Wed Jun 15 11:38:52 2022 -0300

    Merge pull request #5382 from richtja/runnable_config_v3
    
    Runnable with default config [v3]

 avocado/core/nrunner/runnable.py     | 170 ++++++++++++++++++++++++++++-------
 avocado/core/nrunner/runner.py       |   2 +-
 avocado/core/nrunner/task.py         |   2 +-
 avocado/plugins/runner_nrunner.py    |  13 +--
 avocado/plugins/spawners/podman.py   |   2 +-
 avocado/plugins/spawners/process.py  |   4 +-
 selftests/functional/test_nrunner.py |  12 +++
 selftests/unit/test_nrunner.py       |  43 ++++-----
 8 files changed, 178 insertions(+), 70 deletions(-)
bisect found first bad commit
```

By using:

```
git bisect run taskset -c 0 avocado run selftests/functional/test_task_timeout.py:TaskTimeOutTest.test_sleep_longer_timeout{,,,}
```
