### ISSUE TITLE
The `test_podman.py:PodmanTest.test_container_info` failing on CI

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5427]
**Describe the bug**
Sometimes the `functional-parallel-226-selftests/functional/utils/test_podman.py:PodmanTest.test_container_info` test will finish with ERROR on CI. It is happening on all python version, but the occasion seems to be random.

**Current behavior**
Error message:

```
Log file "debug.log" content for test "functional-parallel-226-selftests/functional/utils/test_podman.py:PodmanTest.test_container_info" (ERROR):
[stdlog] 2022-07-11 09:49:57,488 avocado.test INFO | INIT 1-selftests/functional/utils/test_podman.py:PodmanTest.test_container_info
selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: ERROR
[stdlog] 2022-07-11 09:49:57,490 avocado.test DEBUG| PARAMS (key=timeout, path=*, default=None) => None
[stdlog] 2022-07-11 09:49:57,491 avocado.test DEBUG| Test metadata:
[stdlog] 2022-07-11 09:49:57,491 avocado.test DEBUG|   filename: /home/runner/work/avocado/avocado/selftests/functional/utils/test_podman.py
[stdlog] 2022-07-11 09:49:57,491 avocado.test DEBUG|   teststmpdir: /tmp/avocado__dfylp_i
[stdlog] 2022-07-11 09:49:57,492 avocado.test INFO | START 1-selftests/functional/utils/test_podman.py:PodmanTest.test_container_info
[stdlog] 2022-07-11 09:49:57,493 avocado.utils.podman DEBUG| Executing ('create', 'fedora:34', '/bin/bash')
[stdlog] 2022-07-11 09:50:03,357 avocado.utils.podman DEBUG| Return code: 0
[stdlog] 2022-07-11 09:50:03,358 avocado.utils.podman DEBUG| Stdout: 40dd8036109a09b1689a8df6f194b6d3fcb02b977aa0dfa155dd42868729d316
[stdlog] 2022-07-11 09:50:03,358 avocado.utils.podman DEBUG| Stderr: Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
[stdlog] Trying to pull registry.fedoraproject.org/fedora:34...
[stdlog] Getting image source signatures
[stdlog] Copying blob sha256:878a8677dead0e70225056b0624c816077ad74129e66097e7bcbcbea27842778
[stdlog] Copying blob sha256:878a8677dead0e70225056b0624c816077ad74129e66097e7bcbcbea27842778
[stdlog] Copying config sha256:307241a058e3f161a7772c8587238f2e1c093c207ea9afaafff3d1a4d1deaf0e
[stdlog] Writing manifest to image destination
[stdlog] Storing signatures
[stdlog] 2022-07-11 09:50:03,358 avocado.utils.podman DEBUG| Executing ('ps', '--all', '--format=json')
[stdlog] 2022-07-11 09:50:03,576 avocado.utils.podman DEBUG| Return code: 125
[stdlog] 2022-07-11 09:50:03,577 avocado.utils.podman DEBUG| Stdout: 
[stdlog] 2022-07-11 09:50:03,577 avocado.utils.podman DEBUG| Stderr: Error: container 2ed4b513ecbb66133d0d1d98ca3383e7c3ab571b9d852e640f980e8f481736f7 does not exist in database: no such container
[stdlog] 2022-07-11 09:50:03,577 avocado.utils.podman ERROR| Could not execute the command: 125:b'Error: container 2ed4b513ecbb66133d0d1d98ca3383e7c3ab571b9d852e640f980e8f481736f7 does not exist in database: no such container\n'.
[stdlog] 2022-07-11 09:50:03,577 avocado.test ERROR| 
[stdlog] 2022-07-11 09:50:03,577 avocado.test ERROR| Reproduced traceback from: /home/runner/work/avocado/avocado/avocado/core/test.py:630
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/utils/podman.py", line 132, in get_container_info
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR|     _, stdout, _ = await self.execute("ps", "--all", "--format=json")
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/utils/podman.py", line 71, in execute
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR|     raise PodmanException(msg)
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR| avocado.utils.podman.PodmanException: Could not execute the command: 125:b'Error: container 2ed4b513ecbb66133d0d1d98ca3383e7c3ab571b9d852e640f980e8f481736f7 does not exist in database: no such container\n'.
[stdlog] 2022-07-11 09:50:03,578 avocado.test ERROR| 
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR| The above exception was the direct cause of the following exception:
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR| 
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR|   File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR|     return future.result()
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/selftests/functional/utils/test_podman.py", line 23, in test_container_info
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR|     result = await podman.get_container_info(container_id)
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/utils/podman.py", line 136, in get_container_info
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR|     ) from ex
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR| avocado.utils.podman.PodmanException: Failed getting information about container: 40dd8036109a09b1689a8df6f194b6d3fcb02b977aa0dfa155dd42868729d316.
[stdlog] 2022-07-11 09:50:03,579 avocado.test ERROR| 
[stdlog] 2022-07-11 09:50:03,579 avocado.test DEBUG| Local variables:
[stdlog] 2022-07-11 09:50:03,605 avocado.test DEBUG|  -> new_task <class 'bool'>: True
[stdlog] 2022-07-11 09:50:03,605 avocado.test DEBUG|  -> future <class '_asyncio.Task'>: <Task finished coro=<PodmanTest.test_container_info() done, defined at /home/runner/work/avocado/avocado/selftests/functional/utils/test_podman.py:15> exception=PodmanException('Failed getting information about container: 40dd8036109a09b1689a8df6f194b6d3fcb02b977aa0dfa155dd42868729d316.',)>
[stdlog] 2022-07-11 09:50:03,605 avocado.test DEBUG|  -> self <class 'asyncio.unix_events._UnixSelectorEventLoop'>: <_UnixSelectorEventLoop running=False closed=False debug=False>
[stdlog] 2022-07-11 09:50:03,605 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-07-11 09:50:03,605 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/utils/podman.py", line 132, in get_container_info
[stdlog]     _, stdout, _ = await self.execute("ps", "--all", "--format=json")
[stdlog] 2022-07-11 09:50:03,605 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/utils/podman.py", line 71, in execute
[stdlog]     raise PodmanException(msg)
[stdlog] 2022-07-11 09:50:03,605 avocado.test ERROR| avocado.utils.podman.PodmanException: Could not execute the command: 125:b'Error: container 2ed4b513ecbb66133d0d1d98ca3383e7c3ab571b9d852e640f980e8f481736f7 does not exist in database: no such container\n'.
[stdlog] 2022-07-11 09:50:03,605 avocado.test ERROR| 
[stdlog] The above exception was the direct cause of the following exception:
[stdlog] 
[stdlog] 2022-07-11 09:50:03,605 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/core/test.py", line 638, in _run_test
[stdlog]     raise details
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/core/test.py", line 623, in _run_test
[stdlog]     loop.run_until_complete(testMethod())
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR|   File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
[stdlog]     return future.result()
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/selftests/functional/utils/test_podman.py", line 23, in test_container_info
[stdlog]     result = await podman.get_container_info(container_id)
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR|   File "/home/runner/work/avocado/avocado/avocado/utils/podman.py", line 136, in get_container_info
[stdlog]     ) from ex
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR| avocado.utils.podman.PodmanException: Failed getting information about container: 40dd8036109a09b1689a8df6f194b6d3fcb02b977aa0dfa155dd42868729d316.
[stdlog] 2022-07-11 09:50:03,606 avocado.test ERROR| ERROR 1-selftests/functional/utils/test_podman.py:PodmanTest.test_container_info -> PodmanException: Failed getting information about container: 40dd8036109a09b1689a8df6f194b6d3fcb02b977aa0dfa155dd42868729d316.
[stdlog] 2022-07-11 09:50:03,606 avocado.test INFO |
```

**Additional information**
This test was introduced in #5400, and it might be connected with #5421

**Comment by clebergnu** [comment]
Under Ubuntu 20.04 with podman version 3.4.2 from [this repo](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/), it's not hard to reproduce it:

```
avocado run selftests/functional/utils/test_podman.py{,,,,,,,,,}
JOB ID     : 1a8cc6f1de52900bdcd92802bbd6a19e84c450b6
JOB LOG    : /home/cleber/avocado/job-results/job-2022-07-13T19.06-1a8cc6f/job.log
 (02/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (03/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (01/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (04/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (01/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.37 s)
 (03/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.47 s)
 (02/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.78 s)
 (05/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (04/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.89 s)
 (06/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (07/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (05/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.45 s)
 (08/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (06/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: ERROR: Failed getting information about container: bf0fb904cf91270e6a7ff029d92ff85e5259d47a19428f912c7006447f228c7d. (0.28 s)
 (07/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.35 s)
 (09/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (10/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (11/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (08/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.79 s)
 (09/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.42 s)
 (11/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.35 s)
 (12/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (10/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.58 s)
 (13/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (14/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (13/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.38 s)
 (15/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (12/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.64 s)
 (14/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.58 s)
 (15/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.37 s)
 (16/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (17/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (18/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (19/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (17/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.35 s)
 (16/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.64 s)
 (19/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.35 s)
 (20/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (18/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: ERROR: Failed getting information about container: 8c417305a27be1bccc85047acc9aac6dab1122584a06388a44b52c6ea82e6bcc. (0.40 s)
 (20/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.67 s)
RESULTS    : PASS 18 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2022-07-13T19.06-1a8cc6f/results.html
JOB TIME   : 7.25 s

Test summary:
selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: ERROR
selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: ERROR
```

Under no circumstances I was able to reproce this on Fedora 36 with podman 4.1.1.  IMO, this is a podman 3.4.2 locking/database issue that gets manifested with the parallel execution of downloads and retrieval of container and image information.

**Comment by clebergnu** [comment]
Also under the Ubuntu environment, without parallel execution, no failures can be seen:

```
avocado run --nrunner-max-parallel-tasks=1 selftests/functional/utils/test_podman.py{,,,,,,,,,}
JOB ID     : 817c379452e520f7d8ef295ac2bf0c3f66ea7553
JOB LOG    : /home/cleber/avocado/job-results/job-2022-07-13T19.11-817c379/job.log
 (01/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (01/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (02/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (02/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.65 s)
 (03/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (03/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (04/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (04/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.64 s)
 (05/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (05/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (06/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (06/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.61 s)
 (07/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (07/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.35 s)
 (08/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (08/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.64 s)
 (09/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (09/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (10/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (10/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.62 s)
 (11/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (11/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (12/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (12/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.67 s)
 (13/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (13/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (14/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (14/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.67 s)
 (15/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (15/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.35 s)
 (16/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (16/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.65 s)
 (17/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (17/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.24 s)
 (18/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (18/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.65 s)
 (19/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: STARTED
 (19/20) selftests/functional/utils/test_podman.py:PodmanTest.test_python_version: PASS (0.25 s)
 (20/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: STARTED
 (20/20) selftests/functional/utils/test_podman.py:PodmanTest.test_container_info: PASS (0.62 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2022-07-13T19.11-817c379/results.html
JOB TIME   : 20.83 s
```
