### ISSUE TITLE
OSError: AF_UNIX path too long on Darwin

### ISSUE THREAD

**Issue by philmd** [avocado-framework/avocado#5519]
**Describe the bug**
`OSError: AF_UNIX path too long`

**Steps to reproduce**
- use a Darwin host
- build QEMU (I am using *v7.2.0-rc0*)
- run `make check-avocado`

**Expected behavior**
Tests running similarly to Linux.

**Current behavior**
```
23:49:22 INFO | Asset not in cache, fetching it.
23:49:22 INFO | Fetching https://fileserver.linaro.org/s/2c7ERpPBiwHg5jc/download?path=/&files=7088.tar.xz -> /Users/philmd/avocado/data/cache/by_location/dcfdce9869111dbfdbf020e483e363aa1d7db764/download.zwj_xjl5
23:49:29 DEBUG| QEMUMachine "default" created
23:49:29 DEBUG| QEMUMachine "default" temp_dir: /var/folders/yj/r7khncsj4d77k04ybz9lw4tm0000gn/T/tmpelgxvuab/test-results/tmp_dirgfithciy/1-Mps2Machine.test_zephyr_2/qemu-machine-gmchw0xu
23:49:29 DEBUG| QEMUMachine "default" log_dir: /var/folders/yj/r7khncsj4d77k04ybz9lw4tm0000gn/T/tmpelgxvuab/test-results/1-Mps2Machine.test_zephyr_2
23:49:29 ERROR| Failed to establish connection: OSError: AF_UNIX path too long
23:49:29 ERROR| 
23:49:29 ERROR| Reproduced traceback from: /builddir/tests/venv/lib/python3.10/site-packages/avocado/core/test.py:772
23:49:29 ERROR| Traceback (most recent call last):
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/qmp/protocol.py", line 424, in _session_guard
23:49:29 ERROR|     await coro
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/qmp/protocol.py", line 582, in _do_start_server
23:49:29 ERROR|     self._server = await coro
23:49:29 ERROR|   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 114, in start_unix_server
23:49:29 ERROR|     return await loop.create_unix_server(factory, path, **kwds)
23:49:29 ERROR|   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 307, in create_unix_server
23:49:29 ERROR|     sock.bind(path)
23:49:29 ERROR| OSError: AF_UNIX path too long
23:49:29 ERROR| 
23:49:29 ERROR| The above exception was the direct cause of the following exception:
23:49:29 ERROR| 
23:49:29 ERROR| Traceback (most recent call last):
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/machine/machine.py", line 423, in launch
23:49:29 ERROR|     self._launch()
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/machine/machine.py", line 450, in _launch
23:49:29 ERROR|     self._pre_launch()
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/machine/machine.py", line 342, in _pre_launch
23:49:29 ERROR|     self._qmp_connection = QEMUMonitorProtocol(
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/qmp/legacy.py", line 87, in __init__
23:49:29 ERROR|     self._sync(self._qmp.start_server(self._address))
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/qmp/legacy.py", line 94, in _sync
23:49:29 ERROR|     return self._aloop.run_until_complete(
23:49:29 ERROR|   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
23:49:29 ERROR|     return future.result()
23:49:29 ERROR|   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
23:49:29 ERROR|     return await fut
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/qmp/protocol.py", line 323, in start_server
23:49:29 ERROR|     await self._session_guard(
23:49:29 ERROR|   File "/sourcedir/qemu/python/qemu/qmp/protocol.py", line 455, in _session_guard
23:49:29 ERROR|     raise ConnectError(emsg, err) from err
23:49:29 ERROR| qemu.qmp.protocol.ConnectError: Failed to establish connection: AF_UNIX path too long
```

**System information (please complete the following information):**
 - OS: `lsb_release -a`
```
-bash: lsb_release: command not found
```

 - Avocado version: `avocado -v`
```
Avocado 88.1
```

 - Avocado installation method: pip, rpm, github ?
```
pip
```

**Additional information**

Running from QEMU `make check-avocado`

**Comment by clebergnu** [comment]
Hi @philmd ,

Thanks for reporting this.

The error seems to be related to the [QMP socket dir](https://gitlab.com/qemu-project/qemu/-/blob/98f10f0e2613ba1ac2ad3f57a5174014f6dcb03d/tests/avocado/avocado_qemu/__init__.py#L309) which is used by the QEMU's `QEMUMachine` class.

IIRC, `sock_dir` is being set to a different value than `base_temp_dir` is exactly because it would be (on most systems) a shorter and valid path.

IIUC, there are two ways to shorten (and make it valid under darwin):

* Define a shorter [tempdir](https://docs.python.org/3/library/tempfile.html#tempfile.tempdir)
* Define a shorter prefix (from `avo_qemu_sock` to something like `sock`)

In any way, it seems that the the actual fix will be a change to QEMU.

**Comment by philmd** [comment]
> The error seems to be related to the [QMP socket dir](https://gitlab.com/qemu-project/qemu/-/blob/98f10f0e2613ba1ac2ad3f57a5174014f6dcb03d/tests/avocado/avocado_qemu/__init__.py#L309) which is used by the QEMU's `QEMUMachine` class.

Thanks @clebergnu , I reported [here](https://gitlab.com/qemu-project/qemu/-/issues/1316) in QEMU.
