### ISSUE TITLE
Job timeout selftest failures

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5544]
**Describe the bug**
The following tests are often failing as part of `make check`:
* `functional-parallel-71-selftests_functional_test_job_timeout.py_JobTimeOutTest.test_sleep_short_timeout`
* `functional-parallel-72-selftests_functional_test_job_timeout.py_JobTimeOutTest.test_sleep_short_timeout_with_test_methods`

**Steps to reproduce**
* run `make check`

**Expected behavior**
Tests passing.

**Current behavior**
Tests failing such as:

```
[stdout] ======================================================================
[stdout] FAIL: test_sleep_short_timeout (test_job_timeout.JobTimeOutTest)
[stdout] ----------------------------------------------------------------------
[stdout] Traceback (most recent call last):
[stdout]   File "/home/cleber/src/avocado/avocado/selftests/functional/test_job_timeout.py", line 126, in test_sleep_short_timeout
[stdout]     self.run_and_check(
[stdout]   File "/home/cleber/src/avocado/avocado/selftests/functional/test_job_timeout.py", line 89, in run_and_check
[stdout]     self.assertTrue(
[stdout] AssertionError: False is not true : Test /tmp/avocado_timeout_functionaleedfho2w/sleep.sh was not in JOB ID     : 787295ed18429faf0965d66a95564c57c9380652
[stdout] JOB LOG    : /tmp/avocado_JobTimeOutTest_us1mtotz/job-2022-12-07T14.35-787295e/job.log
[stdout] 
[stdout] RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
[stdout] JOB HTML   : /tmp/avocado_JobTimeOutTest_us1mtotz/job-2022-12-07T14.35-787295e/results.html
[stdout] JOB TIME   : 3.55 s
[stdout] .
[stdout] 
[stdout] ----------------------------------------------------------------------
[stdout] Ran 1 test in 5.319s
[stdout] 
[stdout] FAILED (failures=1)
```

And:

```
[stdout] ======================================================================
[stdout] FAIL: test_sleep_short_timeout_with_test_methods (test_job_timeout.JobTimeOutTest)
[stdout] ----------------------------------------------------------------------
[stdout] Traceback (most recent call last):
[stdout]   File "/home/cleber/src/avocado/avocado/selftests/functional/test_job_timeout.py", line 137, in test_sleep_short_timeout_with_test_methods
[stdout]     self.run_and_check(
[stdout]   File "/home/cleber/src/avocado/avocado/selftests/functional/test_job_timeout.py", line 89, in run_and_check
[stdout]     self.assertTrue(
[stdout] AssertionError: False is not true : Test /tmp/avocado_timeout_functionalzoeegr3q/sleep_test.py:Dummy.test00sleep was not in JOB ID     : 67f21be1b1aa817ce48dbf03ddc0026f3b8444bc
[stdout] JOB LOG    : /tmp/avocado_JobTimeOutTest_oyheunty/job-2022-12-07T14.35-67f21be/job.log
[stdout] 
[stdout] RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 3 | WARN 0 | INTERRUPT 0 | CANCEL 0
[stdout] JOB HTML   : /tmp/avocado_JobTimeOutTest_oyheunty/job-2022-12-07T14.35-67f21be/results.html
[stdout] JOB TIME   : 2.30 s
[stdout] .
[stdout] 
[stdout] ----------------------------------------------------------------------
[stdout] Ran 1 test in 4.226s
[stdout] 
[stdout] FAILED (failures=1)
```

**System information (please complete the following information):**
 - OS: `LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 36 (Thirty Six)
Release:	36
Codename:	ThirtySix`
 - Avocado version: 35778465721bcfae9788a1cf5ed264d56dc8070a
 - Avocado installation method: GIT

**Additional information**
Tests were modified as part of #5530

**Comment by clebergnu** [comment]
The issue seems to be related to a timing issue with the runners not having enough time to even be started and send back their statuses.   Example on a system with lots of resources:

```
$ avocado run --job-results-dir /tmp/ttt --disable-sysinfo --job-timeout=1 /tmp/py.py examples/tests/passtest.py 
JOB ID     : 196401ffcba9ff36750ca9d5b2cc804cacc15f76
JOB LOG    : /tmp/ttt/job-2022-12-07T15.12-196401f/job.log
 (2/4) /tmp/py.py:Dummy.test01pass: STARTED
 (1/4) /tmp/py.py:Dummy.test00sleep: STARTED
 (3/4) /tmp/py.py:Dummy.test02pass: STARTED
 (4/4) examples/tests/passtest.py:PassTest.test: STARTED
 (2/4) /tmp/py.py:Dummy.test01pass:  PASS (0.01 s)
 (4/4) examples/tests/passtest.py:PassTest.test:  PASS (0.01 s)
 (3/4) /tmp/py.py:Dummy.test02pass:  PASS (0.01 s)
 (1/4) /tmp/py.py:Dummy.test00sleep:  INTERRUPTED: Test interrupted: Timeout reached (0.56 s)

RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 1 | CANCEL 0
JOB HTML   : /tmp/ttt/job-2022-12-07T15.12-196401f/results.html
JOB TIME   : 1.51 s
```

And now with restrictions on the usage of a single CPU:


```
$ taskset -c 0 avocado run --job-results-dir /tmp/ttt --disable-sysinfo --job-timeout=1 /tmp/py.py examples/tests/passtest.py 
JOB ID     : 18df2b30d6f8bfadba00f79bb229d70d8eb8344b
JOB LOG    : /tmp/ttt/job-2022-12-07T15.12-18df2b3/job.log

RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 4 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /tmp/ttt/job-2022-12-07T15.12-18df2b3/results.html
JOB TIME   : 1.59 s
```

Because we can't control the availability of resources on all systems, one way is to give the job more time (but still less than the 10 seconds that will be spent on `sleep()` on one of the tests).
