### ISSUE TITLE
nrunner should have a back up plan for when port 8888 is taken

### ISSUE THREAD

**Issue by verdog** [avocado-framework/avocado#5550]
**Is your feature request related to a problem? Please describe.**
Multiple people on my team use avocado 99.0 on a shared development server. Only one of us can run a test suite at once because the status server (?) always binds to port 8888 with no backup plan.

If multiple people try to run tests, someone will see this:

```
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /.../avocado-virtual-environment/avocado/lib/python3.6/site-packages/avocado/core/status/server.py:41> exception=OSError(98, "error while attempting to bind on address ('127.0.0.1', 8888): address already in use")>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1073, in create_server
    sock.bind(sa)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../avocado-virtual-environment/avocado/lib/python3.6/site-packages/avocado/core/status/server.py", line 43, in serve_forever
    await self.create_server()
  File "/.../avocado-virtual-environment/avocado/lib/python3.6/site-packages/avocado/core/status/server.py", line 34, in create_server
    self.cb, host=host, port=port, limit=limit
  File "/usr/lib64/python3.6/asyncio/streams.py", line 119, in start_server
    return (yield from loop.create_server(factory, host, port, **kwds))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1077, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8888): address already in use
```

**Describe the solution you'd like**
If the user hasn't specified any specific options with `--status-server-listen` etc. and binding on port 8888 fails, try another port.

**Describe alternatives you've considered**
 `--status-server-disable-auto --status-server-listen 127.0.0.1:8889 --status-server-uri 127.0.0.1:8889` works but is impractical.

**Comment by verdog** [comment]
I like that. The most important thing for my use case in particular would be to make the auto behavior be equal to a range like that by default, without any extra flags.
