### ISSUE TITLE
Avocado crashed: ReaderError: unacceptable character #x007f: ...

### ISSUE THREAD

**Issue by ruda** [avocado-framework/avocado#560]
rmoura@thinkpad:avocado% ./scripts/avocado run  examples/tests/sleeptest.py -m examples/tests/sleeptest.py.data/sleeptest.yaml /usr/bin/true --job-timeout=3s 
Avocado crashed: ReaderError: unacceptable character #x007f: control characters are not allowed
  in "/usr/bin/true", position 0
Traceback (most recent call last):

  File "/home/rmoura/Work/avocado/avocado/job.py", line 313, in _run
    mux = multiplexer.Mux(self.args)

  File "/home/rmoura/Work/avocado/avocado/multiplexer.py", line 442, in __init__
    self.pools = parse_yamls(mux_files, filter_only, filter_out)

  File "/home/rmoura/Work/avocado/avocado/multiplexer.py", line 77, in parse_yamls
    input_tree = tree.create_from_yaml(input_yamls, debug)

  File "/home/rmoura/Work/avocado/avocado/core/tree.py", line 492, in create_from_yaml
    merge(data, path)

  File "/home/rmoura/Work/avocado/avocado/core/tree.py", line 475, in _merge
    data.merge(_create_from_yaml(path))

  File "/home/rmoura/Work/avocado/avocado/core/tree.py", line 452, in _create_from_yaml
    loaded_tree = yaml.load(stream, Loader)

  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()

  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()

  File "_yaml.pyx", line 702, in _yaml.CParser.get_single_node (ext/_yaml.c:8689)

  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:11673)

ReaderError: unacceptable character #x007f: control characters are not allowed
  in "/usr/bin/true", position 0

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
rmoura@thinkpad:avocado% ./scripts/avocado run  examples/tests/sleeptest.py /u

**Comment by adereis** [comment]
Fixed a while ago, closing.
