### ISSUE TITLE
Error message on badly formatted config file is amazingly cryptic

### ISSUE THREAD

**Issue by dgibson** [avocado-framework/avocado#5643]
**Describe the bug**

If the config file `~/.config/avocado/avocado.conf` contains badly formatted lines, the error message is astoundingly unhelpful.

**Steps to reproduce**

Place this in `~/.config/avocado/avocado.conf`:
```
[run]
max_parallel_tasks = 8

[job.output.testlogs]
statuses = ["CANCEL", "SKIP", "FAIL"]
	test build/cppcheck
	test build/clang_tidy
```
Note the nonsensical last two lines - in my case I'd accidentally pasted these from elsewhere.

**Expected behavior**

A useful error message, e.g. `Syntax error in config file ~/.config/avocado/avocado.conf, line 6`.

**Current behavior**

An extremely cryptic traceback:

```
$ avocado --test
Traceback (most recent call last):
  File "/bin/avocado", line 33, in <module>
    sys.exit(load_entry_point('avocado-framework==92.0', 'console_scripts', 'avocado')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/avocado", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/avocado/__init__.py", line 34, in <module>
    settings.merge_with_configs()
  File "/usr/lib/python3.11/site-packages/avocado/core/settings.py", line 512, in merge_with_configs
    self.update_option(namespace, value, convert=True)
  File "/usr/lib/python3.11/site-packages/avocado/core/settings.py", line 679, in update_option
    self._namespaces[namespace].set_value(value, convert)
  File "/usr/lib/python3.11/site-packages/avocado/core/settings.py", line 242, in set_value
    self._value = self._as_list(value)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/avocado/core/settings.py", line 200, in _as_list
    return ast.literal_eval(value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    test build/cppcheck
    ^^^^
SyntaxError: invalid syntax
```

This does include the line causing the problem, but there's no indication of which file it found the bad information in, nor even that this is during the parsing of configuration.  What is there is obscured by the many lines of Python traceback information.

**System information (please complete the following information):**
 - OS: Fedora 37
(Aside, I don't have `lsb_release` installed and I don't know what package it is in)
 - Avocado version: Avocado 92.0
(Note that I couldn't even run `avocado -v` until I figured out what was going wrong here)
 - Avocado installation method: rpm, `python3-avocado-92.0-1.fc37.noarch`

**Comment by richtja** [comment]
Hi @dgibson thank you for reporting this. Definitely, we should have better error handling here.

**Comment by clebergnu** [comment]
I've tried to come up with a quick fix, but turns out the evaluation is done with the content that is previously read from possibly a number of configuration files.

That is, the parsing of the list is done much later than the actual reading of the [(potentially multiple) files](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read), and there's a no 1:1 relationship between the content and which file it came from.

A deeper refactor would be needed, moving the parsing of the list syntax into a custom `ConfigParser` because it knows about the actual files and their lines.

**Comment by dgibson** [comment]
Good news, thanks.
