### ISSUE TITLE
Error running method "pre_tests" of plugin "fetchasset": 'Subscript' object has no attribute 'id' in avocado selftests

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5684]
**Describe the bug**
Avocado self tests shows error with `pre_tests` and `fetchasset` plugin. The error courses at the beginning of testing and it looks like that the tests are not evolved, because they are passing. You can see this even in our [pipelines](https://github.com/avocado-framework/avocado/actions/runs/4915011479/jobs/8777000288) 

**Steps to reproduce**
```
$ python setup.py test
/home/runner/work/avocado/avocado/setup.py:21: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.command.clean import clean  # pylint: disable=W0402
running test
Error running method "pre_tests" of plugin "fetchasset": 'Subscript' object has no attribute 'id'

Reproduced traceback from: /home/runner/work/avocado/avocado/avocado/core/extension_manager.py:224
Traceback (most recent call last):
  File "/home/runner/work/avocado/avocado/avocado/plugins/assets.py", line 279, in pre_tests
    fetch_assets(*candidate, logger)
  File "/home/runner/work/avocado/avocado/avocado/plugins/assets.py", line 227, in fetch_assets
    handler = FetchAssetHandler(test_file, klass, method)
  File "/home/runner/work/avocado/avocado/avocado/plugins/assets.py", line 67, in __init__
    self.visit(self.tree)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/home/runner/work/avocado/avocado/avocado/plugins/assets.py", line 143, in visit_ClassDef
    self.generic_visit(node)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/home/runner/work/avocado/avocado/avocado/plugins/assets.py", line 158, in visit_FunctionDef
    self.generic_visit(node)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/home/runner/work/avocado/avocado/avocado/plugins/assets.py", line 189, in visit_Assign
    name = node.targets[0].id
AttributeError: 'Subscript' object has no attribute 'id'

JOB ID     : 89f1f2d2984511ace9df8ed48cee3144f9678de6
JOB LOG    : /home/runner/avocado/job-results/job-2023-05-08T12.19-89f1f2d/job.log
 (nrunner-interface-2/100) selftests/functional/nrunner_interface.py:Interface.test_help;avocado-runner-noop: STARTED
 (nrunner-interface-1/100) selftests/functional/nrunner_interface.py:Interface.test_help;avocado-runner-dry-run: STARTED
 (nrunner-interface-1/100) selftests/functional/nrunner_interface.py:Interface.test_help;avocado-runner-dry-run:  PASS (0.47 s)
...
```

**Expected behavior**
avocado selftests without this error.

**Comment by richtja** [comment]
I was able to create a small reproducer for this issue.

```
from avocado import Test as t


class Test(t):

    def test(self):
        pom = {}
        pom["foo"] = []

```

**Comment by richtja** [comment]
@clebergnu, thanks I totally forget about this.
