### ISSUE TITLE
avocado jobs command is broken

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#6067]
**Describe the bug**
The `avocado jobs` command makes avocado crash. Bout `avocado jobs list`  and `avocado jobs show` is broken. 

**Steps to reproduce**
Just run `avocado jobs list` or `avocado jobs show latest`

**Expected behavior**
Avocado will provide useful information, and it won't crash.

**Current behavior**
```
$ avocado jobs list
...
abb1d9a7875e6dde3ad96fd4976a4c4bedb246bb 2024-10-30 10:44:49.229156   1 (0/0/1/0)
dc68076acdaa2ceb7a1f5b2a06164863f02abb91 2024-10-30 10:44:00.593955   1 (0/0/0/0)
64ca178a72bef056fc859b07fb5b648e49f8d60e 2024-10-30 10:43:51.515882   1 (0/0/0/0)
d34143063b6fb1611609e794154d7514beaa5c23 2024-10-29 16:19:51.930934   2 (2/0/0/0)
Avocado crashed unexpectedly: 'start'
Traceback (most recent call last):
  File "/home/janrichter/.pyenv/versions/avocado/bin/avocado", line 33, in <module>
    sys.exit(load_entry_point('avocado-framework', 'console_scripts', 'avocado')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/core/main.py", line 86, in main
    return app.run()
           ^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/core/app.py", line 111, in run
    return method(self.parser.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/plugins/jobs.py", line 189, in run
    return self.handle_list_command(results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/plugins/jobs.py", line 122, in handle_list_command
    job["start"],
    ~~~^^^^^^^^^
KeyError: 'start'

You can also find details in /home/janrichter/avocado/data/crashes/avocado-traceback-2024-11-08_11:11:50-45p8yhss.log
```

```
$ avocado jobs show latest
JOB ID      : latest
JOB LOG     : /home/janrichter/avocado/job-results/job-2024-11-07T14.26-c5f4066/job.log

Avocado crashed unexpectedly: 'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/janrichter/.pyenv/versions/avocado/bin/avocado", line 33, in <module>
    sys.exit(load_entry_point('avocado-framework', 'console_scripts', 'avocado')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/core/main.py", line 86, in main
    return app.run()
           ^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/core/app.py", line 111, in run
    return method(self.parser.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/plugins/jobs.py", line 191, in run
    return self.handle_show_command(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janrichter/Avocado/avocado/avocado/plugins/jobs.py", line 157, in handle_show_command
    self._print_job_tests(results_data.get("tests"))
  File "/home/janrichter/Avocado/avocado/avocado/plugins/jobs.py", line 60, in _print_job_tests
    end = datetime.fromtimestamp(test.get("actual_end", test.get("end")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer

You can also find details in /home/janrichter/avocado/data/crashes/avocado-traceback-2024-11-08_11:14:57-cj90psur.log
```

**System information (please complete the following information):**
 - OS: Fedora 40
 - Avocado version: master
 - Avocado installation method: github

**Comment by richtja** [comment]
Hi @clebergnu, thanks for the testing. So IIUIC the `avocado jobs show latest` is not some corner case with corrupted test results, it just simply doesn't work on avocado 108. Therefore, I will move this into current milestone as any other normal bug.
