### ISSUE TITLE
Investigation of avocado build failures

### ISSUE THREAD

**Issue by lmr** [avocado-framework/avocado#792]
An interesting side effect of @clebergnu's work of ditching nose and standardizing all the unittests and functional tests is that all the tests are run at rpm build time. While a great idea, it made building our avocado packages on different chroots challenging. Here are the problems I've faced so far:

Success

    epel-6-i386: OK
    epel-6-x86_64: OK
    epel-7-x86_64: OK
    fedora-22-x86_64: OK
    fedora-22-i386: OK

    Failures

    fedora-rawhide-i386:

    ======================================================================
    ERROR: test_build_docs (selftests.doc.test_doc_build.DocBuildTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/doc/test_doc_build.py", line 54, in test_build_docs
        raise DocBuildError(e_msg)
    DocBuildError: 3 ERRORS and/or WARNINGS detected while building the html docs:
    1) /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.rst:17: WARNING: autodoc: failed to import module u'avocado.core.restclient.connection'; the following exception was raised:
    2) /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.app'; the following exception was raised:
    3) /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.actions.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.actions.server'; the following exception was raised:
    Full output: make: Entering directory '/builddir/build/BUILD/avocado-0.28.0/docs'
    sphinx-build -b html -d build/doctrees   source build/html
    Making output directory...
    Running Sphinx v1.2.3
    loading pickled environment... not yet created
    loading intersphinx inventory from http://docs.python.org/objects.inv...
    building [html]: targets for 24 source files that are out of date
    updating environment: 24 added, 0 changed, 0 removed
    reading sources... [  4%] Configuration
    reading sources... [  8%] ContributionGuide
    reading sources... [ 12%] DebuggingWithGDB
    reading sources... [ 16%] DevelopmentTips
    reading sources... [ 20%] GetStartedGuide
    reading sources... [ 25%] Introduction
    reading sources... [ 29%] MultiplexConfig
    reading sources... [ 33%] Plugins
    reading sources... [ 37%] ReferenceGuide
    reading sources... [ 41%] ResultFormats
    reading sources... [ 45%] RunningTestsRemotely
    reading sources... [ 50%] WrapProcess
    reading sources... [ 54%] WritingTests
    reading sources... [ 58%] api/core/avocado.core
    reading sources... [ 62%] api/core/avocado.core.plugins
    reading sources... [ 66%] api/core/avocado.core.remote
    reading sources... [ 70%] api/core/avocado.core.restclient
    reading sources... [ 75%] api/core/avocado.core.restclient.cli
    reading sources... [ 79%] api/core/avocado.core.restclient.cli.actions
    reading sources... [ 83%] api/core/avocado.core.restclient.cli.args
    reading sources... [ 87%] api/test/avocado
    reading sources... [ 91%] api/utils/avocado.utils
    reading sources... [ 95%] api/utils/avocado.utils.external
    reading sources... [100%] index
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... done
    preparing documents... done
    writing output... [  4%] Configuration
    writing output... [  8%] ContributionGuide
    writing output... [ 12%] DebuggingWithGDB
    writing output... [ 16%] DevelopmentTips
    writing output... [ 20%] GetStartedGuide
    writing output... [ 25%] Introduction
    writing output... [ 29%] MultiplexConfig
    writing output... [ 33%] Plugins
    writing output... [ 37%] ReferenceGuide
    writing output... [ 41%] ResultFormats
    writing output... [ 45%] RunningTestsRemotely
    writing output... [ 50%] WrapProcess
    writing output... [ 54%] WritingTests
    writing output... [ 58%] api/core/avocado.core
    writing output... [ 62%] api/core/avocado.core.plugins
    writing output... [ 66%] api/core/avocado.core.remote
    writing output... [ 70%] api/core/avocado.core.restclient
    writing output... [ 75%] api/core/avocado.core.restclient.cli
    writing output... [ 79%] api/core/avocado.core.restclient.cli.actions
    writing output... [ 83%] api/core/avocado.core.restclient.cli.args
    writing output... [ 87%] api/test/avocado
    writing output... [ 91%] api/utils/avocado.utils
    writing output... [ 95%] api/utils/avocado.utils.external
    writing output... [100%] index
    writing additional files... genindex py-modindex search
    copying images... [ 50%] diagram.png
    copying images... [100%] modules.png
    copying static files... done
    copying extra files... done
    dumping search index... done
    dumping object inventory... done
    build succeeded, 3 warnings.
    Build finished. The HTML pages are in build/html.
    make: Leaving directory '/builddir/build/BUILD/avocado-0.28.0/docs'
    /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.rst:17: WARNING: autodoc: failed to import module u'avocado.core.restclient.connection'; the following exception was raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/connection.py", line 22, in <module>
        import requests
    ImportError: No module named requests
    /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.app'; the following exception was raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/cli/app.py", line 26, in <module>
        from .. import connection
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/connection.py", line 22, in <module>
        import requests
    ImportError: No module named requests
    /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.actions.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.actions.server'; the following exception was raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/cli/actions/server.py", line 10, in <module>
        from ... import connection
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/connection.py", line 22, in <module>
        import requests
    ImportError: No module named requests
    Please check the output and fix your docstrings/.rst docs
    ----------------------------------------------------------------------
    Ran 262 tests in 58.913s
    FAILED (errors=1)

    fedora-rawhide-x86_64:

    ======================================================================
    ERROR: test_build_docs (selftests.doc.test_doc_build.DocBuildTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/doc/test_doc_build.py", line 54, in test_build_docs
        raise DocBuildError(e_msg)
    DocBuildError: 3 ERRORS and/or WARNINGS detected while building the html docs:
    1) /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.rst:17: WARNING: autodoc: failed to import module u'avocado.core.restclient.connection'; the following exception was raised:
    2) /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.app'; the following exception was raised:
    3) /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.actions.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.actions.server'; the following exception was raised:
    Full output: make: Entering directory '/builddir/build/BUILD/avocado-0.28.0/docs'
    sphinx-build -b html -d build/doctrees   source build/html
    Making output directory...
    Running Sphinx v1.2.3
    loading pickled environment... not yet created
    loading intersphinx inventory from http://docs.python.org/objects.inv...
    building [html]: targets for 24 source files that are out of date
    updating environment: 24 added, 0 changed, 0 removed
    reading sources... [  4%] Configuration
    reading sources... [  8%] ContributionGuide
    reading sources... [ 12%] DebuggingWithGDB
    reading sources... [ 16%] DevelopmentTips
    reading sources... [ 20%] GetStartedGuide
    reading sources... [ 25%] Introduction
    reading sources... [ 29%] MultiplexConfig
    reading sources... [ 33%] Plugins
    reading sources... [ 37%] ReferenceGuide
    reading sources... [ 41%] ResultFormats
    reading sources... [ 45%] RunningTestsRemotely
    reading sources... [ 50%] WrapProcess
    reading sources... [ 54%] WritingTests
    reading sources... [ 58%] api/core/avocado.core
    reading sources... [ 62%] api/core/avocado.core.plugins
    reading sources... [ 66%] api/core/avocado.core.remote
    reading sources... [ 70%] api/core/avocado.core.restclient
    reading sources... [ 75%] api/core/avocado.core.restclient.cli
    reading sources... [ 79%] api/core/avocado.core.restclient.cli.actions
    reading sources... [ 83%] api/core/avocado.core.restclient.cli.args
    reading sources... [ 87%] api/test/avocado
    reading sources... [ 91%] api/utils/avocado.utils
    reading sources... [ 95%] api/utils/avocado.utils.external
    reading sources... [100%] index
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... done
    preparing documents... done
    writing output... [  4%] Configuration
    writing output... [  8%] ContributionGuide
    writing output... [ 12%] DebuggingWithGDB
    writing output... [ 16%] DevelopmentTips
    writing output... [ 20%] GetStartedGuide
    writing output... [ 25%] Introduction
    writing output... [ 29%] MultiplexConfig
    writing output... [ 33%] Plugins
    writing output... [ 37%] ReferenceGuide
    writing output... [ 41%] ResultFormats
    writing output... [ 45%] RunningTestsRemotely
    writing output... [ 50%] WrapProcess
    writing output... [ 54%] WritingTests
    writing output... [ 58%] api/core/avocado.core
    writing output... [ 62%] api/core/avocado.core.plugins
    writing output... [ 66%] api/core/avocado.core.remote
    writing output... [ 70%] api/core/avocado.core.restclient
    writing output... [ 75%] api/core/avocado.core.restclient.cli
    writing output... [ 79%] api/core/avocado.core.restclient.cli.actions
    writing output... [ 83%] api/core/avocado.core.restclient.cli.args
    writing output... [ 87%] api/test/avocado
    writing output... [ 91%] api/utils/avocado.utils
    writing output... [ 95%] api/utils/avocado.utils.external
    writing output... [100%] index
    writing additional files... genindex py-modindex search
    copying images... [ 50%] diagram.png
    copying images... [100%] modules.png
    copying static files... done
    copying extra files... done
    dumping search index... done
    dumping object inventory... done
    build succeeded, 3 warnings.
    Build finished. The HTML pages are in build/html.
    make: Leaving directory '/builddir/build/BUILD/avocado-0.28.0/docs'
    /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.rst:17: WARNING: autodoc: failed to import module u'avocado.core.restclient.connection'; the following exception was raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/connection.py", line 22, in <module>
        import requests
    ImportError: No module named requests
    /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.app'; the following exception was raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/cli/app.py", line 26, in <module>
        from .. import connection
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/connection.py", line 22, in <module>
        import requests
    ImportError: No module named requests
    /builddir/build/BUILD/avocado-0.28.0/docs/source/api/core/avocado.core.restclient.cli.actions.rst:18: WARNING: autodoc: failed to import module u'avocado.core.restclient.cli.actions.server'; the following exception was raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/cli/actions/server.py", line 10, in <module>
        from ... import connection
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/core/restclient/connection.py", line 22, in <module>
        import requests
    ImportError: No module named requests
    Please check the output and fix your docstrings/.rst docs
    ----------------------------------------------------------------------
    Ran 262 tests in 55.893s
    FAILED (errors=1)

    fedora-21-x86_64:

    ======================================================================
    ERROR: test_badly_behaved (selftests.functional.test_interrupt.InterruptTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 99, in test_badly_behaved
        wait.wait_for(wait_until_no_badtest, timeout=2)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/utils/wait.py", line 28, in wait_for
        output = func()
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 88, in wait_until_no_badtest
        for p in psutil.pids():
    AttributeError: 'module' object has no attribute 'pids'
    ======================================================================
    ERROR: test_well_behaved (selftests.functional.test_interrupt.InterruptTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 140, in test_well_behaved
        wait.wait_for(wait_until_no_goodtest, timeout=2)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/utils/wait.py", line 28, in wait_for
        output = func()
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 129, in wait_until_no_goodtest
        for p in psutil.pids():
    AttributeError: 'module' object has no attribute 'pids'
    ----------------------------------------------------------------------
    Ran 262 tests in 57.053s
    FAILED (errors=2)

    fedora-21-i386:

    ======================================================================
    ERROR: test_badly_behaved (selftests.functional.test_interrupt.InterruptTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 99, in test_badly_behaved
        wait.wait_for(wait_until_no_badtest, timeout=2)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/utils/wait.py", line 28, in wait_for
        output = func()
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 88, in wait_until_no_badtest
        for p in psutil.pids():
    AttributeError: 'module' object has no attribute 'pids'
    ======================================================================
    ERROR: test_well_behaved (selftests.functional.test_interrupt.InterruptTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 140, in test_well_behaved
        wait.wait_for(wait_until_no_goodtest, timeout=2)
      File "/builddir/build/BUILD/avocado-0.28.0/avocado/utils/wait.py", line 28, in wait_for
        output = func()
      File "/builddir/build/BUILD/avocado-0.28.0/selftests/functional/test_interrupt.py", line 129, in wait_until_no_goodtest
        for p in psutil.pids():
    AttributeError: 'module' object has no attribute 'pids'
    ----------------------------------------------------------------------
    Ran 262 tests in 61.469s
    FAILED (errors=2)

    fedora-22-ppc64le: 

    Mock Version: 1.2.12
    ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target ppc64le --nodeps /builddir/build/SPECS/avocado.spec'], chrootPath='/var/lib/mock/fedora-22-ppc64le-mockbuilder-6508/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x3fff8aae6a50>uid=1000)
    Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target ppc64le --nodeps /builddir/build/SPECS/avocado.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'} and shell False
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    Building target platforms: ppc64le
    Building for target ppc64le
    Wrote: /builddir/build/SRPMS/avocado-0.28.0-2.fc22.src.rpm
    Child return code was: 0
    LEAVE do --> 

    fedora-21-ppc64le:

    Mock Version: 1.2.12
    ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target ppc64le --nodeps /builddir/build/SPECS/avocado.spec'], chrootPath='/var/lib/mock/fedora-21-ppc64le-mockbuilder-3473/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x3fffa28e6a50>uid=1000)
    Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target ppc64le --nodeps /builddir/build/SPECS/avocado.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'} and shell False
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    Building target platforms: ppc64le
    Building for target ppc64le
    Wrote: /builddir/build/SRPMS/avocado-0.28.0-2.fc21.src.rpm
    Child return code was: 0
    LEAVE do --> 

    fedora-23-i386:

    Mock Version: 1.2.12
    ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target i686 --nodeps /builddir/build/SPECS/avocado.spec'], chrootPath='/var/lib/mock/fedora-23-i386-mockbuilder-7204/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x7fb84b82a690>uid=1001)
    Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target i686 --nodeps /builddir/build/SPECS/avocado.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'} and shell False
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    Building target platforms: i686
    Building for target i686
    Wrote: /builddir/build/SRPMS/avocado-0.28.0-2.fc23.src.rpm
    Child return code was: 0
    LEAVE do --> 

    fedora-23-x86_64:

    Mock Version: 1.2.12
    ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/avocado.spec'], chrootPath='/var/lib/mock/fedora-23-x86_64-mockbuilder-6780/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x7fedadd1b6d0>uid=1001)
    Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/avocado.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'} and shell False
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    Building target platforms: x86_64
    Building for target x86_64
    Wrote: /builddir/build/SRPMS/avocado-0.28.0-2.fc23.src.rpm
    Child return code was: 0
    LEAVE do --> 

    fedora-23-ppc64le:

    Mock Version: 1.2.12
    ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target ppc64le --nodeps /builddir/build/SPECS/avocado.spec'], chrootPath='/var/lib/mock/fedora-23-ppc64le-mockbuilder-4866/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x3fff90c36a50>uid=1000)
    Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target ppc64le --nodeps /builddir/build/SPECS/avocado.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/builddir', 'HOSTNAME': 'mock'} and shell False
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    sh: /usr/bin/python: No such file or directory
    Building target platforms: ppc64le
    Building for target ppc64le
    Wrote: /builddir/build/SRPMS/avocado-0.28.0-2.fc23.src.rpm
    Child return code was: 0
    LEAVE do -->

**Comment by lmr** [comment]
So basically:

* Rawhide: `requests` can't be important even though `python-requests` is specified in the spec file
* Fedora 21: `psutil` is too old (related to #774)
* Fedora 23, and `ppc64le` targets: Some unfathomable error, the build simply dies and not much information is there for us to debug.

Some issues are workable, some others I'm assuming are simply COPR problems.

**Comment by lmr** [comment]
@ldoktor, if you are curious to see how my last attempt to build avocado for `ppc64le` targets, look at my report.

**Comment by lmr** [comment]
After some research on the Rawhide failures, the problem seems to be:

https://bugzilla.redhat.com/show_bug.cgi?id=1253823

Long story short, `requests` requires `urllib3` dependency to a very specific one (1.10.4), and rawhide ships with the incompatible 1.11.0. Oh, the joys of distro dependency hell. So this really doesn't seem to be our fault and we'll skip building on rawhide until this gets fixed.

**Comment by lmr** [comment]
The problem in Fedora 21 should be fixed by https://github.com/avocado-framework/avocado/pull/794.

**Comment by lmr** [comment]
For F23 and other targets: I still have no idea what's going on.

**Comment by lmr** [comment]
OK, I've figured out what's wrong - aexpect has not been built for these architectures, making it not possible to progress with install. I can fix it by sending a new aexpect build for all chroots.

**Comment by lmr** [comment]
After fixing the `aexpect` build for all architectures, we're all in the clear, since the last remaining problem is due to the dependency problems of Rawhide (nothing related with avocado itself).
